import React,{useEffect,useState} from 'react';
import {View,Text,TextInput,TouchableOpacity} from 'react-native';
import {useThemeContext} from '../contexts/ThemeContext';
import {fetchMobileDetails,MOBILE_PROFILE_FIELDS,saveMobileBusinessProfile} from '../lib/onthegoDetails';
import {safeBusinessUrl} from '../lib/onthego';
export default function OnTheGoProfileEditor({placeId}:{placeId:string}){const [open,setOpen]=useState(false);const {isDark}=useThemeContext();return <View><TouchableOpacity accessibilityRole="button" accessibilityState={{expanded:open}} onPress={()=>setOpen(!open)} style={{padding:12,minHeight:44}}><Text style={{color:isDark?'#fff':'#17013a',fontWeight:'700'}}>Edit business information {open?'−':'+'}</Text></TouchableOpacity>{open&&<Fields key={placeId} placeId={placeId}/>}</View>;}
function Fields({placeId}:{placeId:string}){
 const {isDark}=useThemeContext(),color=isDark?'#fff':'#17013a';const [draft,setDraft]=useState<Record<string,string>|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setDraft(null);setMessage('');fetchMobileDetails({tavvyPlaceId:placeId}).then(data=>{if(!active)return;if(!data)throw Error('Business not found.');setDraft(Object.fromEntries(MOBILE_PROFILE_FIELDS.map(([key])=>[key,String(data.place[key]||'')])));}).catch(()=>active&&setMessage('Unable to load your business information.'));return()=>{active=false;};},[placeId,attempt]);
 const save=async()=>{if(!draft||busy)return;setBusy(true);setMessage('');try{const values={...draft};for(const key of ['website','instagram','facebook','twitter','tiktok'])if(values[key]?.trim()){const url=safeBusinessUrl(values[key]);if(!url)throw Error('Enter a valid website or social URL.');values[key]=url;}await saveMobileBusinessProfile(placeId,values);setDraft(values);setMessage('Business information saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save. Your changes are still here.');}finally{setBusy(false);}};
 const button=(label:string,action:()=>void)=><TouchableOpacity accessibilityRole="button" disabled={busy} onPress={action} style={{padding:12,minHeight:44,backgroundColor:'#70059b',borderRadius:10,marginVertical:8}}><Text style={{color:'#fff'}}>{label}</Text></TouchableOpacity>;
 return <View>{draft?<><Text style={{color,lineHeight:22}}>Your current stop is managed separately below. Usual hours do not mark you as live.</Text>{MOBILE_PROFILE_FIELDS.map(([key,label])=><View key={key}><Text style={{color,marginTop:12}}>{label}</Text><TextInput accessibilityLabel={label} value={draft[key]} onChangeText={value=>setDraft({...draft,[key]:value})} editable={!busy} multiline={key==='description'||key==='hours_display'} autoCapitalize={['website','instagram','facebook','twitter','tiktok','email'].includes(key)?'none':'sentences'} keyboardType={key==='email'?'email-address':key==='phone'?'phone-pad':'default'} style={{color,padding:12,minHeight:46,backgroundColor:isDark?'#292331':'#f1edf6',borderWidth:1,borderColor:isDark?'#50445c':'#d6cbdf',borderRadius:10,marginTop:6}}/></View>)}{button(busy?'Saving…':'Save business information',()=>void save())}</>:message?button('Retry loading information',()=>setAttempt(n=>n+1)):<Text style={{color}}>Loading business information…</Text>}<Text accessibilityLiveRegion="polite" style={{color,lineHeight:22,marginVertical:8}}>{message}</Text></View>;
}
