/** Execute the real native Settings component/press handlers with isolated hooks and no native/network runtime. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function load(file,mocks={}){const api={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React}}).outputText,{exports:api,require:n=>{if(n in mocks)return mocks[n];throw Error('Unexpected dependency '+n)},console,URL,URLSearchParams});return api;}
const availability=load('lib/accountDeletion.ts'),copy=load('lib/accountDeletionCopy.ts');
function harness(){let actor={user:{id:'A'},session:{access_token:'a'},signOut:()=>{throw Error('Unexpected signout')}},locale='en',slots=[],cursor=0,effects=[],cleanups=[],alerts=[],pending;
 const react={createElement:(type,props,...children)=>({type,props:{...props,children}}),useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>slots[i]=v]},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i]},useEffect:(fn,deps)=>{const i=cursor++,prior=slots[i];if(!prior||deps.some((d,n)=>d!==prior[n])){slots[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=fn()})}}};react.default=react;
 const native={StyleSheet:{create:x=>x},Alert:{alert:(...a)=>alerts.push(a)}};for(const name of ['View','Text','TouchableOpacity','ScrollView','SafeAreaView','Switch','ActivityIndicator'])native[name]=name;
 const mocks={react,'react-native':native,'expo-constants':{default:{expoConfig:{version:'test'}}},'../hooks/useReleaseCopy':{useReleaseCopy:()=>x=>x},'../lib/accountDeletion':{...availability,getAccountDeletionAvailability:()=>new Promise(resolve=>pending=resolve)},'../lib/accountDeletionCopy':copy,'@react-navigation/native':{useNavigation:()=>({navigate:()=>{throw Error('Unexpected navigation')},goBack:()=>{}})},'@expo/vector-icons':{Ionicons:'Icon'},'react-i18next':{useTranslation:()=>({t:(key,opt)=>opt?.defaultValue||key,i18n:{language:locale}})},'../contexts/ThemeContext':{useThemeContext:()=>({theme:{}})},'../contexts/AuthContext':{useAuth:()=>actor},'../components/LanguageSelector':{InlineLanguageSelector:'Language'},'../components/ReviewTranslation':{AutoTranslateToggle:'AutoTranslate'},'../components/BlockedAuthors':{default:'BlockedAuthors'},'../components/AppearanceSelector':{default:'Appearance'}};
 const Component=load('screens/SettingsScreen.tsx',mocks).default;
 function render(){cursor=0;const tree=Component();while(effects.length)effects.shift()();return tree;}
 function all(node){if(!node||typeof node!=='object')return[];if(Array.isArray(node))return node.flatMap(all);return[node,...all(node.props?.children)]}
 function deletion(){return all(render()).find(n=>n.type==='TouchableOpacity'&&all(n).some(c=>c.type==='Text'&&c.props.children.includes('auth.deleteAccount')))}
 return{render,deletion,alerts,resolve:()=>pending({status:'unavailable',code:'ACCOUNT_DELETION_UNAVAILABLE'}),switchActor:(id,token)=>{actor={...actor,user:{id},session:{access_token:token}};render()},locale:x=>{locale=x},unmount:()=>cleanups.forEach(fn=>fn?.())};
}
test('native Delete Account stays reachable and reports unavailable without success/navigation',async()=>{const h=harness();const done=h.deletion().props.onPress();h.resolve();await done;assert.equal(h.alerts.length,1);assert.match(h.alerts[0][1],/cannot be started/);assert.match(h.alerts[0][1],/has not sent a deletion request/);assert.equal(h.alerts[0][2].length,1);assert.equal(h.alerts[0][2][0].onPress,undefined);});
test('late response after account or same-account session change is suppressed',async()=>{for(const [id,token] of [['B','b'],['A','new-a']]){const h=harness();const done=h.deletion().props.onPress();h.switchActor(id,token);h.resolve();await done;assert.equal(h.alerts.length,0);}});
test('unmount suppresses late alert and state response',async()=>{const h=harness();const done=h.deletion().props.onPress();h.unmount();h.resolve();await done;assert.equal(h.alerts.length,0);});
test('Portuguese/Spanish native deletion status uses localized copy',async()=>{for(const locale of ['pt','es']){const h=harness();h.locale(locale);const done=h.deletion().props.onPress();h.resolve();await done;assert.equal(h.alerts[0][1],copy.accountDeletionCopy(locale).unavailable+'\n\n'+copy.accountDeletionCopy(locale).unchanged);}});
test('AuthContext delete action never clears a session when deletion is unavailable',async()=>{let slots=0,changes=0;const react={createContext:()=>({Provider:'Provider'}),createElement:(type,props)=>({type,props}),useState:()=>[[{id:'A'},{access_token:'a'},null,true][slots++],()=>changes++],useCallback:fn=>fn,useEffect:()=>{}};react.default=react;
 const Auth=load('contexts/AuthContext.tsx',{react,'../lib/accountDeletion':availability,'expo-web-browser':{},'../lib/supabaseClient':{supabase:new Proxy({},{get:()=>{throw Error('Unexpected Supabase call')}})},'@supabase/supabase-js':{}});
 const tree=Auth.AuthProvider({children:null});await assert.rejects(tree.props.value.deleteAccount(),e=>e.code==='ACCOUNT_DELETION_UNAVAILABLE');assert.equal(changes,0);
});
