const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const file=path.resolve(__dirname,'../../screens/PlaceDetailsScreen.tsx'),source=fs.readFileSync(file,'utf8'),ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),arrows={};let reviewPress,locationEffect;
function visit(node){if(ts.isVariableDeclaration(node)&&ts.isIdentifier(node.name)&&node.initializer&&ts.isArrowFunction(node.initializer))arrows[node.name.text]=node.initializer.getText(ast);if(ts.isJsxAttribute(node)&&node.name.getText(ast)==='onPress'&&node.initializer?.getText(ast).includes("navigation.navigate('AddReview'"))reviewPress=node.initializer.expression.getText(ast);if(ts.isCallExpression(node)&&node.expression.getText(ast)==='useEffect'&&node.arguments[0]?.getText(ast).includes('locationRequested.current'))locationEffect=node.arguments[0].getText(ast);ts.forEachChild(node,visit)}visit(ast);
function fn(text,context){vm.runInNewContext(ts.transpileModule('globalThis.run='+text,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);return context.run}
for(const previous of [true,false])test('ship breadcrumb '+(previous?'returns to existing ship state':'opens exact parent when entered directly'),()=>{const calls=[],context={cruiseVenue:{universe_id:'ship-universe'},navigation:{getState:()=>({index:1,routes:[{name:previous?'UniverseDetail':'Home',params:{universeId:'ship-universe'}},{name:'PlaceDetails'}]}),goBack:()=>calls.push('back'),navigate:(name,args)=>calls.push([name,args])}};fn(arrows.openParentShip,context)();if(previous)assert.deepEqual(calls,['back']);else{assert.equal(calls[0][0],'UniverseDetail');assert.equal(calls[0][1].universeId,'ship-universe')}});
test('announced venue actual review handler never navigates to composer',()=>{let calls=0;fn(reviewPress,{reviewDisabled:true,navigation:{navigate(){calls++}}})();assert.equal(calls,0)});
test('operating venue actual review handler uses canonical place/category',()=>{const calls=[],place={id:'venue-place',name:'Dining',primaryCategory:'restaurant'};fn(reviewPress,{reviewDisabled:false,place,navigation:{navigate:(...v)=>calls.push(v)}})();assert.equal(calls[0][0],'AddReview');assert.equal(calls[0][1].placeId,'venue-place');assert.equal(calls[0][1].primaryCategory,'restaurant')});
test('onboard directions cannot create a navigation destination',()=>{const calls=[];fn(arrows.handleNavigate,{place:{cruiseVenue:{}},setNavDestination:()=>calls.push('destination'),setShowNavModal:()=>calls.push('modal'),Number})(0,0,'Dining');assert.deepEqual(calls,[])});
test('existing ordinary place with valid coordinates still navigates',()=>{const calls=[];fn(arrows.handleNavigate,{place:{},setNavDestination:v=>calls.push(v),setShowNavModal:v=>calls.push(v),Number})(42,-71,'Known place');assert.equal(calls[0].lat,42);assert.equal(calls[1],true)});
test('onboard Story/claim action guard does not resolve/create a place or open sign-in',async()=>{let calls=0;const run=fn(arrows.openCanonicalPlaceAction,{place:{cruiseVenue:{}},user:null,navigation:{navigate(){calls++}},resolvePhotoPlace(){assert.fail('No identity mutation')}});await run('StoryUpload');await run('ClaimBusiness');assert.equal(calls,0)});
test('onboard details never request GPS just to show venue information',()=>{let calls=0;const locationRequested={current:false};fn(locationEffect,{place:{id:'venue',cruiseVenue:{}},locationRequested,Location:{requestForegroundPermissionsAsync(){calls++}},console})();assert.equal(calls,0);assert.equal(locationRequested.current,false)});
test('ordinary details retain the one-time location request',async()=>{let calls=0;const locationRequested={current:false};const run=fn(locationEffect,{place:{id:'ordinary'},locationRequested,Location:{requestForegroundPermissionsAsync:async()=>{calls++;return{status:'denied'}}},console:{log(){},error(){}}});run();run();await Promise.resolve();assert.equal(calls,1)});
