const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
function harness(){
 const slots=[],effects=[],timers=new Map(),requests=[],facets=[],featured=[],navigations=[];let cursor=0,nextTimer=0,dirty=true,tree,dismissals=0;
 const react={Fragment:'Fragment',createElement:(type,props,...children)=>({type,props:{...props,children}}),useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>{const value=typeof v==='function'?v(slots[i]):v;if(value!==slots[i]){slots[i]=value;dirty=true}}]},useEffect(fn,deps){const i=cursor++;const old=slots[i];if(!old||deps.some((v,j)=>v!==old.deps[j])){old?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=fn()})}}};
 const directoryState={};new Function('exports',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../lib/cruises/directoryState.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(directoryState);
 const deferred=(list,args)=>new Promise((resolve,reject)=>list.push({args,resolve,reject}));
 const exports={};const dependencies={'../ToolHeader':{default:'ToolHeader'},react:{...react,default:react},'react-native':new Proxy({StyleSheet:{create:x=>x},Keyboard:{dismiss:()=>{dismissals++}}},{get:(o,k)=>o[k]||k}),'@react-navigation/native':{useNavigation:()=>({navigate:(...args)=>navigations.push(args)})},'@expo/vector-icons':{Ionicons:'Icon'},'../../contexts/ThemeContext':{useThemeContext:()=>({theme:{}})},'../../lib/cruises/catalog':{safeCruiseUrl:x=>/^https:/.test(x||'')?x:null},'../../lib/cruises/directoryState':directoryState,'../../lib/cruises/service':{searchCruiseShips:args=>deferred(requests,args),getCruiseOperators:()=>deferred(facets),getFeaturedCruiseShips:args=>deferred(featured,args)}};
 const code=ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../components/cruises/CruiseDirectory.tsx'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2022}}).outputText;
 new Function('require','exports','setTimeout','clearTimeout',code)(name=>{assert(name in dependencies,name);return dependencies[name]},exports,(fn)=>{const id=++nextTimer;timers.set(id,fn);return id},id=>timers.delete(id));
 const render=()=>{for(let i=0;dirty&&i<15;i++){dirty=false;cursor=0;tree=exports.default({onBack:()=>navigations.push(['back'])});effects.splice(0).forEach(fn=>fn())}return tree};
 function all(node=tree){return !node||typeof node!=='object'?[]:[node,...(node.props?.children||[]).flat(Infinity).flatMap(all)]}
 const text=(node=tree)=>typeof node==='string'?node:node&&typeof node==='object'?(node.props?.children||[]).flat(Infinity).map(text).join(''):'';
 const press=label=>{const node=all().find(x=>x.type==='TouchableOpacity'&&(text(x)===label||x.props?.accessibilityLabel===label));assert(node,'button '+label);node.props.onPress();render()};
 const type=(label,value)=>{const node=all().find(x=>x.type==='TextInput'&&x.props.accessibilityLabel===label);assert(node,'input '+label);node.props.onChangeText(value);render()};
 const tick=async()=>{render();const pending=[...timers.values()];timers.clear();pending.forEach(fn=>fn());await new Promise(r=>setImmediate(r));render()};
 render();return {requests,facets,featured,navigations,press,type,tick,text,all,render,get dismissals(){return dismissals}};
}
const ship=(id,name)=>({ship:{id,universe_id:'universe-'+id,slug:id,name,operator_name:'Fixture line',kind:'ocean',operating_status:'operating',photo:null}});
test('selected tabs keep loaded ships, pagination uses canonical Universe IDs, and stale pages cannot replace a new filter',async()=>{
 const h=harness();await h.tick();assert.equal(h.requests[0].args.status,'operating');h.requests[0].resolve({ships:[ship('one','Ship One')],hasMore:true});await h.tick();assert.match(h.text(),/Ship One/);
 h.press('All types');h.press('Operating ships');await h.tick();assert.equal(h.requests.length,1);assert.match(h.text(),/Ship One/);
 const card=h.all().find(x=>x.type==='TouchableOpacity'&&h.text(x).includes('Ship One'));card.props.onPress();assert.deepEqual(h.navigations[0],['UniverseLanding',{universeId:'universe-one'}]);assert(h.all().some(x=>x.props?.accessibilityLabel==='No verified ship photo'));
 h.press('Load more ships');await h.tick();assert.equal(h.requests[1].args.offset,1);h.press('River');await h.tick();assert.equal(h.requests[2].args.kind,'river');assert.equal(h.requests[2].args.offset,0);h.requests[2].resolve({ships:[ship('river','River Fixture')],hasMore:false});await h.tick();h.requests[1].resolve({ships:[ship('old','Stale Old Ship')],hasMore:false});await h.tick();assert.match(h.text(),/River Fixture/);assert(!h.text().includes('Stale Old Ship'));
});
test('failed reads show a retry instead of an empty verified fleet; announced selection stays separate',async()=>{
 const h=harness();await h.tick();h.requests[0].reject(Error('Ships unavailable'));await h.tick();assert.match(h.text(),/Ships unavailable/);assert(!h.text().includes('No verified ships match these filters.'));h.press('Try again');await h.tick();h.requests[1].resolve({ships:[],hasMore:false});await h.tick();assert.match(h.text(),/No verified ships match these filters./);h.press('Announced ships');await h.tick();assert.equal(h.requests[2].args.status,'announced');
});
const operators=[{id:'msc-cruises',name:'MSC Cruises'},{id:'royal-caribbean-international',name:'Royal Caribbean International'}];
test('full operator facets are searchable, selected company is a no-op, and company composes with type/status/query',async()=>{
 const h=harness();await h.tick();h.facets[0].resolve(operators);h.requests[0].resolve({ships:[ship('other','Other fleet')],hasMore:false});await h.tick();h.press('Cruise line: All cruise lines');h.type('Search cruise lines','msc');assert(h.text().includes('MSC Cruises'));assert(!h.text().includes('Royal Caribbean International'));h.press('MSC Cruises');await h.tick();assert.equal(h.requests[1].args.operatorId,'msc-cruises');assert.equal(h.requests[1].args.offset,0);h.requests[1].resolve({ships:[ship('msc','MSC Match')],hasMore:false});await h.tick();
 h.press('Cruise line: MSC Cruises');h.press('MSC Cruises');await h.tick();assert.equal(h.requests.length,2);assert(h.text().includes('MSC Match'));assert(h.dismissals>=4);
 h.press('River');h.press('Announced ships');h.type('Search ship or cruise line','A source name');await h.tick();const args=h.requests.at(-1).args;assert.deepEqual([args.operatorId,args.kind,args.status,args.query,args.offset],['msc-cruises','river','announced','A source name',0]);assert(!h.text().includes('MSC Match'));
});
test('Featured follows current company and stale responses cannot restore old ships; a query suppresses Featured',async()=>{
 const h=harness();await h.tick();h.facets[0].resolve(operators);await h.tick();h.press('Cruise line: All cruise lines');h.press('MSC Cruises');await h.tick();assert.equal(h.featured[1].args.operatorId,'msc-cruises');h.featured[1].resolve([ship('msc','Current MSC Featured')]);await h.tick();assert(h.text().includes('Current MSC Featured'));h.featured[0].resolve([ship('old','Stale Other Featured')]);await h.tick();assert(!h.text().includes('Stale Other Featured'));
 h.type('Search ship or cruise line','Wonder');await h.tick();assert.equal(h.featured[2].args.query,'Wonder');h.featured[2].resolve([ship('unexpected','Unexpected query Featured')]);await h.tick();assert(!h.text().includes('Featured ships'));assert(!h.text().includes('Unexpected query Featured'));assert(!h.text().includes('Current MSC Featured'));
});
test('facet failures stay separate, retry rejects stale facet results, and retrying a loaded page does not duplicate it',async()=>{
 const h=harness();await h.tick();h.requests[0].resolve({ships:[ship('one','Ship One')],hasMore:true});h.facets[0].reject(Error('Facet failure'));await h.tick();assert(h.text().includes('Cruise lines are temporarily unavailable.'));assert(h.text().includes('Ship One'));h.press('Try again');await h.tick();const staleFacet=h.facets[1];h.requests[1].resolve({ships:[ship('one','Ship One')],hasMore:true});await h.tick();h.press('Load more ships');await h.tick();h.requests[2].resolve({ships:[ship('two','Ship Two')],hasMore:false});h.featured[1].reject(Error('Featured failure'));await h.tick();assert(h.text().includes('Featured ships are temporarily unavailable.'));h.press('Try again');await h.tick();assert.equal(h.requests[3].args.offset,1);h.requests[3].resolve({ships:[ship('two','Ship Two')],hasMore:false});h.facets[2].resolve([operators[0]]);await h.tick();staleFacet.resolve([operators[1]]);await h.tick();h.press('Cruise line: All cruise lines');assert(h.text().includes('MSC Cruises'));assert(!h.text().includes('Royal Caribbean International'));assert.equal(h.all().filter(x=>x.type==='TouchableOpacity'&&h.text(x).includes('Ship Two')).length,1);
});
