const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
function harness(){
 const slots=[],effects=[],timers=new Map(),requests=[],facets=[],featured=[],navigations=[];let cursor=0,nextTimer=0,dirty=true,tree,dismissals=0;
 const react={Fragment:'Fragment',createElement:(type,props,...children)=>({type,props:{...props,children}}),useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>{const value=typeof v==='function'?v(slots[i]):v;if(value!==slots[i]){slots[i]=value;dirty=true}}]},useRef(initial){const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i]},useEffect(fn,deps){const i=cursor++;const old=slots[i];if(!old||deps.some((v,j)=>v!==old.deps[j])){old?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=fn()})}}};
 const directoryState={};new Function('exports',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../lib/cruises/directoryState.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(directoryState);
 const deferred=(list,args)=>new Promise((resolve,reject)=>list.push({args,resolve,reject}));
 const brands={};new Function('exports',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../lib/cruises/lineBrands.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(brands);
 const exports={};const dependencies={'../ToolHeader':{default:'ToolHeader'},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:0,bottom:0,left:0,right:0})},'../../lib/cruises/lineBrands':brands,'../../lib/cruises/lineLogoAssets':{CRUISE_LINE_LOGOS:{}},react:{...react,default:react},'react-native':new Proxy({StyleSheet:{create:x=>x},Platform:{OS:'ios'},findNodeHandle:()=>null,AccessibilityInfo:{setAccessibilityFocus(){}},Keyboard:{dismiss:()=>{dismissals++}}},{get:(o,k)=>o[k]||k}),'@react-navigation/native':{useNavigation:()=>({navigate:(...args)=>navigations.push(args)})},'@expo/vector-icons':{Ionicons:'Icon'},'../../contexts/ThemeContext':{useThemeContext:()=>({theme:{}})},'../../lib/cruises/catalog':{visibleCruisePhoto:()=>null},'../../lib/cruises/directoryState':directoryState,'../../lib/cruises/service':{searchCruiseShips:args=>deferred(requests,args),getCruiseOperators:()=>deferred(facets),getFeaturedCruiseShips:args=>deferred(featured,args)}};
 const code=ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../components/cruises/CruiseDirectory.tsx'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2022}}).outputText;
 new Function('require','exports','setTimeout','clearTimeout',code)(name=>{assert(name in dependencies,name);return dependencies[name]},exports,(fn)=>{const id=++nextTimer;timers.set(id,fn);return id},id=>timers.delete(id));
 const render=()=>{for(let i=0;dirty&&i<15;i++){dirty=false;cursor=0;tree=exports.default({onBack:()=>navigations.push(['back'])});effects.splice(0).forEach(fn=>fn())}return tree};
 function all(node=tree){return !node||typeof node!=='object'?[]:[node,...(node.props?.children||[]).flat(Infinity).flatMap(all)]}
 const text=(node=tree)=>typeof node==='string'?node:node&&typeof node==='object'?(node.props?.children||[]).flat(Infinity).map(text).join(''):'';
 const press=label=>{const node=all().filter(x=>!all().some(y=>y.type==='Modal')||all(all().find(y=>y.type==='Modal')).includes(x)).find(x=>x.type==='TouchableOpacity'&&(text(x)===label||x.props?.accessibilityLabel===label));assert(node,'button '+label);node.props.onPress();render()};
 const type=(label,value)=>{const node=all().find(x=>x.type==='TextInput'&&x.props.accessibilityLabel===label);assert(node,'input '+label);node.props.onChangeText(value);render()};
 const tick=async()=>{render();const pending=[...timers.values()];timers.clear();pending.forEach(fn=>fn());await new Promise(r=>setImmediate(r));render()};
 render();return {requests,facets,featured,navigations,press,type,tick,text,all,render,get dismissals(){return dismissals}};
}
const ship=(id,name)=>({ship:{id,universe_id:'universe-'+id,slug:id,name,operator_name:'Fixture line',kind:'ocean',operating_status:'operating',photo:null}});
test('draft controls are atomic, same selection is a no-op, pagination and canonical navigation survive',async()=>{
 const h=harness();await h.tick();h.requests[0].resolve({ships:[ship('one','Ship One')],hasMore:true});await h.tick();
 h.press('Filters');h.press('All types');h.press('Operating ships');await h.tick();assert.equal(h.requests.length,1);h.press('Apply filters');await h.tick();assert.equal(h.requests.length,1);assert.match(h.text(),/Ship One/);
 const card=h.all().find(x=>x.type==='TouchableOpacity'&&h.text(x).includes('Ship One'));card.props.onPress();assert.deepEqual(h.navigations[0],['UniverseLanding',{universeId:'universe-one'}]);assert(h.all().some(x=>x.props?.accessibilityLabel==='No ship photo'));
 h.press('Load more ships');await h.tick();assert.equal(h.requests[1].args.offset,1);h.press('Filters');h.press('River');await h.tick();assert.equal(h.requests.length,2);h.press('Apply filters');await h.tick();assert.equal(h.requests[2].args.kind,'river');assert.equal(h.requests[2].args.offset,0);h.requests[2].resolve({ships:[ship('river','River Fixture')],hasMore:false});await h.tick();h.requests[1].resolve({ships:[ship('old','Stale Old Ship')],hasMore:false});await h.tick();assert.match(h.text(),/River Fixture/);assert(!h.text().includes('Stale Old Ship'));
});
test('cancel discards draft; failed reads show retry and announced selection stays separate',async()=>{
 const h=harness();await h.tick();h.requests[0].reject(Error('Ships unavailable'));await h.tick();assert.match(h.text(),/Ships unavailable/);assert(!h.text().includes('No verified ships match these filters.'));h.press('Try again');await h.tick();h.requests[1].resolve({ships:[],hasMore:false});await h.tick();assert.match(h.text(),/No verified ships match these filters./);h.press('Filters');h.press('Announced ships');h.press('Close filters');await h.tick();assert.equal(h.requests.length,2);h.press('Filters');h.press('Apply filters');await h.tick();assert.equal(h.requests.length,2);h.press('Filters');h.press('Announced ships');h.press('Apply filters');await h.tick();assert.equal(h.requests[2].args.status,'announced');
});
const operators=Array.from({length:26},(_,i)=>({id:'line-'+i,name:'Fixture Line '+i}));
test('all26 lines remain accessible, searchable panel composes all filters and chips remove only one',async()=>{
 const h=harness();await h.tick();h.facets[0].resolve(operators);h.requests[0].resolve({ships:[],hasMore:false});await h.tick();assert.equal(h.all().filter(x=>x.type==='TouchableOpacity'&&x.props?.accessibilityLabel?.startsWith('Fixture Line')).length,26);
 h.press('Fixture Line 25');await h.tick();assert.equal(h.requests[1].args.operatorId,'line-25');h.press('Fixture Line 25');await h.tick();assert.equal(h.requests.length,2);
 h.type('Search ship or cruise line','A source name');await h.tick();h.press('Filters, 1 active');h.type('Search cruise lines','Line 24');h.press('Fixture Line 24');h.press('River');h.press('Announced ships');await h.tick();assert.equal(h.requests.length,3);h.press('Apply filters');await h.tick();const args=h.requests.at(-1).args;assert.deepEqual([args.operatorId,args.kind,args.status,args.query,args.offset],['line-24','river','announced','A source name',0]);
 h.press('Remove River filter');await h.tick();assert.deepEqual([h.requests.at(-1).args.kind,h.requests.at(-1).args.operatorId,h.requests.at(-1).args.status],[undefined,'line-24','announced']);h.press('Clear all');await h.tick();assert.deepEqual([h.requests.at(-1).args.query,h.requests.at(-1).args.operatorId,h.requests.at(-1).args.status],['','','operating']);
});
test('Featured follows line scope; stale results cannot restore old ships and search suppresses Featured',async()=>{
 const h=harness();await h.tick();h.facets[0].resolve(operators);await h.tick();h.press('Fixture Line 25');await h.tick();assert.equal(h.featured[1].args.operatorId,'line-25');h.featured[1].resolve([ship('current','Current Featured')]);await h.tick();assert(h.text().includes('Current Featured'));h.featured[0].resolve([ship('old','Stale Other Featured')]);await h.tick();assert(!h.text().includes('Stale Other Featured'));
 h.type('Search ship or cruise line','Wonder');await h.tick();assert.equal(h.featured[2].args.query,'Wonder');h.featured[2].resolve([ship('unexpected','Unexpected query Featured')]);await h.tick();assert(!h.text().includes('Featured ships'));assert(!h.text().includes('Unexpected query Featured'));
});
test('Reset filters keeps search, and operator failure leaves ship results intact',async()=>{
 const h=harness();await h.tick();h.requests[0].resolve({ships:[ship('one','Ship One')],hasMore:false});h.facets[0].reject(Error('Facet failure'));await h.tick();assert(h.text().includes('Cruise lines are temporarily unavailable.'));assert(h.text().includes('Ship One'));
 h.type('Search ship or cruise line','Ship');await h.tick();h.press('Filters');h.press('Expedition');h.press('Announced ships');h.press('Reset filters');h.press('Apply filters');await h.tick();assert.equal(h.requests.length,2);assert.equal(h.requests.at(-1).args.query,'Ship');assert.equal(h.requests.at(-1).args.status,'operating');
});
