const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function fixture(pro=false){let cursor=0;const slots=[],cache={};const react={createElement:(type,props,...children)=>({type,props:props||{},children:children.flat(Infinity)}),useState:init=>{const i=cursor++;if(!(i in slots))slots[i]=typeof init==='function'?init():init;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v]},useRef:init=>{const i=cursor++;if(!(i in slots))slots[i]={current:init};return slots[i]}};
const real=file=>{file=path.resolve(file);if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:1,target:7}}).outputText)(id=>real(path.resolve(path.dirname(file),id+'.ts')),m,m.exports);return m.exports;};const transition={duration(){return this},springify(){return this}};
const exports={};new Function('require','exports',ts.transpileModule(fs.readFileSync(path.join(root,'screens/ecard/ECardNewScreen.tsx'),'utf8'),{compilerOptions:{module:1,jsx:2,target:7}}).outputText)(id=>{
 if(id==='react')return{...react,default:react};if(id==='react-native')return{View:'View',Text:'Text',TouchableOpacity:'Button',Alert:{alert:()=>{}},StyleSheet:{create:s=>s}};
 if(id==='react-native-safe-area-context')return{SafeAreaView:'Safe'};if(id==='@react-navigation/native')return{useNavigation:()=>({navigate(){},goBack(){}}),useRoute:()=>({params:{}})};
 if(id==='@expo/vector-icons')return{Ionicons:'Icon'};if(id==='react-native-reanimated')return{default:{View:'Animated'},FadeIn:transition,SlideInRight:transition,SlideInLeft:transition,SlideOutLeft:transition,SlideOutRight:transition};
 if(id==='expo-haptics')return{impactAsync:()=>Promise.resolve(),ImpactFeedbackStyle:{Light:'light'}};if(id==='expo-file-system')return{};if(id==='base64-arraybuffer')return{decode:()=>{throw Error('unexpected upload')}};
 if(id.includes('AuthContext'))return{useAuth:()=>({user:{id:'fixture'}})};if(id.includes('ThemeContext'))return{useThemeContext:()=>({isDark:false})};if(id.includes('useECardEntitlement'))return{useECardEntitlement:()=>({isPro:pro,loading:false,error:null,refresh(){}})};
 if(id.includes('eCardTemplates'))return real(path.join(root,'config/eCardTemplates.ts'));if(id.includes('templateSelection'))return real(path.join(root,'lib/ecard/templateSelection.ts'));if(id.includes('creationDraft'))return real(path.join(root,'lib/ecard/creationDraft.ts'));if(id.includes('supabaseClient'))return{supabase:{from:()=>{throw Error('No writes expected')}}};if(id.includes('useReleaseCopy'))return{useReleaseCopy:()=>s=>s};
 if(id.includes('FocusedStatusBar'))return{default:'StatusBar'};for(const n of ['TypePicker','TemplateGallery','TemplateBrowseFilters','QuickSetup'])if(id.endsWith('/'+n))return{default:n};throw Error(id);
 },exports);
 const nodes=t=>{const out=[];function walk(n){if(n&&typeof n==='object'){out.push(n);n.children?.forEach(walk)}}walk(t);return out};const render=()=>{cursor=0;return exports.default()};return{render,nodes,templates:real(path.join(root,'config/eCardTemplates.ts')).TEMPLATES,find:(tree,type)=>nodes(tree).find(n=>n.type===type)};
}
test('native starts business category and explicit locked country design clears stale selection',()=>{const f=fixture();let t=f.render();assert.equal(f.find(t,'TemplateBrowseFilters').props.category,'business-services');const typeButton=f.nodes(t).find(n=>n.type==='Button'&&f.nodes(n).some(v=>v.children?.includes('Choose card type & template')));typeButton.props.onPress();t=f.render();f.find(t,'TypePicker').props.onSelect('politician','BR','civic-card-flag');t=f.render();const g=f.find(t,'TemplateGallery');assert.equal(g.props.cardType,'politics-public-service');assert.equal(g.props.selectedTemplateId,null);assert.equal(g.props.countryTemplate,'civic-card-flag')});
test('native Free political filter selects approved civic design, not old business choice',()=>{const f=fixture();let t=f.render();f.find(t,'TemplateBrowseFilters').props.onChange('politics-public-service','free');t=f.render();const g=f.find(t,'TemplateGallery');assert.equal(g.props.planFilter,'free');assert.equal(g.props.selectedTemplateId,'politician-generic');assert.equal(g.props.selectedColorSchemeId,'classic-blue')});
test('native switching categories preserves entered name/title/photo and custom draft identity',()=>{const f=fixture();let t=f.render();f.nodes(t).find(n=>n.type==='Button'&&f.nodes(n).some(v=>v.children?.includes('Quick setup'))).props.onPress();t=f.render();const q=f.find(t,'QuickSetup');q.props.onChange({name:'User supplied',title:'Saved title',photoUri:'file:///qa-photo.png',primaryColor:'#123456'});t=f.render();const back=f.nodes(t).find(n=>n.type==='Button'&&f.nodes(n).some(v=>v.children?.includes('Change design or color')));assert.ok(back);back.props.onPress();t=f.render();f.find(t,'TemplateBrowseFilters').props.onChange('food-mobile','all');t=f.render();f.find(t,'TemplateGallery').props.onAvailabilityChange(true);t=f.render();f.nodes(t).find(n=>n.type==='Button'&&f.nodes(n).some(v=>v.children?.includes('Use this template'))).props.onPress();t=f.render();const values=f.find(t,'QuickSetup').props.value;assert.equal(values.name,'User supplied');assert.equal(values.title,'Saved title');assert.equal(values.photoUri,'file:///qa-photo.png')});

function button(f,t,label){return f.nodes(t).find(n=>n.type==='Button'&&f.nodes(n).some(v=>v.children?.includes(label)))}
function setup(f,t){f.find(t,'TemplateGallery').props.onAvailabilityChange(true);t=f.render();button(f,t,'Use this template').props.onPress();return f.render()}
function purpose(f,t,label){return button(f,t,label).props.accessibilityState.selected}
test('Cover in Personal & Creators sets Personal; explicit Business choice survives color-only changes',()=>{const f=fixture(true);let t=f.render();f.find(t,'TemplateBrowseFilters').props.onChange('personal-creators','all');t=f.render();const template=f.templates.find(x=>x.id==='cover-card');f.find(t,'TemplateGallery').props.onSelect(template.id,template.colorSchemes[0].id);t=setup(f,f.render());assert.equal(purpose(f,t,'Personal'),true);button(f,t,'Business').props.onPress();t=f.render();button(f,t,'Change design or color').props.onPress();t=f.render();f.find(t,'TemplateGallery').props.onSelect(template.id,template.colorSchemes[1].id);t=setup(f,f.render());assert.equal(purpose(f,t,'Business'),true)});
test('Spotlight in Food & Mobile Businesses sets Business purpose',()=>{const f=fixture(true);let t=f.render();f.find(t,'TemplateBrowseFilters').props.onChange('food-mobile','all');t=f.render();assert.equal(f.find(t,'TemplateGallery').props.selectedTemplateId,'full-width');t=setup(f,t);assert.equal(purpose(f,t,'Business'),true)});
test('Quick setup Business remains Business on basic palette change and return',()=>{const f=fixture();let t=f.render();button(f,t,'Quick setup').props.onPress();t=f.render();assert.equal(purpose(f,t,'Business'),true);button(f,t,'Change design or color').props.onPress();t=f.render();const template=f.templates.find(x=>x.id==='basic');f.find(t,'TemplateGallery').props.onSelect(template.id,template.colorSchemes[1].id);t=setup(f,f.render());assert.equal(purpose(f,t,'Business'),true)});
