const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const ROOT=path.resolve(__dirname,'../..'),cache=new Map();
function load(file){if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);const code=ts.transpileModule(fs.readFileSync(path.join(ROOT,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('require','exports',code)(id=>{if(!id.startsWith('.'))throw Error('Unexpected helper dependency');return load(path.normalize(path.join(path.dirname(file),id))+'.ts');},exports);return exports;}
const catalog=load('config/eCardTemplates.ts'),selection=load('lib/ecard/templateSelection.ts'),draft=load('lib/ecard/creationDraft.ts');
const free=catalog.TEMPLATES.find(t=>!t.isPremium&&t.colorSchemes.some(s=>s.isFree));
const premium=catalog.TEMPLATES.find(t=>t.isPremium),scheme=free.colorSchemes.find(s=>s.isFree);
const values={name:'  My own name  ',title:' My own title ',photoUri:'file://my-photo.jpg',primaryColor:scheme.primary};
const input={userId:'fixture-owner',slug:'fixture-only',templateId:free.id,schemeId:scheme.id,cardType:'business',values,isPro:false};
test('all21 layouts and123 unique per-layout palette IDs remain browsable',()=>{assert.equal(catalog.TEMPLATES.length,21);assert.equal(catalog.TEMPLATES.reduce((n,t)=>n+t.colorSchemes.length,0),123);for(const t of catalog.TEMPLATES)assert.equal(new Set(t.colorSchemes.map(s=>s.id)).size,t.colorSchemes.length);});
test('exact catalog selection rejects unknown IDs and scheme membership falls back safely',()=>{assert.equal(selection.readTemplateSelection('missing','missing'),null);assert.equal(selection.readTemplateSelection([free.id],scheme.id),null);assert.equal(selection.readTemplateSelection(free.id,'foreign').scheme.id,free.colorSchemes[0].id);assert.equal(selection.canUseTemplate(free,'foreign',true),false);});
test('Free rejects premium layouts AND paid palettes at draft persistence',()=>{assert.throws(()=>draft.createCardDraftPayload({...input,templateId:premium.id,schemeId:premium.colorSchemes[0].id}),/Pro/);const t=catalog.TEMPLATES.find(t=>!t.isPremium&&t.colorSchemes.some(s=>!s.isFree));assert.throws(()=>draft.createCardDraftPayload({...input,templateId:t.id,schemeId:t.colorSchemes.find(s=>!s.isFree).id}),/Pro/);});
test('draft whitelist never copies fictional example identity, media or links',()=>{for(const t of catalog.TEMPLATES){const result=draft.createCardDraftPayload({...input,templateId:t.id,schemeId:t.colorSchemes[0].id,isPro:true,values:{...values,primaryColor:t.colorSchemes[0].primary}});assert.equal(result.full_name,'My own name');assert.equal(result.title,'My own title');assert.equal(result.is_published,false);for(const key of ['bio','company','phone','email','social_instagram','profile_photo_url','gallery_images','links','office_running_for','ballot_number'])assert.equal(result[key],undefined);if(result.banner_image_url)assert.equal(result.banner_image_url,t.id==='civic-card-flag'?'https://tavvy.com/images/brazil-flag-vertical.jpg':'https://tavvy.com/images/ecard-examples/soft-folds.svg');}});
test('switching designs preserves entered name,title,photo; colors keep scheme secondary unless customized',()=>{const next=draft.applyDesignColor(values,scheme.primary);assert.equal(next.name,values.name);assert.equal(next.title,values.title);assert.equal(next.photoUri,values.photoUri);const result=draft.createCardDraftPayload({...input,values:next});assert.equal(result.gradient_color_2,scheme.secondary);assert.equal(draft.createCardDraftPayload({...input,values:{...values,primaryColor:'#123456'}}).gradient_color_2,'#123456');});
test('gallery all is not persistable card_type and obsolete country is omitted',()=>{assert.throws(()=>draft.createCardDraftPayload({...input,cardType:'all'}),/card type/);assert.equal(draft.createCardDraftPayload({...input,countryCode:'BR'}).country_code,undefined);assert.equal(draft.createCardDraftPayload({...input,cardType:'politician',countryCode:'BR'}).country_code,'BR');});
function harness(file,{pro=false,params,props={}}={}){
 let index=0,slots=[],tree,effects=[];const inserts=[],navigations=[],alerts=[];
 const React={createElement:(type,props,...children)=>({type,props:{...props,children}}),useState:value=>{const i=index++;if(!(i in slots))slots[i]=typeof value==='function'?value():value;return[slots[i],next=>{slots[i]=typeof next==='function'?next(slots[i]):next;}];},useRef:value=>{const i=index++;if(!(i in slots))slots[i]={current:value};return slots[i];},useMemo:fn=>fn(),useCallback:fn=>fn,useEffect:fn=>effects.push(fn)};
 const native={StyleSheet:{create:x=>x,absoluteFillObject:{}},Platform:{OS:'ios'},useWindowDimensions:()=>({width:390,height:844}),Alert:{alert:(...args)=>alerts.push(args)}};
 for(const n of ['View','Text','TouchableOpacity','FlatList','ScrollView','Modal','ActivityIndicator'])native[n]=n;
 const transition={duration:()=>transition};
 const deps={react:{...React,default:React},'react-native':native,'react-native-safe-area-context':{SafeAreaView:'SafeAreaView'},'@react-navigation/native':{useNavigation:()=>({goBack:()=>navigations.push('back'),replace:(...args)=>navigations.push(args)}),useRoute:()=>({params})},'@expo/vector-icons':{Ionicons:'Ionicons'},'expo-linear-gradient':{LinearGradient:'LinearGradient'},'react-native-reanimated':{default:{View:'Animated.View'},FadeIn:transition,FadeOut:transition,SlideInRight:transition,SlideInLeft:transition,SlideOutLeft:transition,SlideOutRight:transition},'expo-haptics':{impactAsync:async()=>{},selectionAsync:async()=>{},notificationAsync:async()=>{},ImpactFeedbackStyle:{Light:1},NotificationFeedbackType:{Success:1}},'expo-file-system':{},'base64-arraybuffer':{},'react-i18next':{useTranslation:()=>({i18n:{language:'en'}})},'react-native-webview':{WebView:'WebView'}};
 const code=ts.transpileModule(fs.readFileSync(path.join(ROOT,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React}}).outputText,exports={};
 new Function('require','exports','setTimeout','clearTimeout',code)(id=>{
  if(id in deps)return deps[id];
  if(id.endsWith('/AuthContext'))return{useAuth:()=>({user:{id:'fixture-owner'}})};
  if(id.endsWith('/ThemeContext'))return{useThemeContext:()=>({isDark:false})};
  if(id.endsWith('/useECardEntitlement'))return{useECardEntitlement:()=>({isPro:pro,loading:false,error:null,refresh:()=>{}})};
  if(id.endsWith('/useReleaseCopy'))return{useReleaseCopy:()=>x=>x};
  if(id.endsWith('/EditorContext'))return{useEditor:()=>({state:{card:{full_name:'Preview fixture'},links:[],pendingUploads:new Map()}})};
  if(id.endsWith('/supabaseClient'))return{supabase:{from:()=>({insert:payload=>{inserts.push(payload);return{select:()=>({single:async()=>({data:{id:'fixture-card'},error:null})})};}})}};
  if(id.endsWith('/TypePicker'))return{default:'TypePicker'};if(id.endsWith('/TemplateGallery'))return{default:'TemplateGallery'};if(id.endsWith('/QuickSetup'))return{default:'QuickSetup'};if(id.endsWith('/StudioPreview'))return{StudioPreviewFrame:'StudioPreviewFrame'};
  if(id.startsWith('.'))return load(path.normalize(path.join(path.dirname(file),id))+'.ts');throw Error('Unexpected component dependency '+id);
 },exports,()=>0,()=>{});
 const nodes=()=>{const result=[];function walk(n){if(!n||typeof n!=='object')return;if(Array.isArray(n))return n.forEach(walk);result.push(n);walk(n.props?.children);}walk(tree);return result;};
 const text=n=>typeof n==='string'?n:Array.isArray(n)?n.map(text).join(''):n?.props?text(n.props.children):'';
 const render=(next=props,component='default')=>{props=next;index=0;effects=[];tree=exports[component](props);effects.forEach(fn=>fn());return tree;};
 render();return{render,nodes,text,inserts,navigations,alerts,get:(type)=>nodes().find(n=>n.type===type),button:label=>nodes().find(n=>n.type==='TouchableOpacity'&&text(n)===label)};
}
test('actual native entry begins with all designs, and Quick setup remains available',()=>{const h=harness('screens/ecard/ECardNewScreen.tsx');assert.equal(h.get('TemplateGallery').props.cardType,'all');assert.equal(h.get('QuickSetup'),undefined);h.button('Quick setup').props.onPress();h.render();assert.equal(h.get('QuickSetup').props.templateId,'basic');});
test('actual wizard preserves entered identity/photo through design and full country/type paths',()=>{const h=harness('screens/ecard/ECardNewScreen.tsx');h.button('Quick setup').props.onPress();h.render();h.get('QuickSetup').props.onChange(values);h.render();h.button('Change design or color').props.onPress();h.render();h.get('TemplateGallery').props.onSelect(free.id,scheme.id);h.render();h.button('Use this template').props.onPress();h.render();assert.deepEqual(h.get('QuickSetup').props.value,values);h.button('Card type & country').props.onPress();h.render();h.get('TypePicker').props.onSelect('politician','BR','civic-card');h.render();assert.equal(h.get('TemplateGallery').props.cardType,'politician');assert.equal(h.get('TemplateGallery').props.countryTemplate,'civic-card');});
test('locked route preset is shown once and cannot continue or silently switch',()=>{const h=harness('screens/ecard/ECardNewScreen.tsx',{params:{template:premium.id,scheme:premium.colorSchemes[0].id}});assert.equal(h.get('TemplateGallery').props.selectedTemplateId,premium.id);assert.equal(h.button('Use this template').props.disabled,true);h.button('Use this template').props.onPress();h.render();assert.equal(h.get('QuickSetup'),undefined);assert.equal(h.get('TemplateGallery').props.selectedTemplateId,premium.id);});
test('actual draft creation persists selected design with user identity only',async()=>{const h=harness('screens/ecard/ECardNewScreen.tsx');h.button('Quick setup').props.onPress();h.render();await h.get('QuickSetup').props.onCreateCard({...values,photoUri:undefined});assert.equal(h.inserts.length,1);assert.equal(h.inserts[0].template_id,'basic');assert.equal(h.inserts[0].full_name,'My own name');assert.equal(h.inserts[0].card_type,'business');assert.equal(h.inserts[0].is_published,false);assert.equal(h.inserts[0].bio,undefined);assert.deepEqual(h.navigations,[['ECardEdit',{cardId:'fixture-card'}]]);});
test('gallery settles locked design visibly but availability cannot use a previous free choice',()=>{const changes=[],availability=[];const props={cardType:'all',selectedTemplateId:free.id,selectedColorSchemeId:scheme.id,onSelect:(...x)=>changes.push(x),onAvailabilityChange:x=>availability.push(x),isPro:false,isDark:false};const h=harness('components/ecard/wizard/TemplateGallery.tsx',{props});const list=h.get('FlatList'),index=catalog.TEMPLATES.findIndex(t=>t.id===premium.id),interval=list.props.snapToInterval;list.props.onMomentumScrollEnd({nativeEvent:{contentOffset:{x:index*interval}}});h.render();assert.equal(changes.length,0);assert.equal(availability.at(-1),false);const live=h.get('FlatList').props.renderItem({item:premium,index});assert.equal(live.props.children[0].type,'StudioPreviewFrame');});

test('real preview wrapper keeps its inner viewport9:16 at phone and short-screen sizes',()=>{
 const props={isDark:false,card:{full_name:'Private fixture',template_id:'basic'},links:[],showCaption:false};
 const h=harness('components/ecard/editor/StudioPreview.tsx',{props});
 for(const size of [{width:320,height:420},{width:280,height:240},{width:768,height:900}]){
  h.render(props,'StudioPreviewFrame');h.nodes().find(n=>n.props?.onLayout).props.onLayout({nativeEvent:{layout:size}});h.render(props,'StudioPreviewFrame');
  const screen=h.nodes().find(n=>n.props?.testID==='ecard-preview-screen'),phone=h.nodes().find(n=>n.props?.testID==='ecard-preview-phone');
  const rect=screen.props.style[1],outer=phone.props.style[1];assert.ok(Math.abs(rect.width/rect.height-9/16)<1e-10);assert.ok(outer.width<=size.width);assert.ok(outer.height<=size.height);
  assert.match(h.get('WebView').props.source.uri,/^https:\/\/tavvy\.com\/app\/ecard\/studio-preview$/);
  assert.equal(h.get('WebView').props.scrollEnabled,true);assert.equal(h.get('WebView').props.incognito,true);
 }
});
test('gallery full preview expands the same real renderer instead of a mock template',()=>{
 const props={cardType:'all',selectedTemplateId:free.id,selectedColorSchemeId:scheme.id,onSelect:()=>{},isPro:false,isDark:false};
 const h=harness('components/ecard/wizard/TemplateGallery.tsx',{props});h.button('Open full preview').props.onPress();h.render();assert.equal(h.get('Modal').props.visible,true);assert.equal(h.get('StudioPreviewFrame').props.card.template_id,free.id);assert.equal(h.get('StudioPreviewFrame').props.card.is_published,false);
});

test('Modern Business, Pro Card and Creative use palette backgrounds instead of empty default banners',()=>{for(const id of ['biz-modern','pro-card','pro-creative']){const t=catalog.getTemplateById(id);const result=draft.createCardDraftPayload({...input,templateId:t.id,schemeId:t.colorSchemes[0].id,values:{...values,primaryColor:t.colorSchemes[0].primary},isPro:true});assert.equal(result.banner_image_url,undefined);assert.equal(result.font_style,'default');assert.equal(result.gradient_color_2,t.colorSchemes[0].secondary);}});

test('flag draft keeps customer identity and uses only the approved flag decoration',()=>{const t=catalog.getTemplateById('civic-card-flag');const result=draft.createCardDraftPayload({...input,templateId:t.id,schemeId:t.colorSchemes[0].id,isPro:true});assert.equal(result.full_name,'My own name');assert.equal(result.title,'My own title');assert.equal(result.banner_image_url,'https://tavvy.com/images/brazil-flag-vertical.jpg');assert.equal(result.profile_photo_url,undefined);assert.equal(result.ballot_number,undefined);});
