const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
function load(name){const code=ts.transpileModule(fs.readFileSync(path.join(root,'lib',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:spec=>load(spec.replace('./','')),Error,Promise});return module.exports;}
const {lookupPlaceDetails}=load('placeDetailsLookup');
const uuid='12345678-1234-1234-1234-123456789abc',fsq='4e4c348bbd413c4cc667b40f';
function client(rows,error=false){const calls=[];return{calls,from(table){const filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},async limit(){calls.push({table,filters});return{data:(rows[table]||[]).filter(row=>filters.every(([k,v])=>row[k]===v)),error:error?{}:null}}};return q;}};}
test('prefixed FSQ Boston result loads exact real provider details without writes',async()=>{const db=client({fsq_places_raw:[{fsq_place_id:fsq,name:"D'Amore's",locality:'Boston',region:'MA',address:'1 North St',fsq_category_labels:['Dining > Italian Restaurant'],latitude:42.36,longitude:-71.05}]});const p=await lookupPlaceDetails('fsq:'+fsq,db);assert.equal(p.name,"D'Amore's");assert.equal(p.id,'fsq:'+fsq);assert.equal(p.city,'Boston');assert.equal(p.address_line_1,'1 North St');assert.equal(p.primary_category,'Italian Restaurant');assert.equal(p.cover_image_url,null);assert(db.calls.every(c=>c.table!=='places_unified'));});
test('canonical record wins for provider identity and preserves UUID/content fields',async()=>{const db=client({places:[{id:uuid,source_id:fsq,source_type:'fsq',name:'Real canonical',status:'active',street:'Known address',region:'MA',tavvy_subcategory:'Italian Restaurant',hours:{mon:'9-5'}}]});const p=await lookupPlaceDetails('fsq-'+fsq,db);assert.equal(p.id,uuid);assert.equal(p.address_line_1,'Known address');assert.equal(p.primary_category,'Italian Restaurant');assert(p.hours);assert.equal(db.calls.length,1);});
test('Tavvy UUID prefix and slugs resolve without invalid UUID queries',async()=>{const db=client({places:[{id:uuid,slug:'trattoria',name:'Trattoria',status:'active'}]});assert.equal((await lookupPlaceDetails('tavvy:'+uuid,db)).id,uuid);assert.equal((await lookupPlaceDetails('trattoria',db)).id,uuid);assert.equal(db.calls[1].filters[0][0],'slug');});
test('unknown IDs never create sample places; inactive records stay unavailable',async()=>{assert.equal(await lookupPlaceDetails('1',client({})),null);assert.equal(await lookupPlaceDetails('fsq:'+fsq,client({})),null);assert.equal(await lookupPlaceDetails(uuid,client({places:[{id:uuid,name:'Inactive',status:'inactive'}]})),null);});
test('index fallback must match the requested provider ID',async()=>{const p=await lookupPlaceDetails(fsq,client({}),async id=>({id:'fsq:'+id,fsq_place_id:id,name:'Indexed Boston',locality:'Boston'}));assert.equal(p.name,'Indexed Boston');assert.equal(await lookupPlaceDetails(fsq,client({}),async()=>({id:'different',name:'Wrong place'})),null);});
test('database failures and ambiguous IDs report an error instead of showing unrelated data',async()=>{await assert.rejects(lookupPlaceDetails(uuid,client({},true)),/temporarily unavailable/);await assert.rejects(lookupPlaceDetails(uuid,client({places:[{id:uuid},{id:uuid}]})),/could not be identified/);});
