const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function fixture(file,os='ios'){
 let cursor=0,focused=true;const slots=[],calls=[];
 const react={createElement:(type,props,...children)=>({type,props:props||{},children:children.flat(Infinity)}),useState:initial=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],v=>{slots[i]=typeof v==='function'?v(slots[i]):v}]},useRef:initial=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i]},useMemo:fn=>fn(),useCallback:fn=>fn,useEffect:()=>{}};
 const template={id:'basic',name:'Link Page',isPremium:false,colorSchemes:[{id:'basic-white',name:'White',primary:'#fff',secondary:'#eee',isFree:true}]};
 const exports={};new Function('require','exports',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText)(id=>{
  if(id==='react')return{...react,default:react};if(id==='react-native')return{...Object.fromEntries(['View','Text','FlatList','TouchableOpacity','ScrollView','Modal','ActivityIndicator'].map(s=>[s,s])),StyleSheet:{create:s=>s,absoluteFillObject:{}},Platform:{OS:os},useWindowDimensions:()=>({width:440,height:956})};
  if(id==='@react-navigation/native')return{useIsFocused:()=>focused};if(id.includes('FocusedStatusBar'))return{default:'FocusedStatusBar',useRestoreFocusedStatusBar:()=>()=>calls.push('restore')};
  if(id==='react-native-safe-area-context')return{SafeAreaProvider:'SafeAreaProvider',SafeAreaView:'SafeAreaView'};if(id==='@expo/vector-icons')return{Ionicons:'Icon'};if(id==='expo-linear-gradient')return{LinearGradient:'Gradient'};if(id==='expo-haptics')return{};
  if(id.includes('eCardTemplates'))return{TEMPLATES:[template]};if(id.includes('templatePreviewData'))return{templatePreviewData:()=>({card:{full_name:'Example only'},links:[]})};if(id.includes('templateSelection'))return{TEMPLATE_CATEGORIES:{},canUseTemplate:()=>true};if(id.includes('useReleaseCopy'))return{useReleaseCopy:()=>s=>s};if(id.endsWith('/StudioPreview'))return{StudioPreviewFrame:'Frame'};
  if(id==='react-native-webview')return{WebView:'WebView'};if(id==='react-i18next')return{useTranslation:()=>({i18n:{language:'en'}})};if(id.includes('EditorContext'))return{useEditor:()=>{throw Error('No editor mutation expected')}};if(id.includes('previewBridge'))return{createECardPreviewMessage:(card,links)=>JSON.stringify({card,links}),ECARD_PREVIEW_READY:'ready'};throw Error(id);
 },exports);
 function render(component,props){cursor=0;return component(props)}
 function nodes(tree){const result=[];function walk(n){if(n&&typeof n==='object'){result.push(n);n.children?.forEach(walk)}}walk(tree);return result}
 const galleryProps={cardType:'all',selectedTemplateId:'basic',selectedColorSchemeId:'basic-white',isPro:false,isDark:true,onSelect:()=>calls.push('unexpected selection')};
 return{...exports,render,nodes,calls,template,galleryProps,setFocused:value=>{focused=value}};
}
function inlineFrame(f,tree){const list=f.nodes(tree).find(n=>n.type==='FlatList');return f.nodes(list.props.renderItem({item:f.template,index:0})).filter(n=>n.type==='Frame').length}
function fullButton(f,tree){return f.nodes(tree).find(n=>n.type==='TouchableOpacity'&&f.nodes(n).some(c=>c.type==='Text'&&c.children.includes('Open full preview')))}
test('iOS chooser suspends inline renderer and remounts only after actual modal dismissal',()=>{
 const f=fixture('components/ecard/wizard/TemplateGallery.tsx');let tree=f.render(f.default,f.galleryProps);assert.equal(inlineFrame(f,tree),1);fullButton(f,tree).props.onPress();tree=f.render(f.default,f.galleryProps);assert.equal(inlineFrame(f,tree),0);let modal=f.nodes(tree).find(n=>n.type==='Modal');assert.equal(modal.props.visible,true);modal.props.onRequestClose();tree=f.render(f.default,f.galleryProps);assert.equal(inlineFrame(f,tree),0);modal=f.nodes(tree).find(n=>n.type==='Modal');assert.equal(modal.props.visible,false);modal.props.onDismiss();tree=f.render(f.default,f.galleryProps);assert.equal(inlineFrame(f,tree),1);assert.deepEqual(f.calls,['restore']);
});
test('Android restores inline renderer on close without relying on iOS onDismiss',()=>{
 const f=fixture('components/ecard/wizard/TemplateGallery.tsx','android');let tree=f.render(f.default,f.galleryProps);fullButton(f,tree).props.onPress();tree=f.render(f.default,f.galleryProps);f.nodes(tree).find(n=>n.type==='Modal').props.onRequestClose();tree=f.render(f.default,f.galleryProps);assert.equal(inlineFrame(f,tree),1);assert.deepEqual(f.calls,[]);
});
test('retained unfocused editor owns no WebView and recovers on return with its payload intact',()=>{
 const f=fixture('components/ecard/editor/StudioPreview.tsx'),props={isDark:false,card:{full_name:'Unchanged draft',title:'Unsaved title'},links:[]};const before=JSON.stringify(props);let tree=f.render(f.StudioPreviewFrame,props);assert.equal(f.nodes(tree).filter(n=>n.type==='WebView').length,1);f.setFocused(false);tree=f.render(f.StudioPreviewFrame,props);assert.equal(f.nodes(tree).filter(n=>n.type==='WebView').length,0);f.setFocused(true);tree=f.render(f.StudioPreviewFrame,props);assert.equal(f.nodes(tree).filter(n=>n.type==='WebView').length,1);assert.equal(JSON.stringify(props),before);
});
for(const event of ['onContentProcessDidTerminate','onRenderProcessGone'])test(event+' exposes Retry preview and preserves draft content',()=>{
 const f=fixture('components/ecard/editor/StudioPreview.tsx'),props={isDark:true,card:{full_name:'Unchanged draft'},links:[]};let tree=f.render(f.StudioPreviewFrame,props),web=f.nodes(tree).find(n=>n.type==='WebView');web.props.onMessage({nativeEvent:{url:'https://tavvy.com/app/ecard/studio-preview',data:'ready'}});tree=f.render(f.StudioPreviewFrame,props);web=f.nodes(tree).find(n=>n.type==='WebView');assert.equal(web.props.style.opacity,1);web.props[event]();tree=f.render(f.StudioPreviewFrame,props);const retry=f.nodes(tree).find(n=>n.type==='TouchableOpacity'&&f.nodes(n).some(c=>c.children?.includes('Retry preview')));assert.ok(retry);retry.props.onPress();tree=f.render(f.StudioPreviewFrame,props);assert.notEqual(f.nodes(tree).find(n=>n.type==='WebView').props.key,web.props.key);assert.equal(props.card.full_name,'Unchanged draft');
});
