const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function render(){const calls=[],exports={};const react={createElement:(type,props,...children)=>({type,props:props||{},children:children.flat(Infinity)}),useEffect:()=>{},useState:v=>[v,()=>{}]};const code=ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../../screens/ProfileScreen.tsx'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;
 new Function('require','exports',code)(id=>{
  if(id==='react')return{...react,default:react};if(id==='expo-constants')return{default:{expoConfig:{version:'9.8.7'}}};
  if(id==='react-native')return{...Object.fromEntries(['View','Text','TouchableOpacity','ScrollView','Image','ActivityIndicator'].map(x=>[x,x])),StyleSheet:{create:s=>s},Dimensions:{get:()=>({width:440})}};
  if(id==='expo-linear-gradient')return{LinearGradient:'Gradient'};if(id==='@expo/vector-icons')return{Ionicons:'Icon'};
  if(id.includes('useReleaseCopy'))return{useReleaseCopy:()=>s=>s};if(id.includes('ThemeContext'))return{useThemeContext:()=>({theme:{},isDark:false})};if(id.includes('AuthContext'))return{useAuth:()=>({user:{id:'fixture',user_metadata:{}},signOut:()=>{throw Error('Unexpected write')}})};
  if(id.includes('useProfile'))return{useProfile:()=>({profile:{display_name:'Private fixture'},stats:{reviews:7,savedPlaces:3},refresh:()=>{}})};
  if(id==='react-i18next')return{useTranslation:()=>({t:s=>s,i18n:{language:'en'}})};if(id.includes('ScreenErrorBoundary'))return{withScreenErrorBoundary:c=>c};if(id.includes('AppearanceSelector'))return{default:'AppearanceSelector'};if(id.includes('supabaseClient'))return{supabase:new Proxy({},{get(){throw Error('Unexpected data access')}})};throw Error(id);
 },exports);
 const tree=exports.default({navigation:{navigate:(...args)=>calls.push(args)}});const nodes=[];function walk(n){if(n&&typeof n==='object'){nodes.push(n);n.children?.forEach(walk)}}walk(tree);return{tree,nodes,calls};}
test('Saved statistic opens the existing SavedMain screen',()=>{const r=render(),saved=r.nodes.find(n=>n.type==='TouchableOpacity'&&n.props.accessibilityLabel==='Saved');assert.ok(saved);saved.props.onPress();assert.deepEqual(r.calls,[['SavedMain']]);});
test('four statistics without destinations are readable text, not dead buttons',()=>{const r=render(),stats=r.nodes.filter(n=>n.type==='View'&&n.props.accessibilityRole==='text');assert.equal(stats.length,4);assert.ok(stats.some(n=>JSON.stringify(n).includes('Reviews')));assert.ok(stats.some(n=>JSON.stringify(n).includes('Points')));assert.ok(stats.some(n=>JSON.stringify(n).includes('Badges')));assert.ok(stats.some(n=>JSON.stringify(n).includes('Day Streak')));});
test('Profile displays actual Expo metadata version',()=>{const r=render();assert.ok(r.nodes.some(n=>n.type==='Text'&&n.children.includes('9.8.7')));assert.ok(!JSON.stringify(r.tree).includes('2.0.0'));});
