const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.resolve(__dirname,'../..'),actor='aabb0000-0000-4000-8000-000000000001',place='aabb0000-0000-4000-8000-000000000002',review='aabb0000-0000-4000-8000-000000000003';
function load(file,db){const ex={};new Function('require','exports',ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>{if(name==='./supabaseClient')return{supabase:db};if(name==='./reviewPersistence')return{};throw Error(name)},ex);return ex;}
function fixture({error=false,malformed=false,current=actor,count=2,savedError=false}={}){const calls=[];class Q{constructor(table){this.table=table}select(){return this}eq(){return this}in(k,ids){this.ids=ids;return this}then(resolve){calls.push({table:this.table,ids:this.ids});return Promise.resolve(this.table==='profiles'?{data:[{user_id:actor,display_name:'Auth member'}],error:null}:this.table==='user_favorites'?{count:5,error:savedError?{message:'failed'}:null}:{data:[],error:null}).then(resolve)}}const db={auth:{getUser:async()=>({data:{user:{id:current}},error:null})},from:table=>{assert.notEqual(table,'place_reviews','No fallback to unproven legacy author mapping');return new Q(table)},rpc:async(name,args)=>{calls.push({rpc:name,args});return{data:name==='get_my_place_review_count'?count:malformed?{}:[{id:review,user_id:actor,created_at:'2026-01-01',public_note:'A visit'},{id:'aabb0000-0000-4000-8000-000000000004',user_id:null,created_at:'2026-01-01',public_note:'Preserved legacy content'}],error:error?{message:'unavailable'}:null}}};return{db,calls};}
test('recent review reader uses resolved Auth identity and preserves unnamed legacy content',async()=>{const f=fixture(),api=load('lib/reviews.ts',f.db);const rows=await api.fetchRecentReviews(place);assert.equal(rows[0].name,'Auth member');assert.equal(rows[1].name,'Tavvy member');assert.equal(rows[1].text,'Preserved legacy content');assert.deepEqual(f.calls.find(c=>c.table==='profiles').ids,[actor]);assert.deepEqual(f.calls[0],{rpc:'get_place_recent_reviews',args:{p_place_id:place,p_limit:10,p_offset:0}});});
test('failed or malformed feed is unavailable, not empty or a raw-table fallback',async()=>{for(const options of [{error:true},{malformed:true}]){const f=fixture(options);await assert.rejects(load('lib/reviews.ts',f.db).fetchRecentReviews(place),/unavailable/);assert.equal(f.calls.length,1)}});
test('own stats use server Auth actor count and retain saved count',async()=>{const f=fixture();assert.deepEqual(await load('lib/profileService.ts',f.db).getUserStats(actor),{reviews:2,savedPlaces:5});assert.deepEqual(f.calls.find(c=>c.rpc),{rpc:'get_my_place_review_count',args:undefined});});
test('different signed-in account cannot fetch another account through own stats helper',async()=>{const f=fixture({current:'different'});await assert.rejects(load('lib/profileService.ts',f.db).getUserStats(actor),/Sign in/);assert.equal(f.calls.length,0)});
test('failed/malformed review and saved counts are not replaced with false zero',async()=>{for(const options of [{error:true},{count:null},{savedError:true}]){const f=fixture(options);await assert.rejects(load('lib/profileService.ts',f.db).getUserStats(actor),/unavailable/)}});
