/** New deletion-status copy. Existing catalogs remain intact; unsupported locales use English. */
const en = {
  title: 'Delete account',
  unavailable: 'Account deletion cannot be started in this version.',
  unchanged: 'This screen has not sent a deletion request or changed your account or subscriptions.',
  settings: 'Back to Settings',
  signIn: 'Sign in',
  guest: 'Sign in to view your account settings.',
  loading: 'Loading account settings…',
  close: 'Close',
  confirmFirstTitle: 'Delete your account?',
  confirmFirstMessage: 'This permanently deletes your reviews, favorites, saved places, eCards, and any subscriptions. Shared business listings you own are disabled, not deleted, so other people\'s data on them is preserved. This cannot be undone.',
  confirmFirstContinue: 'Continue',
  confirmSecondTitle: 'This is permanent',
  confirmSecondMessage: 'Are you absolutely sure you want to delete your account? You will be signed out immediately.',
  confirmSecondDelete: 'Delete my account',
  cancel: 'Cancel',
  deletingTitle: 'Deleting account…',
  successTitle: 'Account deleted',
  successMessage: 'Your account and personal data have been deleted.',
  failureTitle: 'Could not delete account',
};
type Copy = typeof en;
const translations: Record<string, Copy> = {
  en,
  pt: {
    title: 'Excluir conta',
    unavailable: 'Não é possível iniciar a exclusão da conta nesta versão.',
    unchanged: 'Esta tela não enviou uma solicitação de exclusão nem alterou sua conta ou assinaturas.',
    settings: 'Voltar às Configurações',
    signIn: 'Entrar',
    guest: 'Entre para ver as configurações da sua conta.',
    loading: 'Carregando configurações da conta…',
    close: 'Fechar',
    confirmFirstTitle: 'Excluir sua conta?',
    confirmFirstMessage: 'Isso exclui permanentemente suas avaliações, favoritos, locais salvos, eCards e quaisquer assinaturas. Negócios compartilhados que você possui são desativados, não excluídos, preservando os dados de outras pessoas neles. Isso não pode ser desfeito.',
    confirmFirstContinue: 'Continuar',
    confirmSecondTitle: 'Isso é permanente',
    confirmSecondMessage: 'Tem certeza absoluta de que deseja excluir sua conta? Você será desconectado imediatamente.',
    confirmSecondDelete: 'Excluir minha conta',
    cancel: 'Cancelar',
    deletingTitle: 'Excluindo conta…',
    successTitle: 'Conta excluída',
    successMessage: 'Sua conta e dados pessoais foram excluídos.',
    failureTitle: 'Não foi possível excluir a conta',
  },
  es: {
    title: 'Eliminar cuenta',
    unavailable: 'No se puede iniciar la eliminación de la cuenta en esta versión.',
    unchanged: 'Esta pantalla no ha enviado una solicitud de eliminación ni ha cambiado tu cuenta o suscripciones.',
    settings: 'Volver a Configuración',
    signIn: 'Iniciar sesión',
    guest: 'Inicia sesión para ver la configuración de tu cuenta.',
    loading: 'Cargando configuración de la cuenta…',
    close: 'Cerrar',
    confirmFirstTitle: '¿Eliminar tu cuenta?',
    confirmFirstMessage: 'Esto elimina permanentemente tus reseñas, favoritos, lugares guardados, eCards y cualquier suscripción. Los negocios compartidos que posees se desactivan, no se eliminan, preservando los datos de otras personas en ellos. Esto no se puede deshacer.',
    confirmFirstContinue: 'Continuar',
    confirmSecondTitle: 'Esto es permanente',
    confirmSecondMessage: '¿Estás absolutamente seguro de que deseas eliminar tu cuenta? Se cerrará tu sesión inmediatamente.',
    confirmSecondDelete: 'Eliminar mi cuenta',
    cancel: 'Cancelar',
    deletingTitle: 'Eliminando cuenta…',
    successTitle: 'Cuenta eliminada',
    successMessage: 'Tu cuenta y datos personales han sido eliminados.',
    failureTitle: 'No se pudo eliminar la cuenta',
  },
};
export function accountDeletionCopy(locale?: string): Copy {
  return translations[(locale || 'en').toLowerCase().split(/[-_]/)[0]] || en;
}
