/** Explicit UI copy only. Never apply to user or place content. */
export const RELEASE_COPY_KEYS: Record<string, string> = {
  "Design category": "ecardBrowse1",
  "Design plan": "ecardBrowse2",
  "All plans": "ecardBrowse3",
  "Business & Services": "ecardBrowse4",
  "Personal & Creators": "ecardBrowse5",
  "Food & Mobile Businesses": "ecardBrowse6",
  "Real Estate": "ecardBrowse7",
  "Faith & Community": "ecardBrowse8",
  "Politics & Public Service": "ecardBrowse9",
  "No designs match these filters. Choose All plans or another category.": "ecardBrowse10",
  "Free design. Some colors require Pro.": "ecardBrowse11",
  "Profile Card": "ecardBrowse12",
  "Portrait Page": "ecardBrowse13",

  "Airports": "atlasCategoryAirports",
  "Campuses": "atlasCategoryCampuses",
  "Family & Kids": "atlasCategoryFamilyKids",
  "Food & Drink": "atlasCategoryFoodDrink",
  "Hospitals": "atlasCategoryHospitals",
  "Malls": "atlasCategoryMalls",
  "Ports": "atlasCategoryPorts",
  "Stadiums": "atlasCategoryStadiums",
  "Theme Parks": "atlasCategoryThemeParks",
  "Travel Tips": "atlasCategoryTravelTips",
  "Venues": "atlasCategoryVenues",
  "Cruises": "cruiseToolTitle",
  "Explore ocean, river and expedition ships.": "cruiseToolDescription",
  "Good night": "publicFinishGoodNight",
  "What are you in the mood for?": "publicFinishMoodSearch",
  "Your guide to the exceptional.": "publicFinishAtlasTagline",
  "Search articles...": "publicFinishAtlasSearch",
  "Loading articles...": "publicFinishAtlasLoading",
  "FEATURED STORY": "publicFinishAtlasFeatured",
  "Read Article": "publicFinishAtlasRead",
  "All Articles": "publicFinishAtlasAll",
  "No articles found.": "publicFinishAtlasEmpty",
  "Find your perfect campsite.": "publicFinishRVTagline",
  "Search places or cities": "publicFinishPlacesOrCities",
  "Browse all locations. Search a place or city to narrow the list.": "publicFinishBrowseScope",
  "RV Parks": "publicFinishRVParks",
  "Campgrounds": "publicFinishCampgrounds",
  "National Parks": "publicFinishNationalParks",
  "Beaches": "publicFinishBeaches",
  "Boondocking": "publicFinishBoondocking",
  "Overnight Parking": "publicFinishOvernightParking",
  "Dump Stations": "publicFinishDumpStations",
  "Loading places…": "publicFinishPlacesLoading",
  "Load more places": "publicFinishPlacesMore",
  "Try another place, city or category.": "publicFinishPlacesEmptyHint",
  "Places are temporarily unavailable. Please try again.": "publicFinishPlacesUnavailable",
  "Recent reviews": "publicFinishRecentReviews",
  "The Main Thing": "publicFinishMainThing",
  "The Good": "publicFinishTheGood",
  "The Vibe": "publicFinishTheVibe",
  "Heads Up": "publicFinishHeadsUp",
  "Loading recent reviews…": "publicFinishReviewsLoading",
  "Recent reviews unavailable": "publicFinishReviewsUnavailable",
  "More recent reviews needed": "publicFinishReviewsNeeded",
  "Recent concerns reported": "publicFinishConcernsRecent",
  "No recent concerns reported": "publicFinishNoConcernsRecent",
  "The campsite": "publicFinishCampsite",
  "The beach experience": "publicFinishBeachExperience",
  "The food": "publicFinishFood",
  "One person mentioned this": "publicFinishMentionedOne",
  "{{count}} people mentioned this": "publicFinishMentionedMany",
  "By": "publicFinishByAuthor",

  "Discover": "navDiscover",
  "Tools": "navTools",
  "Saved": "navSaved",
  "Profile": "navProfile",
  "Appearance": "appearance",
  "Use device setting": "deviceTheme",
  "Light": "light",
  "Dark": "dark",
  "Content": "content",
  "Design": "design",
  "More features": "moreFeatures",
  "Save": "save",
  "Saving…": "saving",
  "All changes saved": "savedAll",
  "Unsaved changes": "unsaved",
  "Could not save": "saveFailed",
  "Retry saving": "retrySave",
  "Publish": "publish",
  "Publishing…": "publishing",
  "Published": "published",
  "Draft": "draft",
  "Preview": "preview",
  "Edit": "edit",
  "Share": "share",
  "Close": "close",
  "Keep editing": "keepEditing",
  "View Pro plan": "viewPro",
  "Links & actions": "linksActions",
  "Templates & colors": "templatesColors",
  "Typography & buttons": "typographyButtons",
  "Images & layout": "imagesLayout",
  "Professional details & contact form": "professionalForm",
  "Civic details": "civicDetails",
  "Mobile business": "mobileBusiness",
  "Publication & sharing": "publicationSharing",
  "Media": "media",
  "Gallery": "gallery",
  "Videos": "videos",
  "Contact Form": "contactForm",
  "Add Images": "addImages",
  "Add Video": "addVideo",
  "Where": "where",
  "Apply": "apply",
  "Near me": "nearMe",
  "Search": "search",
  "No tools found": "noTools",
  "Clear search": "clearSearch",
  "Share your card": "shareCard",
  "Share & QR": "shareQR",
  "My cards": "myCards",
  "Card preview": "cardPreview",
  "Back to editing": "backEditing",
  "Open full preview": "openPreview",
  "QR code": "qrCode",
  "Copy link": "copyLink",
  "Cancel": "cancel",
  "Name": "name",
  "Full name": "fullName",
  "Title": "title",
  "Bio": "bio",
  "Phone": "phone",
  "Website": "website",
  "Pro features": "proFeatures",
  "Pro feature": "proFeature",
  "Gallery · Pro": "galleryPro",
  "Videos · Pro": "videosPro",
  "Contact Form · Pro": "formPro",
  "A LITTLE HELP FOR EVERY DAY": "toolsEyebrow",
  "What would you like to do?": "toolsTitle",
  "Find your next stop. Meet the right people. Make yourself at home.": "toolsIntro",
  "Search food, places, people and more": "toolsSearch",
  "A good place to start": "toolsStart",
  "Try a word like food, cards or places.": "toolsEmptyHint",
  "Show all tools": "toolsAll",
  "Find your next stop": "toolsDiscover",
  "Good food, new places and a little adventure.": "toolsDiscoverDescription",
  "People who can help": "toolsConnect",
  "Find local expertise and keep the conversation going.": "toolsConnectDescription",
  "Your everyday essentials": "toolsPersonal",
  "Keep useful things close and make Tavvy yours.": "toolsPersonalDescription",
  "Get more out of Tavvy": "toolsMore",
  "Food Menu": "foodMenu",
  "Universes": "universes",
  "On The Go": "onTheGo",
  "Rides": "rides",
  "RV & Camping": "camping",
  "Cities": "cities",
  "Happening Now": "happening",
  "Experiences": "experiences",
  "Atlas": "atlas",
  "Pros": "pros",
  "Realtors": "realtors",
  "Messages": "messages",
  "eCard": "ecard",
  "Wallet": "wallet",
  "Create": "create",
  "Account": "account",
  "Settings": "settings",
  "Find a dish you’re craving nearby.": "foodMenuDescription",
  "Explore parks, airports and places within them.": "universesDescription",
  "Find food trucks and mobile businesses.": "onTheGoDescription",
  "Plan your next theme park adventure.": "ridesDescription",
  "Find somewhere to park, camp and unwind.": "campingDescription",
  "Get to know a new city.": "citiesDescription",
  "See local events and what’s coming up.": "happeningDescription",
  "Explore a path of places or create your own.": "experiencesDescription",
  "Browse guides and stories about places.": "atlasDescription",
  "Find local professionals for your next project.": "prosDescription",
  "Connect with real estate professionals.": "realtorsDescription",
  "Pick up your conversations.": "messagesDescription",
  "Create a digital card that introduces you.": "ecardDescription",
  "Return to places you want to remember.": "savedDescription",
  "Keep business cards and contacts together.": "walletDescription",
  "Add a place, business or something new.": "createDescription",
  "Manage your profile and personal details.": "accountDescription",
  "Set up Tavvy the way you like it.": "settingsDescription",
  "City, state or any location": "cityPlaceholder",
  "Location access was not available. Enter a city instead.": "locationDenied",
  "Location is unavailable. Enter a city instead.": "locationUnavailable",
  "What matters for this meal?": "mealQuestion",
  "Search places, categories, cities...": "searchPlaceholder",
  "Checking guest reports…": "checkingReviews",
  "Saved changes update your published card.": "publicSaveNote",
  "Your draft is private until you publish.": "privateDraftNote",
  "Updates as you edit. Preview actions do not contact anyone.": "previewNote",
  "Your existing content stays on your card.": "existingPreserved",
  "Gallery photos, embedded videos, contact forms and professional credentials are Pro extras.": "proExtrasSummary",
  "Contact forms are included with Pro. Existing form settings are preserved when you turn the form off.": "formOffNote",
  "Adding gallery photos": "galleryAddPro",
  "Adding embedded videos": "videoAddPro",
  "Enabling a contact form": "formEnablePro",
  "Requires Pro": "proRequired",
  "Show contact form on card": "showForm",
  "Unpublish card": "unpublish",
  "Retry plan check": "retryPlan",
  "Dismiss": "dismiss",
  "Free plan": "freePlan",
  "Pro plan": "proPlan",
  "Back to cards": "backCards",
  "Edit card": "editCard",
  "Save PNG": "savePNG",
  "Share link": "shareLink",
  "Your card is published and ready to share.": "publishedConfirmation",
  "Card link copied.": "linkCopied",
  "Your latest changes have not saved. Retry saving before publishing.": "saveBeforePublish",
  "Choose how Tavvy looks on this device.": "appearanceHelp",
  "Phone preview": "phonePreview",
  "9:16 phone preview": "phonePreviewRatio",
  "Scroll inside to see the full card": "scrollPreview",
  "Loading preview…": "loadingPreview",
  "Retry preview": "retryPreview",
  "The preview could not load. Your changes are still in the editor.": "previewFailed",
  "This preview could not be prepared. Return to Edit to continue.": "previewInvalid",
  "New photos appear here after they finish saving.": "pendingPhotos",
  "Choose your look": "finishChooseYourLook",
  "Quick setup": "finishQuickSetup",
  "Choose a card type": "finishChooseACardType",
  "Close card creation": "finishCloseCardCreation",
  "New eCard": "finishNewECard",
  "Change design or color": "finishChangeDesignOrColor",
  "Use this template": "finishUseThisTemplate",
  "Card type & country": "finishCardTypeCountry",
  "Personal": "finishPersonal",
  "Politician": "finishPolitician",
  "Civic / Public Service": "finishCivicPublicService",
  "Checking your plan…": "finishCheckingYourPlan",
  "Pro design": "finishProDesign",
  "Pro design or color": "finishProDesignOrColor",
  "This design or color requires Pro. Choose an available option or review your plan.": "finishThisDesignOrColorRequiresProChoose",
  "Previous template": "finishPreviousTemplate",
  "Next template": "finishNextTemplate",
  "Swipe to browse templates": "finishSwipeToBrowseTemplates",
  "No templates available for this category": "finishNoTemplatesAvailableForThisCategory",
  "Close preview": "finishClosePreview",
  "Start with your name. Everything else can be added in the editor.": "finishStartWithYourNameEverythingElseCan",
  "Name *": "finishName",
  "Your name or business name": "finishYourNameOrBusinessName",
  "Hide optional setup": "finishHideOptionalSetup",
  "Add title or choose a starting color": "finishAddTitleOrChooseAStartingColor",
  "Title / Role": "finishTitleRole",
  "e.g. CEO, Designer, Agent": "finishEGCEODesignerAgent",
  "Primary Color": "finishPrimaryColor",
  "Create card": "finishCreateCard",
  "Permission needed": "finishPermissionNeeded",
  "Camera permission is required to take a photo.": "finishCameraPermissionIsRequiredToTakeA",
  "Failed to pick image. Please try again.": "finishFailedToPickImagePleaseTryAgain",
  "Your photo could not upload. Your setup is still here; please try again.": "finishYourPhotoCouldNotUploadYourSetup",
  "Could not create card": "finishCouldNotCreateCard",
  "Card was not returned after creation. Please try again.": "finishCardWasNotReturnedAfterCreationPlease",
  "Failed to create card. Please try again.": "finishFailedToCreateCardPleaseTryAgain",
  "Select your country": "finishSelectYourCountry",
  "Choose where the politician operates": "finishChooseWhereThePoliticianOperates",
  "Search country...": "finishSearchCountry",
  "What kind of card?": "finishWhatKindOfCard",
  "Select the type that best fits your needs": "finishSelectTheTypeThatBestFitsYour",
  "For your company, store, or service": "finishForYourCompanyStoreOrService",
  "Your personal brand & link page": "finishYourPersonalBrandLinkPage",
  "For public servants & candidates": "finishForPublicServantsCandidates",
  "Live Business Alerts": "finishLiveBusinessAlerts",
  "Privacy & Security": "finishPrivacySecurity",
  "Share Usage Data": "finishShareUsageData",
  "Preferences": "finishPreferences",
  "Distance Unit": "finishDistanceUnit",
  "Choose your preferred distance unit": "finishChooseYourPreferredDistanceUnit",
  "Miles": "finishMiles",
  "Kilometers": "finishKilometers",
  "Default Map Layer": "finishDefaultMapLayer",
  "Choose your default map style": "finishChooseYourDefaultMapStyle",
  "Brazil": "finishBrazil",
  "United States": "finishUnitedStates",
  "United Kingdom": "finishUnitedKingdom",
  "Canada": "finishCanada",
  "Mexico": "finishMexico",
  "Colombia": "finishColombia",
  "Spain": "finishSpain",
  "France": "finishFrance",
  "Germany": "finishGermany",
  "Australia": "finishAustralia",
  "India": "finishIndia",
  "Nigeria": "finishNigeria",
  "Japan": "finishJapan",
  "This permanently removes your sign-in, private profile, cards, reviews, saved activity, uploaded files, and live location sessions. Shared business and payroll history may remain without an account ownership link. Public place, event, and campground listings remain without your creator link. Stripe subscriptions linked to your account will be canceled; Apple or Google subscriptions must be managed in your store subscription settings.": "finishThisPermanentlyRemovesYourSignInPrivate",
  "Take Photo": "finishTakePhoto",
  "Blocked authors": "accountFinish1",
  "Blocked authors are hidden from your reviews, stories, photos, eCards and community comments. Place summaries still include all eligible public experiences.": "accountFinish2",
  "Sign in to manage content and blocked authors.": "accountFinish3",
  "No blocked authors.": "accountFinish4",
  "Unblock": "accountFinish5",
  "Loading…": "accountFinish6",
  "My eCards": "accountFinish7",
  "Create eCard": "accountFinish8",
  "Search cards...": "accountFinish9",
  "No cards match": "accountFinish10",
  "Edit Card": "accountFinish11",
  "View Stats": "accountFinish12",
  "Copy Link": "accountFinish13",
  "Duplicate": "accountFinish14",
  "Copying": "accountFinish15",
  "Stats": "accountFinish16",
  "Delete": "accountFinish17",
  "Delete Card?": "accountFinish18",
  "Untitled Card": "accountFinish19",
  "Live": "accountFinish20",
  "Create your first eCard": "accountFinish21",
  "Create your first digital card": "accountFinish22",
  "Share your professional identity with a beautiful digital business card": "accountFinish23",
  "Tap here to get started with your digital card": "accountFinish24",
  "Could not load card data.": "accountFinish25",
  "Failed to duplicate card.": "accountFinish26",
  "Failed to delete card.": "accountFinish27",
  "Failed to delete card. Please try again.": "accountFinish28",
  "This will permanently remove": "accountFinish29",
  "and all its data. This cannot be undone.": "accountFinish30",
  "Welcome to Tavvy": "accountFinish31",
  "A savvy way of tapping. Discover and share the vibe of places around you.": "accountFinish32",
  "Explore more Tavvy": "accountFinish33",
  "Explore more": "accountFinish34",
  "Log In": "accountFinish35",
  "Create Account": "accountFinish36",
  "Follow me on": "accountFinish37",
  "Edit Profile": "accountFinish38",
  "Points": "accountFinish39",
  "Badges": "accountFinish40",
  "Day Streak": "accountFinish41",
  "Account Information": "accountFinish42",
  "Member Since": "accountFinish43",
  "Account Type": "accountFinish44",
  "Status": "accountFinish45",
  "Trusted Contributor": "accountFinish46",
  "My Digital Card": "accountFinish47",
  "Help & Support": "accountFinish48",
  "Sign Out": "accountFinish49",
  "Are you sure you want to sign out?": "accountFinish50",
  "Failed to sign out": "accountFinish51",
  "Version": "accountFinish52",
  "Sign in to view your profile": "accountFinish53",
  "Create an account to save places, leave reviews, and more": "accountFinish54",
  "Sign In": "accountFinish55",
  "Don't have an account? Sign Up": "accountFinish56",
  "My Reviews": "accountFinish57",
  "No reviews yet": "accountFinish58",
  "Start exploring and leave your first review!": "accountFinish59",
  "Explore Places": "accountFinish60",
  "No saved places": "accountFinish61",
  "Save places you want to visit later": "accountFinish62",
  "Recently": "accountFinish63",
  "Tavvy Legend": "accountFinish64",
  "Tavvy Master": "accountFinish65",
  "Tavvy Expert": "accountFinish66",
  "Tavvy Explorer": "accountFinish67",
  "Tavvy Starter": "accountFinish68",
  "Newcomer": "accountFinish69",
  "Legend": "accountFinish70",
  "Master": "accountFinish71",
  "Expert": "accountFinish72",
  "Explorer": "accountFinish73",
  "Starter": "accountFinish74",
  "to": "accountFinish75",
  "Loading your card...": "accountFinish76",
  "No Digital Card Yet": "accountFinish77",
  "Create your digital business card to share your contact info instantly with anyone.": "accountFinish78",
  "Create My Card": "accountFinish79",
  "Retry loading card": "accountFinish80",
  "Back to Cards": "accountFinish81",
  "Return to editor": "accountFinish83",
  "Current edits · No actions sent": "accountFinish84",
  "Call": "accountFinish85",
  "Text": "accountFinish86",
  "Web": "accountFinish87",
  "Card": "accountFinish88",
  "Links": "accountFinish89",
  "My Links": "accountFinish90",
  "Share Your Card": "accountFinish91",
  "Card Not Published": "accountFinish92",
  "Your card is saved as a draft. Publish it first to share with others.": "accountFinish93",
  "Go to Dashboard to Publish": "accountFinish94",
  "QR Code": "accountFinish95",
  "Let others scan to view your card": "accountFinish96",
  "Share via...": "accountFinish97",
  "AirDrop, Messages, and more": "accountFinish98",
  "SMS / Text": "accountFinish99",
  "Send via text message": "accountFinish100",
  "Share on WhatsApp": "accountFinish101",
  "Send via email": "accountFinish102",
  "Copy card URL to clipboard": "accountFinish103",
  "Share Contact File": "accountFinish104",
  "Send as .vcf contact card": "accountFinish105",
  "Save to My Contacts": "accountFinish106",
  "Scan to View Card": "accountFinish107"
};

/** Existing translated UI labels, reused without changing their catalogs. */
export const EXISTING_COPY_KEYS: Record<string, string> = {
  "loading...": "common.loading",
  "error": "common.error",
  "success": "common.success",
  "cancel": "common.cancel",
  "confirm": "common.confirm",
  "save": "common.save",
  "delete": "common.delete",
  "edit": "common.edit",
  "done": "common.done",
  "next": "common.next",
  "back": "common.back",
  "close": "common.close",
  "search": "common.search",
  "filter": "common.filter",
  "sort": "common.sort",
  "refresh": "common.refresh",
  "retry": "common.retry",
  "submit": "common.submit",
  "apply": "common.apply",
  "clear": "common.clear",
  "select all": "common.selectAll",
  "deselect all": "common.deselectAll",
  "no data available": "common.noData",
  "no results found": "common.noResults",
  "see more": "common.seeMore",
  "see less": "common.seeLess",
  "view all": "common.viewAll",
  "show more": "common.showMore",
  "show less": "common.showLess",
  "yes": "common.yes",
  "no": "common.no",
  "ok": "common.ok",
  "optional": "common.optional",
  "required": "common.required",
  "home": "navigation.home",
  "explore": "navigation.explore",
  "atlas": "navigation.atlas",
  "universe": "navigation.universe",
  "universes": "navigation.universes",
  "pros": "navigation.pros",
  "apps": "navigation.apps",
  "menu": "navigation.menu",
  "profile": "navigation.profile",
  "settings": "navigation.settings",
  "saved": "navigation.saved",
  "saved places": "navigation.savedPlaces",
  "log in": "auth.login",
  "sign up": "auth.signup",
  "email": "auth.email",
  "password": "auth.password",
  "confirm password": "auth.confirmPassword",
  "forgot password?": "auth.forgotPassword",
  "reset password": "auth.resetPassword",
  "send reset link": "auth.sendResetLink",
  "create account": "auth.createAccount",
  "already have an account?": "auth.alreadyHaveAccount",
  "don't have an account?": "auth.dontHaveAccount",
  "or continue with": "auth.orContinueWith",
  "continue with google": "auth.google",
  "continue with apple": "auth.apple",
  "continue with facebook": "auth.facebook",
  "by continuing, you agree to our": "auth.termsAgree",
  "terms of service": "auth.termsOfService",
  "privacy policy": "auth.privacyPolicy",
  "and": "auth.and",
  "please enter a valid email": "auth.invalidEmail",
  "password must be at least 8 characters": "auth.passwordTooShort",
  "passwords do not match": "auth.passwordsDoNotMatch",
  "login failed. please try again.": "auth.loginFailed",
  "sign up failed. please try again.": "auth.signupFailed",
  "password reset email sent": "auth.resetEmailSent",
  "check your email for reset instructions": "auth.checkYourEmail",
  "welcome back!": "auth.welcomeBack",
  "create your account": "auth.createYourAccount",
  "full name": "auth.fullName",
  "username": "auth.username",
  "good morning": "home.greeting.morning",
  "good afternoon": "home.greeting.afternoon",
  "good evening": "home.greeting.evening",
  "search places, categories...": "home.searchPlaceholder",
  "near you": "home.nearYou",
  "trending near you": "home.trendingNearYou",
  "explore places": "home.explorePlaces",
  "recent check-ins": "home.recentCheckins",
  "quick finds": "home.quickFinds",
  "featured guides": "home.featuredGuides",
  "featured universe": "home.featuredUniverse",
  "all": "home.categories.all",
  "restaurants": "home.categories.restaurants",
  "cafes": "home.categories.cafes",
  "bars": "home.categories.bars",
  "shopping": "home.categories.shopping",
  "rv & camping": "home.categories.rvCamping",
  "hotels": "home.categories.hotels",
  "theme parks": "home.categories.themeparks",
  "rides": "home.categories.rides",
  "cities": "home.categories.cities",
  "standard": "home.mapStyles.standard",
  "satellite": "home.mapStyles.satellite",
  "vector": "home.mapStyles.vector",
  "welcome": "home.welcome",
  "welcome back": "home.welcomeBack",
  "search places...": "home.searchPlaces",
  "near me": "home.nearMe",
  "popular": "home.popular",
  "trending": "home.trending",
  "featured": "home.featured",
  "recommended": "home.recommended",
  "for you": "home.forYou",
  "discover": "home.discover",
  "browse": "home.browse",
  "see all": "home.seeAll",
  "load more": "home.loadMore",
  "pull to refresh": "home.pullToRefresh",
  "no places nearby": "home.noPlacesNearby",
  "try a different search": "home.tryDifferentSearch",
  "adjust your filters": "home.adjustFilters",
  "expand your search area": "home.expandSearch",
  "location access required": "home.locationRequired",
  "enable location to see nearby places": "home.enableLocation",
  "happening now": "home.happeningNow",
  "on the go": "home.onTheGo",
  "recently viewed": "home.recentlyViewed",
  "my places": "home.myPlaces",
  "favorites": "home.favorites",
  "explore tavvy": "home.exploreTavvy",
  "new": "home.featureSlides.rides.tag",
  "rate every ride — thrill, wait, theming": "home.featureSlides.rides.subtitle",
  "real signals, not star ratings": "home.featureSlides.restaurants.subtitle",
  "theme parks, airports & themed worlds": "home.featureSlides.universes.subtitle",
  "stay": "home.featureSlides.hotels.tag",
  "find where to stay by what matters": "home.featureSlides.hotels.subtitle",
  "compare livability, food & culture": "home.featureSlides.cities.subtitle",
  "outdoors": "home.featureSlides.rv-camping.tag",
  "campgrounds, sites & boondocking": "home.featureSlides.rv-camping.subtitle",
  "unique": "home.featureSlides.signals.tag",
  "signal search": "home.featureSlides.signals.title",
  "find places by the vibe you want": "home.featureSlides.signals.subtitle",
  "signals": "home.featureGrid.signals",
  "place details": "places.placeDetails",
  "add place": "places.addPlace",
  "add photo": "places.addPhoto",
  "add photos": "places.addPhotos",
  "add review": "places.addReview",
  "claim business": "places.claimBusiness",
  "claim this business": "places.claimThisBusiness",
  "been here?": "places.beenHere",
  "be the first to tap!": "places.beFirstToTap",
  "be the first to add a photo!": "places.beFirstPhoto",
  "share your experience to help others.": "places.shareExperience",
  "directions": "places.directions",
  "call": "places.call",
  "website": "places.website",
  "photos": "places.photos",
  "reviews": "places.reviews",
  "community signals": "places.communitySignals",
  "community reviews": "places.communityReviews",
  "business hours": "places.businessHours",
  "check with business": "places.checkWithBusiness",
  "see hours": "places.seeHours",
  "save to my places": "places.saveToMyPlaces",
  "report photo": "places.reportPhoto",
  "report review": "places.reportReview",
  "view photos": "places.viewPhotos",
  "try a different search term": "places.tryDifferentSearch",
  "try adjusting your filters or search in a different area": "places.adjustFilters",
  "place": "places.place",
  "places": "places.places",
  "about this place": "places.aboutThisPlace",
  "overview": "places.overview",
  "details": "places.details",
  "info": "places.info",
  "information": "places.information",
  "contact": "places.contact",
  "contact info": "places.contactInfo",
  "address": "places.address",
  "phone": "places.phone",
  "hours": "places.hours",
  "open now": "places.openNow",
  "closed now": "places.closedNow",
  "opening soon": "places.openingSoon",
  "closing soon": "places.closingSoon",
  "open 24 hours": "places.open24Hours",
  "permanently closed": "places.permanentlyClosed",
  "temporarily closed": "places.temporarilyClosed",
  "get directions": "places.getDirections",
  "navigate": "places.navigate",
  "call now": "places.callNow",
  "visit website": "places.visitWebsite",
  "share": "places.share",
  "share place": "places.sharePlace",
  "save place": "places.savePlace",
  "unsave": "places.unsave",
  "report": "places.report",
  "report place": "places.reportPlace",
  "claim": "places.claim",
  "is this your business?": "places.isThisYourBusiness",
  "view all photos": "places.viewAllPhotos",
  "no photos yet": "places.noPhotos",
  "write review": "places.writeReview",
  "view reviews": "places.viewReviews",
  "view all reviews": "places.viewAllReviews",
  "no reviews yet": "places.noReviews",
  "be the first to review!": "places.beFirstToReview",
  "tap signals": "places.tapSignals",
  "the good": "places.theGood",
  "the vibe": "places.theVibe",
  "heads up": "places.headsUp",
  "watch out": "places.watchOut",
  "amenities": "places.amenities",
  "features": "places.features",
  "services": "places.services",
  "view menu": "places.viewMenu",
  "price range": "places.priceRange",
  "category": "places.category",
  "categories": "places.categories",
  "tags": "places.tags",
  "added by": "places.addedBy",
  "verified business": "places.verifiedBusiness",
  "claimed business": "places.claimedBusiness",
  "owner verified": "places.ownerVerified",
  "tap signals that apply": "signals.tapSignals",
  "tap signals 1-3 times to show intensity.": "signals.tapIntensity",
  "submit signals": "signals.submitSignals",
  "quick tap:": "signals.quickTap",
  "taps": "signals.taps",
  "tap rating": "signals.tapRating",
  "thanks for tapping!": "signals.thanksForTapping",
  "write full review": "reviews.writeReview",
  "submit review": "reviews.submitReview",
  "real reviews": "reviews.realReviews",
  "secure reviews": "reviews.secureReviews",
  "review real visits": "reviews.reviewRealVisits",
  "see all reviews": "reviews.seeAllReviews",
  "original review": "reviews.originalReview",
  "translated review": "reviews.translatedReview",
  "show original": "reviews.showOriginal",
  "show translation": "reviews.showTranslation",
  "auto-translate reviews": "reviews.autoTranslate",
  "spam or misleading": "reviews.reportReasons.spam",
  "inappropriate content": "reviews.reportReasons.inappropriate",
  "wrong place": "reviews.reportReasons.wrongPlace",
  "violence or gore": "reviews.reportReasons.violence",
  "uses copyrighted material without permission": "reviews.reportReasons.copyright",
  "another issue not listed above": "reviews.reportReasons.other",
  "review": "reviews.review",
  "edit review": "reviews.editReview",
  "delete review": "reviews.deleteReview",
  "your review": "reviews.yourReview",
  "public note": "reviews.publicNote",
  "private note": "reviews.privateNote",
  "only visible to the business owner": "reviews.privateNoteHint",
  "share your experience": "reviews.shareExperience",
  "how was your visit?": "reviews.howWasYourVisit",
  "what did you like?": "reviews.whatDidYouLike",
  "what could be improved?": "reviews.whatCouldBeImproved",
  "any tips for others?": "reviews.anyTips",
  "helpful": "reviews.helpful",
  "not helpful": "reviews.notHelpful",
  "translate": "reviews.translate",
  "verified visit": "reviews.verifiedVisit",
  "recent reviews": "reviews.recentReviews",
  "top reviews": "reviews.topReviews",
  "all reviews": "reviews.allReviews",
  "sort by": "reviews.sortBy",
  "newest": "reviews.newest",
  "oldest": "reviews.oldest",
  "highest rated": "reviews.highestRated",
  "lowest rated": "reviews.lowestRated",
  "most helpful": "reviews.mostHelpful",
  "find trusted professionals": "pros.subtitle",
  "search professionals...": "pros.search",
  "top rated": "pros.topRated",
  "verified": "pros.verified",
  "available now": "pros.available",
  "get quote": "pros.getQuote",
  "view profile": "pros.viewProfile",
  "portfolio": "pros.portfolio",
  "about": "pros.about",
  "experience": "pros.experience",
  "certifications": "pros.certifications",
  "response time": "pros.responseTime",
  "hire rate": "pros.hireRate",
  "projects completed": "pros.projectsCompleted",
  "no professionals found": "pros.noResults",
  "try adjusting your search": "pros.tryDifferent",
  "request quote": "pros.requestQuote",
  "send message": "pros.sendMessage",
  "book now": "pros.bookNow",
  "add new": "add.addNew",
  "create new": "add.createNew",
  "what are you adding?": "add.whatAdding",
  "select the type of entry you want to create.": "add.selectType",
  "business": "add.business",
  "city": "add.city",
  "universal add": "add.universalAdd",
  "quick add": "add.quickAdd",
  "basic information": "add.basicInfo",
  "business info": "add.businessInfo",
  "business name": "add.businessName",
  "business phone": "add.businessPhone",
  "business email": "add.businessEmail",
  "street address": "add.streetAddress",
  "state": "add.state",
  "zip code": "add.zipCode",
  "country": "add.country",
  "subcategory": "add.subcategory",
  "select a category": "add.selectCategory",
  "select subcategory": "add.selectSubcategory",
  "custom category name": "add.customCategory",
  "description": "add.description",
  "entrances": "add.entrances",
  "entrances required": "add.entrancesRequired",
  "add entrance locations for this place.": "add.addEntrances",
  "at least one entrance is required": "add.atLeastOneEntrance",
  "scan business card": "add.scanBusinessCard",
  "card scanned!": "add.cardScanned",
  "enter manually": "add.enterManually",
  "take a photo": "add.takePhoto",
  "choose from library": "add.chooseFromLibrary",
  "use photo": "add.usePhoto",
  "retake": "add.retake",
  "upload photos to showcase this place.": "add.uploadPhotos",
  "tap to add photos": "add.tapToAddPhotos",
  "take photos in good lighting": "add.goodLighting",
  "tips for scanning:": "add.scanningTips",
  "address is required": "add.addressRequired",
  "this city already exists in tavvy": "add.cityAlreadyExists",
  "add": "add.add",
  "add business": "add.addBusiness",
  "event": "add.event",
  "story": "add.story",
  "location info": "add.locationInfo",
  "name": "add.name",
  "place name": "add.placeName",
  "set hours": "add.setHours",
  "add entrance": "add.addEntrance",
  "main entrance": "add.mainEntrance",
  "submit for review": "add.submitForReview",
  "save draft": "add.saveDraft",
  "preview": "add.preview",
  "add campground": "add.addCampground",
  "add event": "add.addEvent",
  "add experience": "add.addExperience",
  "add ride": "add.addRide",
  "event category": "add.eventCategory",
  "event date": "add.eventDate",
  "event description": "add.eventDescription",
  "free event": "add.eventFree",
  "event image": "add.eventImage",
  "event location": "add.eventLocation",
  "event name": "add.eventName",
  "event price": "add.eventPrice",
  "event time": "add.eventTime",
  "place address": "add.placeAddress",
  "search for a city": "cities.searchCities",
  "rate this city": "cities.rateCity",
  "city details": "cities.cityDetails",
  "city not found": "cities.cityNotFound",
  "city information coming soon...": "cities.cityInfoComingSoon",
  "loading cities...": "cities.loading",
  "filters": "atlas.filters",
  "distance": "atlas.distance",
  "rating": "atlas.rating",
  "recent": "atlas.recent",
  "no places found": "atlas.noResults",
  "try adjusting your filters": "atlas.tryDifferent",
  "show map": "atlas.showMap",
  "show list": "atlas.showList",
  "closed": "atlas.closed",
  "explore worlds with many places inside": "universe.exploreUniverses",
  "universe detail": "universe.universeDetail",
  "universe landing": "universe.universeLanding",
  "universe discovery": "universe.universeDiscovery",
  "sub-universes": "universe.subUniverses",
  "view universe map →": "universe.viewUniverseMap",
  "request universe": "universe.requestUniverse",
  "universe request sent!": "universe.universeRequestSent",
  "discover universes": "universe.discoverUniverses",
  "browse universes": "universe.browseUniverses",
  "search universes": "universe.searchUniverses",
  "featured universes": "universe.featuredUniverses",
  "popular universes": "universe.popularUniverses",
  "new universes": "universe.newUniverses",
  "my universes": "universe.myUniverses",
  "saved universes": "universe.savedUniverses",
  "enter universe": "universe.enterUniverse",
  "explore universe": "universe.exploreUniverse",
  "about this universe": "universe.aboutUniverse",
  "universe details": "universe.universeDetails",
  "places in this universe": "universe.placesInUniverse",
  "related universes": "universe.relatedUniverses",
  "suggest a universe": "universe.suggestUniverse",
  "create universe": "universe.createUniverse",
  "joined universes": "universe.joinedUniverses",
  "trending universes": "universe.trendingUniverses",
  "universe events": "universe.universeEvents",
  "universe members": "universe.universeMembers",
  "universe moderators": "universe.universeModerators",
  "universe places": "universe.universePlaces",
  "universe posts": "universe.universePosts",
  "universe rules": "universe.universeRules",
  "edit profile": "profile.editProfile",
  "my reviews": "profile.myReviews",
  "my posts": "profile.myPosts",
  "followers": "profile.followers",
  "following": "profile.following",
  "follow": "profile.follow",
  "unfollow": "profile.unfollow",
  "message": "profile.message",
  "share profile": "profile.share",
  "log out": "profile.logout",
  "joined": "profile.joined",
  "badges": "profile.badges",
  "achievements": "profile.achievements",
  "activity": "profile.activity",
  "location": "profile.location",
  "bio": "profile.bio",
  "edit bio": "profile.editBio",
  "save bio": "profile.saveBio",
  "upload photo": "profile.uploadPhoto",
  "change photo": "profile.changePhoto",
  "remove photo": "profile.removePhoto",
  "app preferences and account": "settings.appPreferences",
  "language": "settings.language",
  "select language": "settings.selectLanguage",
  "theme": "settings.theme",
  "dark mode": "settings.darkMode",
  "light mode": "settings.lightMode",
  "dark": "settings.dark",
  "light": "settings.light",
  "notifications": "settings.notifications",
  "help & support": "settings.helpSupport",
  "community guidelines": "settings.communityGuidelines",
  "contact support": "settings.contactSupport",
  "email support": "settings.emailSupport",
  "still need help?": "settings.stillNeedHelp",
  "questions or concerns?": "settings.questionsOrConcerns",
  "account": "settings.account",
  "app settings": "settings.appSettings",
  "account settings": "settings.accountSettings",
  "notification settings": "settings.notificationSettings",
  "privacy settings": "settings.privacySettings",
  "system default": "settings.systemDefault",
  "push notifications": "settings.pushNotifications",
  "email notifications": "settings.emailNotifications",
  "sms notifications": "settings.smsNotifications",
  "marketing emails": "settings.marketingEmails",
  "privacy": "settings.privacy",
  "profile visibility": "settings.profileVisibility",
  "location sharing": "settings.locationSharing",
  "data usage": "settings.dataUsage",
  "change password": "settings.changePassword",
  "change email": "settings.changeEmail",
  "change phone": "settings.changePhone",
  "linked accounts": "settings.linkedAccounts",
  "delete account": "settings.deleteAccount",
  "sign out": "settings.signOut",
  "help": "settings.help",
  "faq": "settings.faq",
  "report a problem": "settings.reportProblem",
  "send feedback": "settings.sendFeedback",
  "legal": "settings.legal",
  "about tavvy": "settings.aboutTavvy",
  "version": "settings.version",
  "rate app": "settings.rateApp",
  "share app": "settings.shareApp",
  "apple maps": "maps.appleMaps",
  "google maps": "maps.googleMaps",
  "waze": "maps.waze",
  "drive": "maps.drive",
  "see map": "maps.seeMap",
  "see all results on map": "maps.seeAllOnMap",
  "your parked car": "maps.yourParkedCar",
  "save location": "maps.saveLocation",
  "share location": "maps.shareLocation",
  "location saved!": "maps.locationSaved",
  "unknown location": "maps.unknownLocation",
  "social": "social.social",
  "instagram": "social.instagram",
  "facebook": "social.facebook",
  "x (twitter)": "social.twitter",
  "tiktok": "social.tiktok",
  "whatsapp": "social.whatsapp",
  "now": "time.now",
  "just now": "time.justNow",
  "{{count}} minutes ago": "time.minutesAgo",
  "{{count}} hours ago": "time.hoursAgo",
  "{{count}} days ago": "time.daysAgo",
  "{{count}} weeks ago": "time.weeksAgo",
  "{{count}} months ago": "time.monthsAgo",
  "{{count}} years ago": "time.yearsAgo",
  "today": "time.today",
  "yesterday": "time.yesterday",
  "tomorrow": "time.tomorrow",
  "this week": "time.thisWeek",
  "last week": "time.lastWeek",
  "next week": "time.nextWeek",
  "this month": "time.thisMonth",
  "last month": "time.lastMonth",
  "next month": "time.nextMonth",
  "closest": "filters.closest",
  "cuisine": "filters.cuisine",
  "any": "filters.any",
  "all zones": "filters.allZones",
  "something went wrong": "errors.generic",
  "network error. please check your connection.": "errors.network",
  "server error. please try again later.": "errors.server",
  "not found": "errors.notFound",
  "you are not authorized to view this content": "errors.unauthorized",
  "access denied": "errors.forbidden",
  "request timed out": "errors.timeout",
  "you are offline": "errors.offline",
  "go back": "errors.goBack",
  "invalid input": "errors.invalidInput",
  "this field is required": "errors.required",
  "invalid email address": "errors.invalidEmail",
  "invalid phone number": "errors.invalidPhone",
  "file is too large": "errors.fileTooLarge",
  "unsupported file format": "errors.unsupportedFormat",
  "upload failed": "errors.uploadFailed",
  "location access denied": "errors.locationDenied",
  "camera access denied": "errors.cameraDenied",
  "microphone access denied": "errors.microphoneDenied",
  "success!": "success.success",
  "request submitted!": "success.requestSubmitted",
  "thank you!": "success.thankYou",
  "submitted today": "success.submittedToday",
  "you are now subscribed to tavvy pros!": "success.youAreSubscribed",
  "done!": "success.done",
  "saved!": "success.saved",
  "submitted!": "success.submitted",
  "sent!": "success.sent",
  "deleted!": "success.deleted",
  "updated!": "success.updated",
  "created!": "success.created",
  "uploaded!": "success.uploaded",
  "downloaded!": "success.downloaded",
  "copied!": "success.copied",
  "shared!": "success.shared",
  "all done!": "success.allDone",
  "great job!": "success.greatJob",
  "awesome!": "success.awesome",
  "perfect!": "success.perfect",
  "congratulations!": "success.congratulations",
  "welcome aboard!": "success.welcomeAboard",
  "account created!": "success.accountCreated",
  "profile updated!": "success.profileUpdated",
  "review submitted!": "success.reviewSubmitted",
  "photo uploaded!": "success.photoUploaded",
  "request sent!": "success.requestSent",
  "message sent!": "success.messageSent",
  "payment successful!": "success.paymentSuccessful",
  "subscription active!": "success.subscriptionActive",
  "© {{year}} tavvy, inc. all rights reserved.": "legal.copyright",
  "enforcement": "legal.enforcement",
  "be honest": "legal.beHonest",
  "be respectful": "legal.beRespectful",
  "trust & verification": "legal.trustVerification",
  "welcome to tavvy": "onboarding.welcomeToTavvy",
  "get started": "onboarding.getStarted",
  "let's go!": "onboarding.letsGo",
  "skip": "onboarding.skip",
  "finish": "onboarding.finish",
  "step {{current}} of {{total}}": "onboarding.step",
  "discover amazing places": "onboarding.discoverPlaces",
  "share your experiences": "onboarding.shareExperiences",
  "connect with professionals": "onboarding.connectWithPros",
  "explore universes": "onboarding.exploreUniverses",
  "tap to rate": "onboarding.tapToRate",
  "signal system": "onboarding.signalSystem",
  "continue as guest": "onboarding.continueAsGuest",
  "ecard": "ecard.title",
  "your digital business card": "ecard.subtitle",
  "create ecard": "ecard.create",
  "edit ecard": "ecard.edit",
  "share ecard": "ecard.share",
  "title": "ecard.title_field",
  "company": "ecard.company",
  "social links": "ecard.social",
  "add social link": "ecard.addSocial",
  "linkedin": "ecard.linkedin",
  "twitter": "ecard.twitter",
  "photo": "ecard.photo",
  "template": "ecard.template",
  "color": "ecard.color",
  "qr code": "ecard.qrCode",
  "download qr code": "ecard.downloadQR",
  "scan to view ecard": "ecard.scanToView",
  "share via": "ecard.shareVia",
  "copy link": "ecard.copyLink",
  "link copied!": "ecard.linkCopied",
  "you don't have an ecard yet": "ecard.noEcard",
  "create your first digital business card": "ecard.createFirst",
  "realtors": "realtors.title",
  "find your perfect home": "realtors.subtitle",
  "search properties": "realtors.search",
  "find a realtor": "realtors.findRealtor",
  "nearby listings": "realtors.nearby",
  "featured properties": "realtors.featured",
  "for sale": "realtors.forSale",
  "for rent": "realtors.forRent",
  "sold": "realtors.sold",
  "price": "realtors.price",
  "beds": "realtors.beds",
  "baths": "realtors.baths",
  "sq ft": "realtors.sqft",
  "lot size": "realtors.lot",
  "year built": "realtors.yearBuilt",
  "property type": "realtors.propertyType",
  "house": "realtors.house",
  "condo": "realtors.condo",
  "townhouse": "realtors.townhouse",
  "apartment": "realtors.apartment",
  "land": "realtors.land",
  "commercial": "realtors.commercial",
  "open house": "realtors.openHouse",
  "virtual tour": "realtors.virtualTour",
  "schedule a tour": "realtors.schedule",
  "contact agent": "realtors.contact",
  "mortgage calculator": "realtors.mortgage",
  "home value estimate": "realtors.estimate",
  "neighborhood": "realtors.neighborhood",
  "schools": "realtors.schools",
  "walk score": "realtors.walkScore",
  "transit score": "realtors.transit",
  "crime stats": "realtors.crime",
  "property taxes": "realtors.taxes",
  "hoa fees": "realtors.hoa",
  "price history": "realtors.history",
  "similar homes": "realtors.similar",
  "saved homes": "realtors.saved",
  "price alerts": "realtors.alerts",
  "messages": "messages.messages",
  "inbox": "messages.inbox",
  "sent": "messages.sent",
  "archived": "messages.archived",
  "new message": "messages.newMessage",
  "type a message...": "messages.typeMessage",
  "send": "messages.send",
  "reply": "messages.reply",
  "forward": "messages.forward",
  "archive": "messages.archive",
  "mark as read": "messages.markAsRead",
  "mark as unread": "messages.markAsUnread",
  "no messages": "messages.noMessages",
  "no conversations yet": "messages.noConversations",
  "start a conversation": "messages.startConversation",
  "online": "messages.online",
  "offline": "messages.offline",
  "last seen": "messages.lastSeen",
  "typing...": "messages.typing",
  "delivered": "messages.delivered",
  "read": "messages.read",
  "attach photo": "messages.attachPhoto",
  "attach file": "messages.attachFile",
  "share contact": "messages.shareContact",
  "block user": "messages.blockUser",
  "report user": "messages.reportUser",
  "mark all as read": "notifications.markAllRead",
  "clear all": "notifications.clearAll",
  "no notifications": "notifications.noNotifications",
  "earlier": "notifications.earlier",
  "new follower": "notifications.newFollower",
  "liked your post": "notifications.newLike",
  "commented on your post": "notifications.newComment",
  "left a review": "notifications.newReview",
  "price alert": "notifications.priceAlert",
  "reminder": "notifications.reminder",
  "update available": "notifications.update",
  "special offer": "notifications.promotion",
  "request a new community": "actionMenu.universeSubtitle",
  "add a missing spot": "actionMenu.placeSubtitle",
  "expand to a new area": "actionMenu.citySubtitle",
  "rate a place you visited": "actionMenu.reviewSubtitle",
  "new place": "addPlace.newPlace",
  "what kind of place is it?": "addPlace.categoryQuestion",
  "what type of {{category}}?": "addPlace.subcategoryQuestion",
  "let's start": "addPlace.letsStart",
  "what is the name of this place?": "addPlace.nameQuestion",
  "e.g. joe's coffee": "addPlace.namePlaceholder",
  "where is it located?": "addPlace.locationQuestion",
  "how can people reach this place? (optional)": "addPlace.contactQuestion",
  "tell us a bit more about it (optional).": "addPlace.detailsQuestion",
  "great vibes, good wifi...": "addPlace.detailsPlaceholder",
  "add a photo to show the vibe.": "addPlace.photosQuestion",
  "have a business card?": "addPlace.haveBusinessCard",
  "scan it to auto-fill the form with name, address, phone, and website.": "addPlace.scanDescription",
  "take a photo and we'll extract the details": "addPlace.takePhotoExtract",
  "type in the place details yourself": "addPlace.typeDetails",
  "good lighting helps accuracy": "addPlace.tipLighting",
  "hold the card flat and steady": "addPlace.tipFlat",
  "make sure text is readable": "addPlace.tipReadable",
  "form has been pre-filled with business card details. review and edit as needed.": "addPlace.formPreFilled",
  "place added successfully. thank you for contributing!": "addPlace.successMessage",
  "you must be logged in to add a place.": "addPlace.errorLogin",
  "failed to add place: {{error}}": "addPlace.errorFailed",
  "an unexpected error occurred. please try again.": "addPlace.errorUnexpected",
  "discover useful tools and services": "appsHome.subtitle",
  "all apps": "appsHome.all",
  "search apps...": "appsHome.search",
  "no apps found": "appsHome.noResults",
  "explore communities and interests": "universes.subtitle",
  "search universes...": "universes.search",
  "members": "universes.members",
  "posts": "universes.posts",
  "events": "universes.events",
  "join": "universes.join",
  "leave": "universes.leave",
  "rules": "universes.rules",
  "moderators": "universes.moderators",
  "create post": "universes.createPost",
  "no universes found": "universes.noResults",
  "request new universe": "universes.requestNew",
  "your saved places and items": "saved.subtitle",
  "professionals": "saved.pros",
  "nothing saved yet": "saved.empty",
  "save places and items to find them here": "saved.emptySubtitle",
  "remove": "saved.remove",
  "remove all": "saved.removeAll",
  "remove from saved?": "saved.confirmRemove",
  "remove all saved items?": "saved.confirmRemoveAll",
  "find what you need fast": "quickFinds.subtitle",
  "budget friendly": "quickFinds.budget",
  "what are you looking for?": "quickFinds.search",
  "results": "quickFinds.results",
  "rate city": "rateCity.title",
  "help others discover great cities": "rateCity.subtitle",
  "select a city": "rateCity.selectCity",
  "search for a city...": "rateCity.searchCity",
  "overall rating": "rateCity.overallRating",
  "rate by category": "rateCity.categories",
  "safety": "rateCity.safety",
  "cleanliness": "rateCity.cleanliness",
  "transportation": "rateCity.transportation",
  "nightlife": "rateCity.nightlife",
  "food & dining": "rateCity.food",
  "culture & arts": "rateCity.culture",
  "nature & parks": "rateCity.nature",
  "cost of living": "rateCity.costOfLiving",
  "write a review": "rateCity.writeReview",
  "share your experience...": "rateCity.reviewPlaceholder",
  "submit rating": "rateCity.submit",
  "thank you for your rating!": "rateCity.thankYou",
  "your feedback helps others discover great cities": "rateCity.helpOthers",
  "find the perfect campsite": "rv.subtitle",
  "search campgrounds": "rv.search",
  "nearby campgrounds": "rv.nearby",
  "popular destinations": "rv.popular",
  "hookups": "rv.hookups",
  "electric": "rv.electric",
  "water": "rv.water",
  "sewer": "rv.sewer",
  "wifi": "rv.wifi",
  "showers": "rv.showers",
  "restrooms": "rv.restrooms",
  "laundry": "rv.laundry",
  "store": "rv.store",
  "pool": "rv.pool",
  "pet friendly": "rv.petFriendly",
  "campfires allowed": "rv.campfires",
  "rv size": "rv.rvSize",
  "max length": "rv.maxLength",
  "pull-through sites": "rv.pullThrough",
  "back-in sites": "rv.backIn",
  "tent sites": "rv.tent",
  "cabins": "rv.cabin",
  "yurts": "rv.yurt",
  "glamping": "rv.glamping",
  "price per night": "rv.pricePerNight",
  "check availability": "rv.availability",
  "campground rules": "rv.rules",
  "check-in time": "rv.checkIn",
  "check-out time": "rv.checkOut",
  "quiet hours": "rv.quietHours",
  "rides & attractions": "rides.title",
  "discover amazing experiences": "rides.subtitle",
  "search attractions": "rides.search",
  "nearby attractions": "rides.nearby",
  "popular rides": "rides.popular",
  "water parks": "rides.waterPark",
  "amusement parks": "rides.amusement",
  "zoos & aquariums": "rides.zoo",
  "museums": "rides.museum",
  "adventure": "rides.adventure",
  "tours": "rides.tours",
  "shows & entertainment": "rides.shows",
  "tickets": "rides.tickets",
  "buy tickets": "rides.buyTickets",
  "skip the line": "rides.skipLine",
  "fast pass": "rides.fastPass",
  "group discount": "rides.groupDiscount",
  "wait time": "rides.waitTime",
  "minutes": "rides.minutes",
  "height requirement": "rides.height",
  "age restriction": "rides.ageRestriction",
  "accessibility": "rides.accessibility",
  "wheelchair accessible": "rides.wheelchair",
  "parking": "rides.parking",
  "food & drink": "rides.foodDrink",
  "souvenirs": "rides.souvenirs",
  "park map": "rides.map",
  "show schedule": "rides.schedule",
  "weather": "rides.weather",
  "search...": "search.placeholder",
  "search for": "search.searchFor",
  "recent searches": "search.recent",
  "relevance": "search.relevance",
  "price: high to low": "search.priceHigh",
  "price: low to high": "search.priceLow",
  "popularity": "search.popularity",
  "upcoming events": "events.upcoming",
  "events near you": "events.nearby",
  "event details": "events.details",
  "date": "events.date",
  "time": "events.time",
  "venue": "events.venue",
  "free": "events.free",
  "get tickets": "events.getTickets",
  "add to calendar": "events.addToCalendar",
  "share event": "events.share",
  "be the first to review this event": "events.beFirst",
  "best for": "events.bestFor",
  "vibe": "events.vibe",
  "source": "events.source",
  "no events found": "events.noEvents",
  "check back later for upcoming events": "events.checkBack",
  "load more events": "events.loadMore",
  "tavvy shield": "shield.title",
  "protection built into discovery": "shield.subtitle",
  "verified identity": "shield.verifiedIdentity",
  "all professionals complete identity verification, license validation, and background checks": "shield.verifiedIdentityDesc",
  "real activity signals": "shield.realSignals",
  "see actual customer experiences, not manipulated star ratings": "shield.realSignalsDesc",
  "payment protection": "shield.paymentProtection",
  "choose direct payment or let tavvy pay on your behalf with escrow protection": "shield.paymentProtectionDesc",
  "professional inspection": "shield.professionalInspection",
  "optional licensed professional inspection for added peace of mind": "shield.professionalInspectionDesc",
  "code compliance": "shield.codeCompliance",
  "municipal code compliance verification for applicable services": "shield.codeComplianceDesc",
  "transparent fees": "shield.transparentFees",
  "simple flat percentage fee with no hidden costs": "shield.transparentFeesDesc",
  "how it works": "shield.howItWorks",
  "find a verified professional": "shield.step1",
  "review their real signals and history": "shield.step2",
  "book with payment protection": "shield.step3",
  "rate your experience with signal taps": "shield.step4",
  "learn more": "shield.learnMore",
  "frequently asked questions": "shield.faq",
  "what is tavvy shield?": "shield.faqQ1",
  "tavvy shield is our comprehensive protection system that ensures safe, verified transactions between users and service providers.": "shield.faqA1",
  "how does payment protection work?": "shield.faqQ2",
  "funds are held in escrow until the service is completed to your satisfaction. you can pay directly or have tavvy pay on your behalf.": "shield.faqA2",
  "what if i'm not satisfied?": "shield.faqQ3",
  "our dispute resolution team will work with both parties to find a fair solution. escrow funds are released only when issues are resolved.": "shield.faqA3",
  "this screen ran into a problem. you can try again or go back.": "errorBoundary.message",
  "try again": "errorBoundary.tryAgain",
  "time clock": "timeclock.title",
  "hi, {{name}}": "timeclock.hi",
  "on the clock": "timeclock.onTheClock",
  "you're clocked out": "timeclock.clockedOut",
  "since {{time}}": "timeclock.since",
  "select job": "timeclock.selectJob",
  "no active jobs assigned": "timeclock.noJobs",
  "clock in": "timeclock.clockIn",
  "clock out": "timeclock.clockOut",
  "getting your location…": "timeclock.gettingLocation",
  "on site": "timeclock.onSite",
  "off site": "timeclock.offSite",
  "you clocked in away from the job site. your supervisor will see this.": "timeclock.offSiteWarn",
  "you're not set up as a crew member yet. ask your employer to send an invite.": "timeclock.notCrew",
  "please log in to use the time clock.": "timeclock.loginNeeded",
  "saved offline — will sync when you're back online": "timeclock.pendingSync",
  "my hours": "timesheet.title",
  "pay period": "timesheet.period",
  "total hours": "timesheet.totalHours",
  "regular": "timesheet.regular",
  "overtime": "timesheet.overtime",
  "gross pay": "timesheet.gross",
  "approved": "timesheet.approved",
  "awaiting approval": "timesheet.pending",
  "not summarized yet — shows your live hours below.": "timesheet.notBuilt",
  "shifts": "timesheet.shifts",
  "no hours logged this period.": "timesheet.noEntries",
  "open": "timesheet.open",
  "please log in to see your hours.": "timesheet.loginNeeded",
  "you're not set up as a crew member yet.": "timesheet.notCrew"
};

Object.assign(RELEASE_COPY_KEYS, {
  "Find your next happy place.": "discoveryTitle",
  "Good food, new adventures, and people you can trust.": "discoverySubtitle",
  "Map": "map",
  "Surprise": "surprise",
  "Let Tavvy decide": "letTavvyDecide",
  "Search by vibe": "searchByVibe",
  "What's your mood?": "moodQuestion",
  "Hungry": "hungry",
  "Restaurants & Food": "restaurantsFood",
  "Thirsty": "thirsty",
  "Bars & Cafes": "barsCafes",
  "Places to explore": "placesToExplore",
  "Find good food and the signals that matter.": "foodSignals",
  "Find a stay that feels right for you.": "rightStay",
  "Stories are coming soon": "storiesSoon",
  "Great stories about your favorite places are about to go live. Stay tuned!": "storiesSoonMessage",
  "Create your eCard": "createECard",
  "Start with your name. Add links and customize your card next.": "setupIntro",
  "Photo is optional": "photoOptional",
  "Title / role": "titleRole",
  "(optional)": "optional",
  "Creating draft…": "creatingDraft",
  "Create draft": "createDraft",
  "Your full name": "yourFullName",
  "Primary color": "primaryColor",
  "Choose card type & template": "chooseTypeTemplate",
  "All tools": "allTools",
  "Restart Required": "restartRequired",
  "Please restart the app for the layout changes to take effect.": "restartMessage"
});
Object.assign(RELEASE_COPY_KEYS, {
  "Find your next theme park adventure.": "ridesDescription",
  "Discover the places within parks, airports and more.": "universesDescription",
  "Find local people to help with your next project.": "prosDescription",
  "Get to know a new neighborhood or city.": "citiesDescription",
  "Explore guides and ideas for your next trip.": "atlasDescription",
  "Your card stays private until you publish.": "privateDraftNote",
  "Retry save": "retrySave",
  "Contact Form · Pro": "formPro"
});

Object.assign(RELEASE_COPY_KEYS, {"Great food": "needFood", "Quiet conversation": "needQuiet", "Quick visit": "needQuick", "Good value": "needValue"});

Object.assign(RELEASE_COPY_KEYS, {"Any location": "anyLocation", "Search is temporarily unavailable.": "searchUnavailable", "Retry search": "retrySearch", "Searching…": "searching", "Checking guest reports…": "checkingReports", "Try another search or location.": "tryAnotherSearch", "Search is temporarily unavailable": "searchUnavailable", "Searching...": "searching"});

// Atlas audio controls; voice IDs and playback values remain unchanged.
Object.assign(RELEASE_COPY_KEYS, {
  "Listen to this article": "atlasListen",
  "Audio is not available for this article yet.": "atlasUnavailable",
  "Female": "atlasFemale",
  "Male": "atlasMale",
  "Play": "atlasPlay",
  "Pause": "atlasPause",
  "Audio position": "atlasPosition",
  "Back 15 seconds": "atlasBack",
  "Playback speed": "atlasSpeed",
  "Forward 15 seconds": "atlasForward",
  "Audio could not play. Tap Play to try again.": "atlasPlayError"
});

Object.assign(RELEASE_COPY_KEYS, {"Business": "creationBusiness", "Card for": "creationCardFor"});

Object.assign(RELEASE_COPY_KEYS, {"Joined": "accountFinishJoined", "Deleting...": "accountFinishDeleting"});

// Equivalent app-authored discovery labels share existing translations.
Object.assign(RELEASE_COPY_KEYS, {
  "Search Results": "publicFinishSearchResults",
  "Search results": "publicFinishSearchResults",
  "Search places or locations": "publicFinishSearchLocations",
  "Location is off. Enter a city to find places.": "locationDenied",
  "Location is unavailable. Enter a city to find places.": "locationUnavailable"
});

// Approved Free/Pro offer; prices and saved customer content are unchanged.
Object.assign(RELEASE_COPY_KEYS, {
  "No plan-based link limit": "ecardFreeOffer1",
  "Free includes a design in every category and no plan-based link limit. Pro adds premium designs, galleries, embedded videos, contact forms and professional credentials.": "ecardFreeOffer2",
  "Premium designs": "ecardFreeOffer3",
  "Choose from premium layouts and color palettes.": "ecardFreeOffer4",
  "Photo galleries": "ecardFreeOffer5",
  "Show multiple photos on your card.": "ecardFreeOffer6",
  "Embedded videos": "ecardFreeOffer7",
  "Add playable videos to your card.": "ecardFreeOffer8",
  "Contact forms": "ecardFreeOffer9",
  "Let visitors send an inquiry from your card.": "ecardFreeOffer10",
  "Professional credentials": "ecardFreeOffer11",
  "Display your professional credentials.": "ecardFreeOffer12"
});
