import React, { useCallback, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Image, TouchableOpacity, Linking, Alert, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation, useRoute, useFocusEffect } from '@react-navigation/native';
import { TavvyEvent } from '../lib/eventsService';
import { fetchEventSignals, getEventReviewCount, SignalAggregate } from '../lib/eventReviews';
import { eventPrice } from '../lib/eventDiscovery';
import { useThemeContext } from '../contexts/ThemeContext';
import design from '../config/design.json';
export default function EventDetailScreen() {
 const navigation=useNavigation<any>(),route=useRoute<any>(),{isDark}=useThemeContext();
 const event=route.params?.event as TavvyEvent|undefined,palette=isDark?design.dark:design.light;
 const [signals,setSignals]=useState<{best_for:SignalAggregate[];vibe:SignalAggregate[];heads_up:SignalAggregate[]}>({best_for:[],vibe:[],heads_up:[]});
 const [count,setCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 useFocusEffect(useCallback(()=>{let active=true;if(!event)return;setLoading(true);setError(false);Promise.all([fetchEventSignals(event.id),getEventReviewCount(event.id)]).then(([rows,n])=>{if(active){setSignals(rows);setCount(n);}}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[event?.id,retry]));
 const open=async(url:string)=>{if(!/^https?:\/\//i.test(url))return;try{await Linking.openURL(url);}catch{Alert.alert('Link unavailable','This link could not be opened.');}};
 return <SafeAreaView style={[styles.container,{backgroundColor:palette.background}]}><ScrollView contentContainerStyle={styles.content}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={[styles.link,{color:palette.link}]}>← Happening Now</Text></TouchableOpacity>{!event?<Text style={{color:palette.text}}>Event unavailable.</Text>:<>
 {event.image_url&&<Image source={{uri:event.image_url}} style={styles.cover}/>}<Text style={[styles.eyebrow,{color:palette.link}]}>{event.source==='tavvy'?'COMMUNITY EVENT':event.source.toUpperCase()}</Text><Text style={[styles.title,{color:palette.text}]}>{event.title}</Text><Text style={[styles.body,{color:palette.textSecondary}]}>{Number.isFinite(Date.parse(event.start_time))?new Date(event.start_time).toLocaleString():'Date not listed'}</Text><Text style={[styles.body,{color:palette.textSecondary}]}>{[event.venue_name,event.address,event.city,event.state].filter(Boolean).join(' · ')}</Text><Text style={[styles.body,{color:palette.text}]}>{eventPrice(event)}</Text>
 {event.lat!=null&&event.lng!=null&&<TouchableOpacity onPress={()=>open(`https://www.google.com/maps/search/?api=1&query=${event.lat},${event.lng}`)}><Text style={[styles.link,{color:palette.link}]}>Directions ↗</Text></TouchableOpacity>}
 {event.description&&<Text style={[styles.body,{color:palette.textSecondary}]}>{event.description}</Text>}
 {event.url&&/^https?:\/\//i.test(event.url)&&<TouchableOpacity onPress={()=>open(event.url!)} style={[styles.button,{borderColor:palette.border,backgroundColor:palette.surface}]}><Text style={{color:palette.link}}>Event information & tickets ↗</Text></TouchableOpacity>}
 <View style={[styles.section,{borderColor:palette.border}]}><Text style={[styles.heading,{color:palette.text}]}>What people noticed</Text>{loading?<ActivityIndicator color={palette.link}/>:error?<TouchableOpacity onPress={()=>setRetry(n=>n+1)}><Text style={[styles.body,{color:palette.textSecondary}]}>Event taps could not be loaded. Tap to retry.</Text></TouchableOpacity>:<><Text style={[styles.body,{color:palette.textSecondary}]}>{count?`${count} ${count===1?'review':'reviews'}`:'No taps yet. Share what stood out to you.'}</Text>{Object.entries(signals).map(([key,rows])=>rows.length>0&&<View key={key}><Text style={[styles.subheading,{color:palette.text}]}>{key==='best_for'?'The Good':key==='vibe'?'The Vibe':'Heads Up'}</Text>{rows.map(signal=><View key={signal.signal_id} style={[styles.signal,{backgroundColor:palette.surface}]}><Text style={{color:palette.text,flex:1}}>{signal.icon} {signal.label}</Text><Text style={{color:palette.textSecondary}}>{signal.tap_total} taps</Text></View>)}</View>)}</>}
 <TouchableOpacity accessibilityRole="button" onPress={()=>navigation.navigate('AddReview',{eventId:event.id,eventName:event.title,isEvent:true})} style={[styles.button,{backgroundColor:design.primary,borderColor:design.primary}]}><Text style={{color:'#FFFFFF',fontWeight:'600'}}>Add or update your taps</Text></TouchableOpacity></View>
 </>}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1},content:{padding:20,paddingBottom:100},link:{fontSize:15,paddingVertical:14},cover:{width:'100%',height:250,borderRadius:20,marginTop:12},eyebrow:{fontSize:11,fontWeight:'700',letterSpacing:1.4,marginTop:24},title:{fontSize:30,fontWeight:'700',letterSpacing:-.6,marginTop:12},body:{fontSize:15,lineHeight:24,marginVertical:8},heading:{fontSize:23,fontWeight:'600'},subheading:{fontSize:17,fontWeight:'600',marginTop:18,marginBottom:10},button:{padding:16,borderWidth:1,borderRadius:14,marginTop:14},section:{marginTop:28,paddingTop:24,borderTopWidth:1},signal:{padding:14,borderRadius:12,marginBottom:8,flexDirection:'row',gap:10}});
