import React,{useState} from 'react';
import {View,Text,ScrollView,TouchableOpacity,ActivityIndicator} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useNavigation,useRoute} from '@react-navigation/native';
import ToolHeader from '../components/ToolHeader';
import {useAuth} from '../contexts/AuthContext';
import {useThemeContext} from '../contexts/ThemeContext';
import {useProviderRead} from '../hooks/useProviderRead';
import {getMyProviderProjects,getMyProviderMatches} from '../lib/providerProjectStatus';
import {supabase} from '../lib/supabaseClient';
function Matches({userId,projectId}:{userId:string;projectId:string}){const {theme}=useThemeContext();const navigation=useNavigation<any>();const state=useProviderRead(JSON.stringify(['matches',projectId]),()=>getMyProviderMatches(supabase,userId,projectId));return <View style={{gap:16,marginTop:20}}><Text style={{fontSize:20,fontWeight:'700',color:theme.text}}>Professional responses</Text>{state.loading?<ActivityIndicator color={theme.text}/>:state.error?<><Text accessibilityRole="alert" style={{color:theme.text}}>{state.error}</Text><TouchableOpacity accessibilityRole="button" onPress={state.retry} style={{padding:14}}><Text style={{color:theme.text}}>Try again</Text></TouchableOpacity></>:!state.value?.matches.length?<Text style={{color:theme.textSecondary}}>No responses to show.</Text>:state.value.matches.map(m=><View key={m.id} style={{padding:18,backgroundColor:theme.surface,borderRadius:14,gap:10}}><Text style={{fontSize:18,fontWeight:'600',color:theme.text}}>{m.provider?.is_active===true?m.provider.business_name:'Professional profile unavailable'}</Text><Text style={{color:theme.textSecondary}}>{String(m.pro_status||'Status unavailable').replace(/_/g,' ')}</Text>{m.quote_description?<Text style={{color:theme.text}}>{m.quote_description}</Text>:null}{m.quote_amount_cents!=null?<Text style={{color:theme.text}}>Quote: ${(m.quote_amount_cents/100).toFixed(2)}</Text>:null}{m.quote_valid_until?<Text style={{color:theme.textSecondary}}>Valid until {new Date(m.quote_valid_until).toLocaleDateString()}</Text>:null}{m.provider?.is_active===true?<TouchableOpacity accessibilityRole="button" style={{paddingVertical:12}} onPress={()=>navigation.navigate('ProsProfile',{slug:m.provider.slug})}><Text style={{color:theme.text}}>View profile and contact</Text></TouchableOpacity>:null}</View>)}{state.value?.hasMore?<Text style={{color:theme.textSecondary}}>Showing the latest 50 responses.</Text>:null}</View>;}
export default function ProsProjectStatusScreen(){const {user}=useAuth();const {theme}=useThemeContext();const route=useRoute<any>();const navigation=useNavigation<any>();const [chosen,setChosen]=useState<string|null>(null);const routeId=typeof route.params?.projectId==='string'?route.params.projectId:undefined;const state=useProviderRead(JSON.stringify(['my-projects',routeId]),()=>user?getMyProviderProjects(supabase,user.id,routeId):Promise.resolve([]));return <SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ToolHeader title="Your project requests"/><ScrollView contentContainerStyle={{padding:20,paddingBottom:100}}>{!user?<TouchableOpacity accessibilityRole="button" onPress={()=>navigation.navigate('Login')} style={{padding:16}}><Text style={{color:theme.text}}>Sign in to view your requests</Text></TouchableOpacity>:state.loading?<ActivityIndicator color={theme.text}/>:state.error?<><Text accessibilityRole="alert" style={{color:theme.text}}>{state.error}</Text><TouchableOpacity accessibilityRole="button" onPress={state.retry} style={{padding:16}}><Text style={{color:theme.text}}>Try again</Text></TouchableOpacity></>:!state.value?.length?<Text style={{color:theme.textSecondary}}>No saved requests are available for this account.</Text>:<>{state.value.map(p=><View key={p.id} style={{marginBottom:16}}><TouchableOpacity accessibilityRole="button" onPress={()=>setChosen(p.id)} style={{padding:18,borderRadius:14,backgroundColor:theme.surface,gap:8}}><Text style={{fontSize:18,fontWeight:'700',color:theme.text}}>{p.category_id.replace(/[_-]/g,' ')} request</Text><Text style={{color:theme.textSecondary}}>{p.status} · {new Date(p.created_at).toLocaleDateString()}</Text><Text style={{color:theme.text}}>{p.description}</Text><Text style={{color:theme.text}}>View responses</Text></TouchableOpacity>{chosen===p.id||routeId===p.id?<Matches key={`${user.id}:${p.id}`} userId={user.id} projectId={p.id}/>:null}</View>)}{state.value.length===25?<Text style={{color:theme.textSecondary}}>Showing your latest 25 requests.</Text>:null}</>}</ScrollView></SafeAreaView>;}
