/**
 * ProsLeadDetailScreen - High-Fidelity Lead View for Pros
 * Install path: screens/ProsLeadDetailScreen.tsx
 * 
 * This screen displays the full technical details of a lead, including
 * the complexity score and matching reasons generated by the Tavvy Brain.
 */

import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  SafeAreaView,
  ActivityIndicator,
  Image,
  Alert,
} from 'react-native';
import { RouteProp, useRoute, useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { ProsColors } from '../constants/ProsConfig';
import { supabase } from '../lib/supabaseClient';
import { useTranslation } from 'react-i18next';

type RouteParams = {
  ProsLeadDetail: { leadId: string | number };
};

export default function ProsLeadDetailScreen() {
  const { t } = useTranslation();
  const route = useRoute<RouteProp<RouteParams, 'ProsLeadDetail'>>();
  const navigation = useNavigation();
  const { leadId } = route.params;
  
  const [lead, setLead] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchLeadDetails();
  }, [leadId]);

  const fetchLeadDetails = async () => {
    setLoading(true);
    try {
      // Fetch lead with complexity and matching data
      const { data, error } = await supabase
        .from('leads')
        .select(`
          *,
          category:service_categories(name)
        `)
        .eq('id', leadId)
        .single();

      if (error) throw error;
      setLead(data);
    } catch (error) {
      console.error('Error fetching lead:', error);
      Alert.alert('Error', 'Could not load lead details.');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={ProsColors.primary} />
      </View>
    );
  }

  if (!lead) return null;

  const complexity = lead.complexity_data || { score: 0, level: 'Standard', factors: [] };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={24} color="#374151" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Project Details</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Match & Complexity Badges */}
        <View style={styles.badgeRow}>
          <View style={[styles.complexityBadge, styles[`complexity${complexity.level}`]]}>
            <Ionicons name="speedometer-outline" size={14} color="#FFF" />
            <Text style={styles.badgeText}>{complexity.level} Complexity</Text>
          </View>
          {lead.match_score >= 40 && (
            <View style={styles.matchBadge}>
              <Ionicons name="star" size={14} color="#FFF" />
              <Text style={styles.badgeText}>High Match</Text>
            </View>
          )}
        </View>

        <Text style={styles.categoryTitle}>{lead.category?.name}</Text>
        <Text style={styles.locationText}>
          <Ionicons name="location-outline" size={16} /> {lead.city}, {lead.state}
        </Text>

        {/* Complexity Factors */}
        {complexity.factors.length > 0 && (
          <View style={styles.factorsBox}>
            <Text style={styles.sectionLabel}>COMPLEXITY FACTORS</Text>
            <View style={styles.factorChips}>
              {complexity.factors.map((factor: string, i: number) => (
                <View key={i} style={styles.factorChip}>
                  <Text style={styles.factorText}>{factor}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        <View style={styles.divider} />

        {/* Technical Details */}
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>TECHNICAL SPECIFICATIONS</Text>
          {Object.entries(lead.dynamic_answers || {}).map(([question, answer]: [string, any], i) => (
            <View key={i} style={styles.detailRow}>
              <Text style={styles.detailQuestion}>{question}</Text>
              <Text style={styles.detailAnswer}>
                {Array.isArray(answer) ? answer.join(', ') : answer}
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.divider} />

        {/* Description */}
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>PROJECT DESCRIPTION</Text>
          <Text style={styles.descriptionText}>{lead.description}</Text>
        </View>

        {/* Photos */}
        {lead.photos && lead.photos.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionLabel}>PROJECT PHOTOS ({lead.photos.length})</Text>
            <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.photoScroll}>
              {lead.photos.map((photo: string, i: number) => (
                <Image key={i} source={{ uri: photo }} style={styles.photo} />
              ))}
            </ScrollView>
          </View>
        )}
      </ScrollView>

      <View style={styles.footer}>
        <TouchableOpacity style={styles.bidButton}>
          <Text style={styles.bidButtonText}>Send a Bid</Text>
          <Ionicons name="send" size={18} color="#FFF" />
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFF' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  headerTitle: { fontSize: 18, fontWeight: '600' },
  backButton: { padding: 4 },
  content: { flex: 1, padding: 20 },
  badgeRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  complexityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    gap: 4,
  },
  complexityHigh: { backgroundColor: '#EF4444' },
  complexityMedium: { backgroundColor: '#F59E0B' },
  complexityStandard: { backgroundColor: '#10B981' },
  matchBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6366F1',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    gap: 4,
  },
  badgeText: { color: '#FFF', fontSize: 12, fontWeight: '600' },
  categoryTitle: { fontSize: 28, fontWeight: 'bold', color: '#111827' },
  locationText: { fontSize: 16, color: '#6B7280', marginTop: 4, marginBottom: 20 },
  factorsBox: { backgroundColor: '#F9FAFB', padding: 16, borderRadius: 12, marginBottom: 20 },
  sectionLabel: { fontSize: 11, fontWeight: '700', color: '#9CA3AF', letterSpacing: 1, marginBottom: 12 },
  factorChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  factorChip: { backgroundColor: '#E5E7EB', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  factorText: { fontSize: 12, color: '#374151', fontWeight: '500' },
  divider: { height: 1, backgroundColor: '#E5E7EB', marginVertical: 20 },
  section: { marginBottom: 8 },
  detailRow: { marginBottom: 16 },
  detailQuestion: { fontSize: 13, color: '#6B7280', marginBottom: 4 },
  detailAnswer: { fontSize: 16, color: '#111827', fontWeight: '500' },
  descriptionText: { fontSize: 15, color: '#374151', lineHeight: 22 },
  photoScroll: { marginTop: 12 },
  photo: { width: 120, height: 120, borderRadius: 12, marginRight: 12 },
  footer: { padding: 20, borderTopWidth: 1, borderTopColor: '#E5E7EB' },
  bidButton: {
    backgroundColor: ProsColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 12,
    gap: 8,
  },
  bidButtonText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
});
