import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import Stripe from "https://esm.sh/stripe@12.12.0?target=deno";

export type DeletionResult =
  | { status: "deleted" }
  | { status: "available" }
  | { status: "unavailable"; code: string }
  | { status: "error"; code: string; message: string };

const STORAGE_BUCKETS = ["avatars", "ecard-assets", "place-photos"] as const;

function stripeClient(): Stripe | null {
  const key = Deno.env.get("STRIPE_SECRET_KEY");
  if (!key) return null;
  // @ts-ignore fetch client works in Deno
  return new Stripe(key, { httpClient: Stripe.createFetchHttpClient(), apiVersion: "2023-10-16" });
}

async function cancelStripeSubscription(stripe: Stripe, subscriptionId: string | null | undefined) {
  if (!subscriptionId) return;
  try {
    const sub = await stripe.subscriptions.retrieve(subscriptionId);
    if (sub.status !== "canceled") {
      await stripe.subscriptions.cancel(subscriptionId);
    }
  } catch (error) {
    // A retry may find that the subscription was removed after an earlier attempt.
    if (error && typeof error === "object" && "statusCode" in error && error.statusCode === 404) return;
    console.error("[delete-account] Stripe cancel failed for", subscriptionId, error);
    throw error;
  }
}

/**
 * Best-effort Apple token revocation (Apple Guideline 5.1.1(v)). No-ops
 * cleanly if APPLE_TEAM_ID / APPLE_KEY_ID / APPLE_PRIVATE_KEY / APPLE_CLIENT_ID
 * secrets are not configured — those come from the Apple Developer account
 * and cannot be generated by this function. Deletion proceeds either way;
 * this never blocks the rest of the flow.
 */
async function revokeAppleTokenBestEffort(admin: SupabaseClient, userId: string) {
  const teamId = Deno.env.get("APPLE_TEAM_ID");
  const keyId = Deno.env.get("APPLE_KEY_ID");
  const privateKey = Deno.env.get("APPLE_PRIVATE_KEY");
  const clientId = Deno.env.get("APPLE_CLIENT_ID");
  if (!teamId || !keyId || !privateKey || !clientId) {
    console.warn("[delete-account] Apple revocation secrets not configured; skipping (prepared, not active).");
    return;
  }
  try {
    const { data } = await admin
      .from("user_apple_credentials")
      .select("provider_refresh_token")
      .eq("user_id", userId)
      .maybeSingle();
    if (!data?.provider_refresh_token) return;

    const clientSecret = await buildAppleClientSecret(teamId, keyId, privateKey, clientId);
    const res = await fetch("https://appleid.apple.com/auth/revoke", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: clientId,
        client_secret: clientSecret,
        token: data.provider_refresh_token,
        token_type_hint: "refresh_token",
      }),
    });
    if (!res.ok) {
      console.error("[delete-account] Apple revoke responded", res.status, await res.text());
    }
  } catch (error) {
    console.error("[delete-account] Apple revocation failed (non-blocking):", error);
  }
}

async function buildAppleClientSecret(teamId: string, keyId: string, privateKeyPem: string, clientId: string): Promise<string> {
  const alg = "ES256";
  const header = { alg, kid: keyId };
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    iss: teamId,
    iat: now,
    exp: now + 300,
    aud: "https://appleid.apple.com",
    sub: clientId,
  };
  const enc = (obj: unknown) =>
    btoa(JSON.stringify(obj)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
  const unsigned = `${enc(header)}.${enc(payload)}`;

  const pemBody = privateKeyPem
    .replace(/-----BEGIN PRIVATE KEY-----/, "")
    .replace(/-----END PRIVATE KEY-----/, "")
    .replace(/\s/g, "");
  const keyData = Uint8Array.from(atob(pemBody), (c) => c.charCodeAt(0));
  const cryptoKey = await crypto.subtle.importKey(
    "pkcs8",
    keyData,
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"],
  );
  const signature = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    cryptoKey,
    new TextEncoder().encode(unsigned),
  );
  const sigB64 = btoa(String.fromCharCode(...new Uint8Array(signature)))
    .replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
  return `${unsigned}.${sigB64}`;
}

async function removeOwnedStorage(admin: SupabaseClient, userId: string) {
  for (const bucket of STORAGE_BUCKETS) {
    const paths: string[] = [];
    const collect = async (folder: string): Promise<void> => {
      let offset = 0;
      while (true) {
        const { data: entries, error } = await admin.storage.from(bucket).list(folder, { limit: 1000, offset });
        if (error) throw error;
        for (const entry of entries ?? []) {
          const path = `${folder}/${entry.name}`;
          if (entry.id) paths.push(path);
          else await collect(path);
        }
        if (!entries || entries.length < 1000) break;
        offset += entries.length;
      }
    };
    try {
      await collect(userId);
      for (let start = 0; start < paths.length; start += 1000) {
        const { error } = await admin.storage.from(bucket).remove(paths.slice(start, start + 1000));
        if (error) throw error;
      }
    } catch (error) {
      console.error(`[delete-account] Storage cleanup failed for bucket ${bucket}:`, error);
      throw error;
    }
  }
}

export async function checkAccountDeletionAvailability(): Promise<DeletionResult> {
  const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
  const admin = createClient(supabaseUrl, serviceKey);

  const { data: policyRow } = await admin
    .from("account_deletion_policy")
    .select("approved")
    .eq("id", true)
    .maybeSingle();
  const dbApproved = policyRow?.approved === true;
  // The database policy row is the approval of record. The environment flag is
  // an optional veto: when it is set to anything other than "true", deletion
  // stays unavailable even if the row is approved.
  const envFlag = Deno.env.get("ACCOUNT_DELETION_RETENTION_POLICY_APPROVED");
  const envApproved = envFlag === undefined || envFlag === "" || envFlag === "true";
  if (!dbApproved || !envApproved) {
    return { status: "unavailable", code: "ACCOUNT_DELETION_UNAVAILABLE" };
  }
  return { status: "available" };
}

export async function handleDeleteAccount(req: Request): Promise<DeletionResult> {
  const authHeader = req.headers.get("Authorization");
  if (!authHeader) return { status: "error", code: "NO_AUTH_HEADER", message: "Missing Authorization header." };

  const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
  const anonKey = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

  // Caller-scoped client: RLS + auth.uid() resolve to the real caller for the RPC.
  const callerClient = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
  });
  // Service-role client: policy check, Stripe lookups, Storage, Admin API.
  const admin = createClient(supabaseUrl, serviceKey);

  const { data: { user }, error: userError } = await callerClient.auth.getUser();
  if (userError || !user) {
    return { status: "error", code: "NOT_AUTHENTICATED", message: "Could not verify the calling session." };
  }

  const { data: policyRow } = await admin
    .from("account_deletion_policy")
    .select("approved")
    .eq("id", true)
    .maybeSingle();
  const dbApproved = policyRow?.approved === true;
  // The database policy row is the approval of record. The environment flag is
  // an optional veto: when it is set to anything other than "true", deletion
  // stays unavailable even if the row is approved.
  const envFlag = Deno.env.get("ACCOUNT_DELETION_RETENTION_POLICY_APPROVED");
  const envApproved = envFlag === undefined || envFlag === "" || envFlag === "true";
  if (!dbApproved || !envApproved) {
    return { status: "unavailable", code: "ACCOUNT_DELETION_UNAVAILABLE" };
  }

  try {
    // 1. Read what needs canceling/removing BEFORE any deletion.
    const [{ data: subRow }, { data: proRow }] = await Promise.all([
      admin.from("user_subscriptions").select("stripe_subscription_id").eq("user_id", user.id).maybeSingle(),
      admin.from("pro_providers").select("stripe_subscription_id").eq("user_id", user.id).maybeSingle(),
    ]);

    // 2. Cancel Stripe subscriptions.
    const stripe = stripeClient();
    if (stripe) {
      await cancelStripeSubscription(stripe, subRow?.stripe_subscription_id);
      await cancelStripeSubscription(stripe, proRow?.stripe_subscription_id);
    } else {
      console.warn("[delete-account] STRIPE_SECRET_KEY not configured; skipping subscription cancellation.");
    }

    // 3. Best-effort Apple token revocation (never blocks deletion).
    await revokeAppleTokenBestEffort(admin, user.id);

    // 4. Caller-scoped SQL cleanup (reviews, favorites, live sessions, business
    // detachment, audit-identity clearing — see the account_deletion migration).
    const { error: rpcError } = await callerClient.rpc("delete_own_account_data");
    if (rpcError) {
      return { status: "error", code: "CLEANUP_FAILED", message: rpcError.message };
    }

    // 5. Remove owned Storage objects (Storage API, never SQL deletion of metadata).
    await removeOwnedStorage(admin, user.id);

    // 6. Hard-delete the Auth identity. shouldSoftDelete=false per the approved design.
    const { error: deleteError } = await admin.auth.admin.deleteUser(user.id, false);
    if (deleteError) {
      return { status: "error", code: "AUTH_DELETE_FAILED", message: deleteError.message };
    }

    return { status: "deleted" };
  } catch (error) {
    // This is a multi-service operation, not an atomic cross-service transaction
    // (see docs/ACCOUNT_DELETION_READINESS.md). A failure here can mean Stripe was
    // canceled and/or SQL cleanup ran but the Auth identity still exists — never
    // claim a clean, fully-reversed state. Retrying is safe: each step tolerates
    // already-canceled/already-deleted resources.
    console.error("[delete-account] Failed:", error);
    return {
      status: "error",
      code: "DELETION_FAILED",
      message: "Account deletion did not finish. Some of your data or subscriptions may already be removed; please try again or contact support.",
    };
  }
}
