import React,{useEffect,useState,useRef} from 'react';
import {View,Text,TouchableOpacity,TextInput,StyleSheet,Modal,ScrollView,SafeAreaView,DeviceEventEmitter} from 'react-native';
import ContentSafetyActions,{CONTENT_SAFETY_CHANGED} from '../ContentSafetyActions';
import {useNavigation} from '@react-navigation/native';
import {useAuth} from '../../contexts/AuthContext';
import {useThemeContext} from '../../contexts/ThemeContext';
import {CruiseShip} from '../../lib/cruises/catalog';
import {PlaceEvidence} from '../../lib/placeEvidence';
import PlaceReviewGrid from '../PlaceReviewGrid';
import ReviewChoices from '../ReviewChoices';
import {buildPlaceReviewSummary} from '../../lib/placeReviewSummary';
import {CruiseReview,CruiseSignal,fetchCruiseEvidence,fetchCruiseReviews,fetchCruiseSignals,saveCruiseVisit} from '../../lib/cruises/reviews';
export default function CruiseReviewPanel({ship}:{ship:CruiseShip}){
 const [selectedTopic,setSelectedTopic]=useState<string|null>(null);
 const generation=useRef(0),pagination=useRef<number|null>(null);const[loadingMore,setLoadingMore]=useState(false);
 const navigation=useNavigation<any>(),{user}=useAuth(),{theme}=useThemeContext();const[evidence,setEvidence]=useState<PlaceEvidence|null>(null),[reviews,setReviews]=useState<CruiseReview[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const[open,setOpen]=useState(false),[signals,setSignals]=useState<CruiseSignal[]>([]),[selected,setSelected]=useState<Record<string,number>>({}),[date,setDate]=useState(''),[cabin,setCabin]=useState(''),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[message,setMessage]=useState('');
 const text={color:theme.text},muted={color:theme.textSecondary},panel={backgroundColor:theme.surface,borderColor:theme.border};
 useEffect(()=>{const request=++generation.current;let active=true;pagination.current=null;setLoadingMore(false);setLoading(true);setError('');setReviews([]);setTotal(0);void Promise.all([fetchCruiseEvidence(ship.universe_id),fetchCruiseReviews(ship.universe_id)]).then(([next,feed])=>{if(active&&request===generation.current){setEvidence(next);setReviews(feed.reviews);setTotal(feed.total)}}).catch(e=>{if(active&&request===generation.current)setError(e.message)}).finally(()=>{if(active&&request===generation.current)setLoading(false)});return()=>{active=false;++generation.current}},[ship.universe_id,refresh,user?.id]);
 useEffect(()=>{const listener=DeviceEventEmitter.addListener(CONTENT_SAFETY_CHANGED,()=>{++generation.current;setReviews([]);setTotal(0);setRefresh(v=>v+1)});return()=>listener.remove()},[]);
 const formGeneration=useRef(0),saveLock=useRef(false);
 useEffect(()=>{formGeneration.current++;saveLock.current=false;setOpen(false);setSignals([]);setSelected({});setDate('');setCabin('');setNote('');setSaving(false);setFormError('');setMessage('');setSelectedTopic(null);return()=>{formGeneration.current++}},[ship.universe_id,user?.id]);
 const start=async()=>{if(!user){navigation.navigate('Login');return;}const request=formGeneration.current;setOpen(true);setFormError('');try{const catalog=await fetchCruiseSignals();if(request===formGeneration.current)setSignals(catalog)}catch(e){if(request===formGeneration.current)setFormError((e as Error).message)}};
 const save=async()=>{if(saveLock.current)return;saveLock.current=true;const request=formGeneration.current;setSaving(true);setFormError('');try{await saveCruiseVisit({universeId:ship.universe_id,sailingDate:date,signals:Object.entries(selected).map(([signalId,intensity])=>({signalId,intensity})),publicNote:note,cabinCategoryId:cabin||null});if(request!==formGeneration.current)return;setSelected({});setNote('');setDate('');setCabin('');setMessage('Your experience has been saved.');setOpen(false);setRefresh(v=>v+1)}catch(e){if(request===formGeneration.current)setFormError((e as Error).message)}finally{if(request===formGeneration.current){saveLock.current=false;setSaving(false)}}};
 const button=(label:string,action:()=>void,disabled=false)=><TouchableOpacity accessibilityRole="button" disabled={disabled} onPress={action} style={[styles.button,panel,{opacity:disabled ? 0.5 : 1}]}><Text style={text}>{label}</Text></TouchableOpacity>;
 const visibleReviews=reviews.filter(review=>!selectedTopic||review.signals?.some(signal=>signal.label===selectedTopic));
 return <View style={{gap:14}}><Text style={[styles.heading,text]}>What guests experienced</Text><Text style={muted}>Reports describe a sailing, not every trip this ship makes.</Text>{ship.operating_status==='operating'&&button('Add your taps',()=>void start())}{!!message&&<Text accessibilityRole="alert" style={text}>{message}</Text>}{loading?<Text style={muted}>Loading guest reports…</Text>:error||evidence?.dataStatus==='unavailable'?<View><Text accessibilityRole="alert" style={text}>{error||evidence?.unavailableReason}</Text>{button('Retry guest reports',()=>setRefresh(v=>v+1))}</View>:<><PlaceReviewGrid mode="full" summary={buildPlaceReviewSummary(evidence,'cruise_ship')} selectedTopic={selectedTopic} onSelect={(_section,topic)=>setSelectedTopic(topic.label)}/>{selectedTopic&&button('All experiences · '+selectedTopic+' ×',()=>setSelectedTopic(null))}<Text style={[styles.heading,text]}>Recent guest reports</Text>{visibleReviews.map(review=><View key={review.id} style={[styles.review,{borderColor:theme.border}]}><Text style={[styles.small,muted]}>Sailing date: {review.sailing_date} · reported by the guest{review.cabin_category_name?` · ${review.cabin_category_name}`:''}</Text><View style={styles.tags}>{review.signals?.map(s=><Text key={s.label} style={[styles.tag,text,panel]}>{s.label}{s.intensity>1?` · emphasis ${s.intensity}/3`:''}</Text>)}</View>{review.public_note&&<Text style={text}>{review.public_note}</Text>}<ContentSafetyActions kind="cruise_visit" contentId={review.id}/></View>)}{!visibleReviews.length&&<Text style={muted}>{selectedTopic?'No matching experiences in the loaded reports. Load more reports or choose All experiences.':'No guest reports to show.'}</Text>}{reviews.length<total&&button(loadingMore?'Loading reports…':'Load more reports',()=>{const request=generation.current;if(pagination.current===request)return;pagination.current=request;setLoadingMore(true);void fetchCruiseReviews(ship.universe_id,reviews.length).then(more=>{if(request!==generation.current)return;setReviews(current=>[...current,...more.reviews]);setTotal(more.total)}).catch(e=>{if(request===generation.current)setError(e.message)}).finally(()=>{if(request===generation.current){pagination.current=null;setLoadingMore(false)}})})}</>}
 <Modal visible={open} animationType="slide" onRequestClose={()=>{if(!saving)setOpen(false)}}><SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,gap:16}}><Text style={[styles.heading,text]}>Share your ship experience</Text><Text style={muted}>Describe your own sailing. For a specific restaurant or shop, use that venue’s page.</Text><Text style={text}>Sailing date (YYYY-MM-DD)</Text><TextInput accessibilityLabel="Sailing date" placeholder="YYYY-MM-DD" placeholderTextColor={theme.textSecondary} value={date} onChangeText={setDate} maxLength={10} keyboardType="numbers-and-punctuation" style={[styles.input,text,panel]}/>{ship.cabin_categories.length>0&&<><Text style={text}>Cabin category (optional)</Text><View style={styles.tags}>{[{id:'',name:'Prefer not to say'},...ship.cabin_categories].map(c=><TouchableOpacity key={c.id} accessibilityRole="button" accessibilityState={{selected:cabin===c.id}} onPress={()=>setCabin(c.id)} style={[styles.button,panel,cabin===c.id&&{borderColor:theme.primary}]}><Text style={text}>{c.name}</Text></TouchableOpacity>)}</View></>}<ReviewChoices signals={signals} subject="cruise_ship" selected={selected} onChange={setSelected} disabled={saving} maxSelections={30}/><Text style={text}>Public note (optional)</Text><TextInput accessibilityLabel="Public note" multiline maxLength={4000} value={note} onChangeText={setNote} style={[styles.input,text,panel,{minHeight:110,textAlignVertical:'top'}]}/><Text style={[styles.small,muted]}>Do not include your cabin number or current whereabouts. Updating a report for the same sailing date preserves its issue history.</Text>{!!formError&&<Text accessibilityRole="alert" style={text}>{formError}</Text>}</ScrollView><View style={{paddingHorizontal:20,paddingVertical:12,gap:8,borderTopWidth:1,borderColor:theme.border}}>{button(saving?'Saving…':'Save experience',()=>void save(),saving||!date||!Object.keys(selected).length)}{button('Cancel',()=>setOpen(false),saving)}</View></SafeAreaView></Modal></View>;
}
const styles=StyleSheet.create({heading:{fontSize:22,fontWeight:'700'},label:{fontSize:13,marginBottom:12},signal:{fontSize:16,fontWeight:'600'},small:{fontSize:12,lineHeight:19},button:{padding:12,minHeight:44,borderWidth:1,borderRadius:12,justifyContent:'center'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},cell:{width:'48%',flexGrow:1,borderWidth:1,borderRadius:16,padding:14,gap:8},review:{borderBottomWidth:1,paddingVertical:14,gap:10},tags:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{fontSize:12,borderWidth:1,borderRadius:20,padding:8},input:{borderWidth:1,borderRadius:12,padding:12,minHeight:46}});
