import {visibleCruisePhoto} from '../../lib/cruises/catalog';
import React,{useEffect,useState,useRef} from 'react';
import {View,Text,TouchableOpacity,ScrollView,SafeAreaView,Image,TextInput,StyleSheet,Keyboard,Modal,KeyboardAvoidingView,Platform,AccessibilityInfo,findNodeHandle} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {Ionicons} from '@expo/vector-icons';
import {useThemeContext} from '../../contexts/ThemeContext';
import {CruiseShipDetail} from '../../lib/cruises/catalog';
import {searchCruiseShips,getCruiseOperators,getFeaturedCruiseShips,CruiseOperator} from '../../lib/cruises/service';
import {CruiseDirectoryFilters,EMPTY_CRUISE_FILTERS} from '../../lib/cruises/directoryState';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {cruiseLineBrand,cruiseLineInitials,orderedCruiseLines} from '../../lib/cruises/lineBrands';
import {CRUISE_LINE_LOGOS} from '../../lib/cruises/lineLogoAssets';
import ToolHeader from '../ToolHeader';
export default function CruiseDirectory({onBack}:{onBack:()=>void}) {
 const navigation=useNavigation<any>(),{theme}=useThemeContext();
 const [filters,setFilters]=useState<CruiseDirectoryFilters>(EMPTY_CRUISE_FILTERS),[rows,setRows]=useState<CruiseShipDetail[]>([]),[featured,setFeatured]=useState<CruiseShipDetail[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[featuredError,setFeaturedError]=useState(''),[more,setMore]=useState(false),[offset,setOffset]=useState(0),[retry,setRetry]=useState(0);
 const [operators,setOperators]=useState<CruiseOperator[]>([]),[operatorError,setOperatorError]=useState(''),[operatorLoading,setOperatorLoading]=useState(true),[companyOpen,setCompanyOpen]=useState(false),[companyQuery,setCompanyQuery]=useState('');
 const [draft,setDraft]=useState<CruiseDirectoryFilters>(EMPTY_CRUISE_FILTERS),[failedLogos,setFailedLogos]=useState<Record<string,boolean>>({});
 const insets=useSafeAreaInsets(),filterButton=useRef<any>(null),filterTitle=useRef<any>(null),lineStrip=useRef<ScrollView>(null);
 const {query,kind,status,operatorId,length,year,audience}=filters;
 useEffect(()=>{if(operatorId){const index=orderedCruiseLines(operators).findIndex(item=>item.id===operatorId);if(index>=0)lineStrip.current?.scrollTo({x:(index+1)*102,animated:false})}},[operatorId,operators]);
 useEffect(()=>{let active=true;setOperatorLoading(true);setOperatorError('');getCruiseOperators().then(value=>{if(active)setOperators(value)}).catch(e=>{if(active)setOperatorError(e.message)}).finally(()=>{if(active)setOperatorLoading(false)});return()=>{active=false}},[retry]);
 useEffect(()=>{let active=true;setLoading(true);setError('');const timer=setTimeout(()=>void searchCruiseShips({query,kind:kind||undefined,status,operatorId,length,year,audience,offset}).then(result=>{if(active){setRows(old=>offset?[...old.slice(0,offset),...result.ships]:result.ships);setMore(result.hasMore)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)}),200);return()=>{active=false;clearTimeout(timer)}},[query,kind,status,operatorId,length,year,audience,offset,retry]);
 useEffect(()=>{let active=true;setFeatured([]);setFeaturedError('');getFeaturedCruiseShips({query,kind:kind||undefined,status,operatorId,length,year,audience}).then(value=>{if(active)setFeatured(value)}).catch(e=>{if(active)setFeaturedError(e.message)});return()=>{active=false}},[query,kind,status,operatorId,length,year,audience,retry]);
 const change=(next:Partial<CruiseDirectoryFilters>)=>{const value={...filters,...next};if(value.query===query&&value.kind===kind&&value.status===status&&value.operatorId===operatorId&&value.length===length&&value.year===year&&value.audience===audience)return;setRows([]);setFeatured([]);setOffset(0);setMore(false);setFilters(value)};
 const focus=(ref:React.RefObject<any>)=>{const node=findNodeHandle(ref.current);if(node)AccessibilityInfo.setAccessibilityFocus(node)};
 const openFilters=()=>{Keyboard.dismiss();setDraft({...filters});setCompanyQuery('');setCompanyOpen(true)};
 const closeFilters=()=>{Keyboard.dismiss();setCompanyOpen(false);focus(filterButton)};
 const applyFilters=()=>{change({kind:draft.kind,status:draft.status,operatorId:draft.operatorId,length:draft.length,year:draft.year,audience:draft.audience});closeFilters()};
 const selectedCompany=operators.find(item=>item.id===operatorId)?.name||'Selected cruise line';
 const chips=[...(operatorId?[{key:'operatorId',label:selectedCompany,clear:{operatorId:''}}]:[]),...(kind?[{key:'kind',label:kind.charAt(0).toUpperCase()+kind.slice(1),clear:{kind:'' as const}}]:[]),...(status==='announced'?[{key:'status',label:'Announced ships',clear:{status:'operating' as const}}]:[]),...(length?[{key:'length',label:({under150:'Under 150 m','150to250':'150–250 m',over250:'Over 250 m'} as const)[length],clear:{length:'' as const}}]:[]),...(year?[{key:'year',label:({'2020plus':'Built 2020 or newer','2010s':'Built 2010–2019',before2010:'Built before 2010'} as const)[year],clear:{year:'' as const}}]:[]),...(audience?[{key:'audience',label:audience==='adults_only'?'Adults only (18+)':'Family activities',clear:{audience:'' as const}}]:[]),...(query?[{key:'query',label:`Search: ${query}`,clear:{query:''}}]:[])];
 const optionCount=Number(!!kind)+Number(status==='announced')+Number(!!operatorId)+Number(!!length)+Number(!!year)+Number(!!audience);
 const text={color:theme.text},muted={color:theme.textSecondary},panel={backgroundColor:theme.surface,borderColor:theme.border};
 const button=(label:string,onPress:()=>void,selected=false)=><TouchableOpacity accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[styles.button,panel,selected&&{borderColor:theme.primary,borderWidth:2}]}><Text style={[text,selected&&{fontWeight:'700'}]}>{label}</Text></TouchableOpacity>;
 const renderShip=({ship}:CruiseShipDetail,compact=false)=>{const image=visibleCruisePhoto(ship);return <TouchableOpacity key={ship.id} accessibilityRole="button" onPress={()=>navigation.navigate('UniverseLanding',{universeId:ship.universe_id})} style={[styles.card,{borderColor:theme.border},compact&&styles.compact]}>{image?<Image source={{uri:image.url}} accessibilityLabel={image.alt} style={[styles.photo,compact&&styles.compactPhoto]}/>:<View style={[styles.photo,styles.placeholder,{backgroundColor:theme.surface},compact&&styles.compactPhoto]} accessibilityLabel="No ship photo"><Ionicons name="boat-outline" size={36} color={theme.textSecondary}/></View>}<View style={{flex:1,gap:7}}><Text style={[styles.small,muted]}>{ship.operator_name} · {ship.kind}</Text><Text style={[styles.shipTitle,text]}>{ship.name}</Text><Text style={[styles.small,muted]}>{ship.operating_status==='announced'?'Announced · not operating':'Explore this ship'} →</Text></View></TouchableOpacity>;};
 return <SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ToolHeader title="Cruises" onBack={onBack}/><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={{paddingHorizontal:20,paddingBottom:100,gap:16,width:'100%',maxWidth:1040,alignSelf:'center'}}><Text accessibilityRole="header" style={[styles.heading,text]}>Find your next ship</Text>
 <View style={styles.searchRow}><TextInput accessibilityLabel="Search ship or cruise line" placeholder="Ship or cruise line" placeholderTextColor={theme.textSecondary} maxLength={160} value={query} onChangeText={value=>change({query:value})} style={[styles.input,text,panel,{flex:1,minWidth:0}]}/><TouchableOpacity ref={filterButton} accessibilityRole="button" accessibilityLabel={`Filters${optionCount?`, ${optionCount} active`:''}`} accessibilityState={{expanded:companyOpen}} onPress={openFilters} style={[styles.button,styles.filterToggle,panel]}><Ionicons name="options-outline" size={20} color={theme.text}/><Text style={text}>Filters{optionCount?` (${optionCount})`:''}</Text></TouchableOpacity></View>
 <ScrollView ref={lineStrip} horizontal accessibilityLabel="Cruise line filters" showsHorizontalScrollIndicator contentContainerStyle={{gap:8,paddingVertical:6,paddingHorizontal:3}}>
 <TouchableOpacity accessibilityRole="button" accessibilityLabel="All lines" accessibilityState={{selected:!operatorId}} onPress={()=>change({operatorId:''})} style={styles.lineOption}><View style={[styles.lineMark,panel,!operatorId&&{borderColor:theme.primary,borderWidth:3}]}><Ionicons name="boat-outline" size={28} color={theme.text}/></View><Text style={[styles.lineLabel,text]}>All lines</Text></TouchableOpacity>
 {orderedCruiseLines(operators).map(item=>{const brand=cruiseLineBrand(item.id);return <TouchableOpacity key={item.id} accessibilityRole="button" accessibilityLabel={item.name} accessibilityState={{selected:operatorId===item.id}} onPress={()=>change({operatorId:item.id})} style={styles.lineOption}><View style={[styles.lineMark,panel,brand&&!failedLogos[item.id]&&{backgroundColor:brand.background},operatorId===item.id&&{borderColor:theme.primary,borderWidth:3}]}>{brand&&!failedLogos[item.id]?<Image source={CRUISE_LINE_LOGOS[item.id]} accessible={false} resizeMode="contain" style={{width:52,height:40}} onError={()=>setFailedLogos(old=>({...old,[item.id]:true}))}/>:<Text style={[text,{fontSize:22,fontWeight:'600'}]}>{cruiseLineInitials(item.name)}</Text>}</View><Text style={[styles.lineLabel,text,operatorId===item.id&&{fontWeight:'700'}]}>{item.name}</Text></TouchableOpacity>})}</ScrollView>
 {operatorLoading&&<Text style={[styles.small,muted]}>Loading cruise lines…</Text>}{!!operatorError&&<View style={{gap:8}}><Text accessibilityRole="alert" style={text}>Cruise lines are temporarily unavailable.</Text>{button('Try again',()=>setRetry(v=>v+1))}</View>}
 {chips.length>0&&<View accessibilityLabel="Active filters" style={styles.choices}>{chips.map(chip=><TouchableOpacity key={chip.key} accessibilityRole="button" accessibilityLabel={`Remove ${chip.label} filter`} onPress={()=>change(chip.clear)} style={[styles.button,styles.chip,panel]}><Text style={[text,{flexShrink:1}]}>{chip.label}</Text><Ionicons name="close-outline" color={theme.text} size={18}/></TouchableOpacity>)}{button('Clear all',()=>change(EMPTY_CRUISE_FILTERS))}</View>}
 {!query.trim()&&featured.length>0&&<View style={{gap:10}}><Text accessibilityRole="header" style={[styles.title,text]}>Featured ships</Text><Text style={muted}>Selected by Tavvy.</Text><ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={{gap:12,paddingBottom:8}}>{featured.map(item=>renderShip(item,true))}</ScrollView></View>}{!!featuredError&&!query.trim()&&<View style={{gap:8}}><Text style={muted}>Featured ships are temporarily unavailable.</Text>{button('Try again',()=>setRetry(v=>v+1))}</View>}
 <Text accessibilityRole="header" style={[styles.title,text]}>Explore ships</Text>{error?<View style={{gap:12}}><Text accessibilityRole="alert" style={text}>{error}</Text>{button('Try again',()=>setRetry(v=>v+1))}</View>:rows.map(item=>renderShip(item))}{loading&&<Text style={muted}>Loading ships…</Text>}{!loading&&!error&&!rows.length&&<Text style={muted}>No verified ships match these filters. Try changing a length, year, audience or cruise line choice.</Text>}{more&&!loading&&!error&&button('Load more ships',()=>setOffset(rows.length))}
 </ScrollView>
 {companyOpen&&<Modal transparent visible animationType="slide" onRequestClose={closeFilters} onShow={()=>focus(filterTitle)}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={[styles.modal,{paddingLeft:insets.left,paddingRight:insets.right,paddingTop:insets.top}]}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Close filters" onPress={closeFilters} style={StyleSheet.absoluteFill}/><View accessibilityViewIsModal onAccessibilityEscape={closeFilters} style={[styles.sheet,panel,{paddingBottom:Math.max(insets.bottom,16)}]}><View style={styles.sheetHeader}><Text ref={filterTitle} accessible accessibilityRole="header" style={[styles.title,text]}>Filters</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Close filters" onPress={closeFilters} style={styles.close}><Ionicons name="close-outline" size={26} color={theme.text}/></TouchableOpacity></View>
 <ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={{gap:22,padding:20}}><View style={{gap:12}}><Text style={[text,styles.legend]}>Cruise type</Text><View style={styles.choices}>{([['','All types'],['ocean','Ocean'],['river','River'],['expedition','Expedition']] as const).map(([id,label])=><React.Fragment key={id}>{button(label,()=>setDraft(old=>({...old,kind:id})),draft.kind===id)}</React.Fragment>)}</View></View><View style={{gap:12}}><Text style={[text,styles.legend]}>Ship status</Text><View style={styles.choices}>{(['operating','announced'] as const).map(value=><React.Fragment key={value}>{button(value==='operating'?'Operating ships':'Announced ships',()=>setDraft(old=>({...old,status:value})),draft.status===value)}</React.Fragment>)}</View></View>
 <View style={{gap:10}}><Text style={[text,styles.legend]}>Ship length</Text><Text style={muted}>Sourced ship length, not trip duration.</Text><View style={styles.choices}>{([['','Any length'],['under150','Under 150 m'],['150to250','150–250 m'],['over250','Over 250 m']] as const).map(([value,label])=><React.Fragment key={value}>{button(label,()=>setDraft(old=>({...old,length:value})),draft.length===value)}</React.Fragment>)}</View></View>
 <View style={{gap:10}}><Text style={[text,styles.legend]}>Year built</Text><View style={styles.choices}>{([['','Any year'],['2020plus','2020 or newer'],['2010s','2010–2019'],['before2010','Before 2010']] as const).map(([value,label])=><React.Fragment key={value}>{button(label,()=>setDraft(old=>({...old,year:value})),draft.year===value)}</React.Fragment>)}</View></View>
 <View style={{gap:10}}><Text style={[text,styles.legend]}>Who is it for?</Text><Text style={muted}>Family activities means an official youth program. Adults only means an official 18+ policy. These are not guest ratings.</Text><View style={styles.choices}>{([['','Any guests'],['family_activities','Family activities'],['adults_only','Adults only (18+)']] as const).map(([value,label])=><React.Fragment key={value}>{button(label,()=>setDraft(old=>({...old,audience:value})),draft.audience===value)}</React.Fragment>)}</View></View>
 <View style={{gap:10}}><Text style={[text,styles.legend]}>Cruise line</Text><TextInput accessibilityLabel="Search cruise lines" placeholder="Find any cruise line" placeholderTextColor={theme.textSecondary} value={companyQuery} onChangeText={setCompanyQuery} autoCorrect={false} style={[styles.input,text,panel]}/>{button('All cruise lines',()=>setDraft(old=>({...old,operatorId:''})),!draft.operatorId)}{operators.filter(item=>item.name.toLocaleLowerCase().includes(companyQuery.trim().toLocaleLowerCase())).map(item=><React.Fragment key={item.id}>{button(item.name,()=>setDraft(old=>({...old,operatorId:item.id})),draft.operatorId===item.id)}</React.Fragment>)}{operatorLoading&&<Text style={muted}>Loading cruise lines…</Text>}{!!operatorError&&<Text accessibilityRole="alert" style={text}>Cruise lines are temporarily unavailable.</Text>}{!operatorLoading&&!operatorError&&!operators.some(item=>item.name.toLocaleLowerCase().includes(companyQuery.trim().toLocaleLowerCase()))&&<Text style={muted}>No cruise lines match your search.</Text>}</View></ScrollView>
 <View style={[styles.sheetFooter,{borderColor:theme.border}]}>{button('Reset filters',()=>{setDraft({...EMPTY_CRUISE_FILTERS,query});setCompanyQuery('')})}<TouchableOpacity accessibilityRole="button" onPress={applyFilters} style={[styles.button,{backgroundColor:theme.text,flex:1}]}><Text style={{color:theme.background,textAlign:'center',fontWeight:'700'}}>Apply filters</Text></TouchableOpacity></View></View></KeyboardAvoidingView></Modal>}
 </SafeAreaView>;
}
const styles=StyleSheet.create({heading:{fontSize:28,fontWeight:'700',marginTop:18},title:{fontSize:22,fontWeight:'600'},shipTitle:{fontSize:18,fontWeight:'600'},small:{fontSize:12,lineHeight:18},button:{borderWidth:1,borderRadius:12,padding:12,minHeight:44,justifyContent:'center'},input:{borderWidth:1,borderRadius:12,padding:12,minHeight:48,fontSize:16},searchRow:{flexDirection:'row',gap:10},filterToggle:{flexDirection:'row',alignItems:'center',gap:6},lineOption:{width:94,alignItems:'center',gap:8,paddingVertical:3},lineMark:{width:72,height:62,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},lineLabel:{fontSize:12,textAlign:'center',lineHeight:17},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{flexDirection:'row',alignItems:'center',gap:6,borderRadius:24,maxWidth:'100%'},card:{borderBottomWidth:1,paddingVertical:14,flexDirection:'row',alignItems:'center',gap:14},photo:{width:100,height:90,borderRadius:12},placeholder:{justifyContent:'center',alignItems:'center'},compact:{width:268,borderWidth:1,borderRadius:16,padding:12},compactPhoto:{width:70,height:80},modal:{flex:1,backgroundColor:'rgba(0,0,0,.48)',justifyContent:'flex-end',alignItems:'center'},sheet:{width:'100%',maxWidth:640,maxHeight:'88%',borderTopLeftRadius:24,borderTopRightRadius:24,overflow:'hidden'},sheetHeader:{paddingHorizontal:20,paddingVertical:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},close:{minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'},legend:{fontWeight:'700',fontSize:16},sheetFooter:{borderTopWidth:1,padding:16,flexDirection:'row',gap:12}});
