import React,{useEffect,useState,useRef} from 'react';
import {View,Text,TouchableOpacity,TextInput,StyleSheet,Modal,ScrollView,SafeAreaView,DeviceEventEmitter} from 'react-native';
import ContentSafetyActions,{CONTENT_SAFETY_CHANGED} from '../ContentSafetyActions';
import {useNavigation} from '@react-navigation/native';
import {useAuth} from '../../contexts/AuthContext';
import {useThemeContext} from '../../contexts/ThemeContext';
import {CruiseShip} from '../../lib/cruises/catalog';
import {PlaceEvidence,isCurrentWarning} from '../../lib/placeEvidence';
import {CruiseReview,CruiseSignal,fetchCruiseEvidence,fetchCruiseReviews,fetchCruiseSignals,saveCruiseVisit} from '../../lib/cruises/reviews';
export default function CruiseReviewPanel({ship}:{ship:CruiseShip}){
 const generation=useRef(0);
 const navigation=useNavigation<any>(),{user}=useAuth(),{theme}=useThemeContext();const[evidence,setEvidence]=useState<PlaceEvidence|null>(null),[reviews,setReviews]=useState<CruiseReview[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[expanded,setExpanded]=useState('');
 const[open,setOpen]=useState(false),[signals,setSignals]=useState<CruiseSignal[]>([]),[selected,setSelected]=useState<Record<string,number>>({}),[date,setDate]=useState(''),[cabin,setCabin]=useState(''),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[message,setMessage]=useState('');
 const text={color:theme.text},muted={color:theme.textSecondary},panel={backgroundColor:theme.surface,borderColor:theme.border};
 useEffect(()=>{const request=++generation.current;let active=true;setLoading(true);setError('');setReviews([]);setTotal(0);void Promise.all([fetchCruiseEvidence(ship.universe_id),fetchCruiseReviews(ship.universe_id)]).then(([next,feed])=>{if(active&&request===generation.current){setEvidence(next);setReviews(feed.reviews);setTotal(feed.total)}}).catch(e=>{if(active&&request===generation.current)setError(e.message)}).finally(()=>{if(active&&request===generation.current)setLoading(false)});return()=>{active=false;++generation.current}},[ship.universe_id,refresh,user?.id]);
 useEffect(()=>{const listener=DeviceEventEmitter.addListener(CONTENT_SAFETY_CHANGED,()=>{++generation.current;setReviews([]);setTotal(0);setRefresh(v=>v+1)});return()=>listener.remove()},[]);
 const start=async()=>{if(!user){navigation.navigate('Login');return;}setOpen(true);setFormError('');try{setSignals(await fetchCruiseSignals())}catch(e){setFormError((e as Error).message)}};
 const save=async()=>{if(saving)return;setSaving(true);setFormError('');try{await saveCruiseVisit({universeId:ship.universe_id,sailingDate:date,signals:Object.entries(selected).map(([signalId,intensity])=>({signalId,intensity})),publicNote:note,cabinCategoryId:cabin||null});setMessage('Your experience has been saved.');setOpen(false);setRefresh(v=>v+1)}catch(e){setFormError((e as Error).message)}finally{setSaving(false)}};
 const button=(label:string,action:()=>void,disabled=false)=><TouchableOpacity accessibilityRole="button" disabled={disabled} onPress={action} style={[styles.button,panel,{opacity:disabled ? 0.5 : 1}]}><Text style={text}>{label}</Text></TouchableOpacity>;
 const cells=evidence?[{id:'main',name:'The onboard experience',items:[...evidence.coreSignals,...evidence.coreConcerns.map(item=>({...item,label:'Concern: '+item.label}))]},{id:'good',name:'The Good',items:evidence.goodSignals.filter(s=>!evidence.coreSignals.some(c=>c.label===s.label))},{id:'vibe',name:'The Vibe',items:evidence.vibeSignals},{id:'heads',name:'Heads Up',items:evidence.warnings.filter(isCurrentWarning)}]:[];
 return <View style={{gap:14}}><Text style={[styles.heading,text]}>What guests experienced</Text><Text style={muted}>Reports describe a sailing, not every trip this ship makes.</Text>{ship.operating_status==='operating'&&button('Add your taps',()=>void start())}{!!message&&<Text accessibilityRole="alert" style={text}>{message}</Text>}{loading?<Text style={muted}>Loading guest reports…</Text>:error||evidence?.dataStatus==='unavailable'?<View><Text accessibilityRole="alert" style={text}>{error||evidence?.unavailableReason}</Text>{button('Retry guest reports',()=>setRefresh(v=>v+1))}</View>:<><View style={styles.grid}>{cells.map(cell=><TouchableOpacity key={cell.id} accessibilityRole="button" accessibilityState={{expanded:expanded===cell.id}} onPress={()=>setExpanded(expanded===cell.id?'':cell.id)} style={[styles.cell,panel]}><Text style={[styles.label,muted]}>{cell.name}</Text><Text style={[styles.signal,text]}>{cell.items[0]?.label||'No reports yet'}</Text><Text style={[styles.small,muted]}>{cell.items[0]?`${cell.items[0].reports} guests`:'Be the first to share your experience'}</Text>{expanded===cell.id&&cell.items.slice(1).map(item=><Text key={item.label} style={text}>{item.label} · {item.reports} guests</Text>)}</TouchableOpacity>)}</View><Text style={[styles.small,muted]}>{evidence?.recentReviewers||0} distinct guest{evidence?.recentReviewers===1?'':'s'} in the last 6 months. Older concerns remain in history; fewer recent mentions do not prove a repair.</Text><Text style={[styles.heading,text]}>Recent guest reports</Text>{reviews.map(review=><View key={review.id} style={[styles.review,{borderColor:theme.border}]}><Text style={[styles.small,muted]}>Sailing date: {review.sailing_date} · reported by the guest{review.cabin_category_name?` · ${review.cabin_category_name}`:''}</Text><View style={styles.tags}>{review.signals?.map(s=><Text key={s.label} style={[styles.tag,text,panel]}>{s.label}{s.intensity>1?` · ${s.intensity} taps`:''}</Text>)}</View>{review.public_note&&<Text style={text}>{review.public_note}</Text>}<ContentSafetyActions kind="cruise_visit" contentId={review.id}/></View>)}{!reviews.length&&<Text style={muted}>No guest reports to show.</Text>}{reviews.length<total&&button('Load more reports',()=>{const request=generation.current;void fetchCruiseReviews(ship.universe_id,reviews.length).then(more=>{if(request!==generation.current)return;setReviews(current=>[...current,...more.reviews]);setTotal(more.total)}).catch(e=>{if(request===generation.current)setError(e.message)})})}</>}
 <Modal visible={open} animationType="slide" onRequestClose={()=>{if(!saving)setOpen(false)}}><SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,gap:16}}><Text style={[styles.heading,text]}>Share your ship experience</Text><Text style={muted}>Describe your own sailing. For a specific restaurant or shop, use that venue’s page.</Text><Text style={text}>Sailing date (YYYY-MM-DD)</Text><TextInput accessibilityLabel="Sailing date" placeholder="YYYY-MM-DD" placeholderTextColor={theme.textSecondary} value={date} onChangeText={setDate} maxLength={10} keyboardType="numbers-and-punctuation" style={[styles.input,text,panel]}/>{ship.cabin_categories.length>0&&<><Text style={text}>Cabin category (optional)</Text><View style={styles.tags}>{[{id:'',name:'Prefer not to say'},...ship.cabin_categories].map(c=><TouchableOpacity key={c.id} accessibilityRole="button" accessibilityState={{selected:cabin===c.id}} onPress={()=>setCabin(c.id)} style={[styles.button,panel,cabin===c.id&&{borderColor:theme.primary}]}><Text style={text}>{c.name}</Text></TouchableOpacity>)}</View></>}{(['best_for','vibe','heads_up'] as const).map(group=><View key={group} style={{gap:10}}><Text style={[styles.signal,text]}>{group==='best_for'?'The Good':group==='vibe'?'The Vibe':'Heads Up'}</Text><View style={styles.tags}>{signals.filter(s=>s.signal_type===group).map(signal=><View key={signal.id} style={{gap:4}}><TouchableOpacity accessibilityRole="button" accessibilityState={{selected:!!selected[signal.id]}} onPress={()=>setSelected(current=>{const next={...current};if(next[signal.id])delete next[signal.id];else next[signal.id]=1;return next})} style={[styles.button,panel,!!selected[signal.id]&&{borderColor:theme.primary}]}><Text style={text}>{signal.label}</Text></TouchableOpacity>{!!selected[signal.id]&&<View style={styles.tags}>{[1,2,3].map(n=><TouchableOpacity key={n} accessibilityLabel={`${signal.label}: ${n} taps`} accessibilityState={{selected:selected[signal.id]===n}} onPress={()=>setSelected(current=>({...current,[signal.id]:n}))} style={[styles.button,panel,selected[signal.id]===n&&{borderColor:theme.primary}]}><Text style={text}>{n}</Text></TouchableOpacity>)}</View>}</View>)}</View></View>)}<Text style={text}>Public note (optional)</Text><TextInput accessibilityLabel="Public note" multiline maxLength={4000} value={note} onChangeText={setNote} style={[styles.input,text,panel,{minHeight:110,textAlignVertical:'top'}]}/><Text style={[styles.small,muted]}>Do not include your cabin number or current whereabouts. Updating a report for the same sailing date preserves its issue history.</Text>{!!formError&&<Text accessibilityRole="alert" style={text}>{formError}</Text>}{button(saving?'Saving…':'Save experience',()=>void save(),saving||!date||!Object.keys(selected).length)}{button('Cancel',()=>setOpen(false),saving)}</ScrollView></SafeAreaView></Modal></View>;
}
const styles=StyleSheet.create({heading:{fontSize:22,fontWeight:'700'},label:{fontSize:13,marginBottom:12},signal:{fontSize:16,fontWeight:'600'},small:{fontSize:12,lineHeight:19},button:{padding:12,minHeight:44,borderWidth:1,borderRadius:12,justifyContent:'center'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},cell:{width:'48%',flexGrow:1,borderWidth:1,borderRadius:16,padding:14,gap:8},review:{borderBottomWidth:1,paddingVertical:14,gap:10},tags:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{fontSize:12,borderWidth:1,borderRadius:20,padding:8},input:{borderWidth:1,borderRadius:12,padding:12,minHeight:46}});
