import React,{useEffect,useState} from 'react';
import {View,Text,TouchableOpacity,ScrollView,SafeAreaView,Image,TextInput,StyleSheet,Keyboard} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {Ionicons} from '@expo/vector-icons';
import {useThemeContext} from '../../contexts/ThemeContext';
import {CruiseShipDetail,safeCruiseUrl} from '../../lib/cruises/catalog';
import {searchCruiseShips,getCruiseOperators,getFeaturedCruiseShips,CruiseOperator} from '../../lib/cruises/service';
import {CruiseDirectoryFilters,EMPTY_CRUISE_FILTERS} from '../../lib/cruises/directoryState';
import ToolHeader from '../ToolHeader';
export default function CruiseDirectory({onBack}:{onBack:()=>void}) {
 const navigation=useNavigation<any>(),{theme}=useThemeContext();
 const [filters,setFilters]=useState<CruiseDirectoryFilters>(EMPTY_CRUISE_FILTERS),[rows,setRows]=useState<CruiseShipDetail[]>([]),[featured,setFeatured]=useState<CruiseShipDetail[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[featuredError,setFeaturedError]=useState(''),[more,setMore]=useState(false),[offset,setOffset]=useState(0),[retry,setRetry]=useState(0);
 const [operators,setOperators]=useState<CruiseOperator[]>([]),[operatorError,setOperatorError]=useState(''),[operatorLoading,setOperatorLoading]=useState(true),[companyOpen,setCompanyOpen]=useState(false),[companyQuery,setCompanyQuery]=useState('');
 const {query,kind,status,operatorId}=filters;
 useEffect(()=>{let active=true;setOperatorLoading(true);setOperatorError('');getCruiseOperators().then(value=>{if(active)setOperators(value)}).catch(e=>{if(active)setOperatorError(e.message)}).finally(()=>{if(active)setOperatorLoading(false)});return()=>{active=false}},[retry]);
 useEffect(()=>{let active=true;setLoading(true);setError('');const timer=setTimeout(()=>void searchCruiseShips({query,kind:kind||undefined,status,operatorId,offset}).then(result=>{if(active){setRows(old=>offset?[...old.slice(0,offset),...result.ships]:result.ships);setMore(result.hasMore)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)}),200);return()=>{active=false;clearTimeout(timer)}},[query,kind,status,operatorId,offset,retry]);
 useEffect(()=>{let active=true;setFeatured([]);setFeaturedError('');getFeaturedCruiseShips({query,kind:kind||undefined,status,operatorId}).then(value=>{if(active)setFeatured(value)}).catch(e=>{if(active)setFeaturedError(e.message)});return()=>{active=false}},[query,kind,status,operatorId,retry]);
 const change=(next:Partial<CruiseDirectoryFilters>)=>{const value={...filters,...next};if(value.query===query&&value.kind===kind&&value.status===status&&value.operatorId===operatorId)return;setRows([]);setFeatured([]);setOffset(0);setMore(false);setFilters(value)};
 const chooseCompany=(id:string)=>{change({operatorId:id});setCompanyOpen(false);setCompanyQuery('');Keyboard.dismiss()};
 const selectedCompany=operators.find(item=>item.id===operatorId)?.name||(operatorId?'Selected cruise line':'All cruise lines');
 const text={color:theme.text},muted={color:theme.textSecondary},panel={backgroundColor:theme.surface,borderColor:theme.border};
 const button=(label:string,onPress:()=>void,selected=false)=><TouchableOpacity accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[styles.button,panel,selected&&{borderColor:theme.primary}]}><Text style={text}>{label}</Text></TouchableOpacity>;
 const renderShip=({ship}:CruiseShipDetail,compact=false)=><TouchableOpacity key={ship.id} accessibilityRole="button" onPress={()=>navigation.navigate('UniverseLanding',{universeId:ship.universe_id})} style={[styles.card,panel,compact&&styles.compact]}>{ship.photo?.permission_verified&&safeCruiseUrl(ship.photo.url)?<Image source={{uri:ship.photo.url}} accessibilityLabel={ship.photo.alt} style={styles.photo}/>:<View style={[styles.placeholder,compact&&styles.compactPlaceholder,{justifyContent:'center',alignItems:'center'}]} accessibilityLabel="No verified ship photo"><Ionicons name="boat-outline" size={compact?40:54} color={theme.textSecondary}/></View>}<View style={{padding:18,gap:10}}><Text style={[styles.small,muted]}>{ship.operator_name} · {ship.kind}</Text><Text style={[styles.title,text,compact&&{fontSize:20}]}>{ship.name}</Text><Text style={{color:theme.primary}}>{ship.operating_status==='announced'?'Announced · not operating':'Explore this ship'} →</Text></View></TouchableOpacity>;
 return <SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ToolHeader title="Cruises" onBack={onBack}/><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={{padding:20,paddingBottom:100,gap:18}}><Text style={[styles.small,muted]}>Cruise Universe</Text><Text style={[styles.heading,text]}>Find your kind of ship.</Text><Text style={muted}>Explore verified ship details, onboard places and guest experiences.</Text><TextInput accessibilityLabel="Search ship or cruise line" placeholder="Ship or cruise line" placeholderTextColor={theme.textSecondary} value={query} onChangeText={value=>change({query:value})} style={[styles.input,text,panel]}/>
 <View style={{gap:8}}><Text style={text}>Cruise line</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Cruise line: ${selectedCompany}`} accessibilityState={{expanded:companyOpen}} onPress={()=>{Keyboard.dismiss();setCompanyOpen(value=>!value)}} style={[styles.button,styles.companyToggle,panel]}><Text style={[text,{flex:1}]}>{selectedCompany}</Text><Ionicons name={companyOpen?'chevron-up':'chevron-down'} color={theme.text} size={18}/></TouchableOpacity>{companyOpen&&<View style={[styles.companyPanel,panel]}><TextInput accessibilityLabel="Search cruise lines" placeholder="Find a cruise line" placeholderTextColor={theme.textSecondary} value={companyQuery} onChangeText={setCompanyQuery} autoCorrect={false} style={[styles.input,text,panel]}/><ScrollView nestedScrollEnabled keyboardShouldPersistTaps="handled" style={{maxHeight:230}} contentContainerStyle={{gap:6}}>{button('All cruise lines',()=>chooseCompany(''),!operatorId)}{operators.filter(item=>item.name.toLocaleLowerCase().includes(companyQuery.trim().toLocaleLowerCase())).map(item=><React.Fragment key={item.id}>{button(item.name,()=>chooseCompany(item.id),operatorId===item.id)}</React.Fragment>)}</ScrollView>{operatorLoading&&<Text style={muted}>Loading cruise lines…</Text>}{!operatorLoading&&!operatorError&&!operators.some(item=>item.name.toLocaleLowerCase().includes(companyQuery.trim().toLocaleLowerCase()))&&<Text style={muted}>No cruise lines match your search.</Text>}{button('Close cruise line picker',()=>{setCompanyOpen(false);Keyboard.dismiss()})}</View>}{!!operatorError&&<View style={{gap:8}}><Text accessibilityRole="alert" style={text}>Cruise lines are temporarily unavailable.</Text>{button('Try again',()=>setRetry(v=>v+1))}</View>}</View>
 <ScrollView horizontal contentContainerStyle={{gap:8}}>{([['','All types'],['ocean','Ocean'],['river','River'],['expedition','Expedition']] as const).map(([id,label])=><React.Fragment key={id}>{button(label,()=>{if(kind!==id)change({kind:id})},kind===id)}</React.Fragment>)}</ScrollView><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>{(['operating','announced'] as const).map(value=><React.Fragment key={value}>{button(value==='operating'?'Operating ships':'Announced ships',()=>{if(status!==value)change({status:value})},status===value)}</React.Fragment>)}</View><Text style={[styles.small,muted]}>The catalog grows as ships and sources are verified. Announced ships are listed separately.</Text>
 {!query.trim()&&featured.length>0&&<View style={{gap:10}}><Text accessibilityRole="header" style={[styles.title,text]}>Featured ships</Text><Text style={muted}>A few starting points selected by Tavvy.</Text><ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={{gap:12,paddingBottom:8}}>{featured.map(item=>renderShip(item,true))}</ScrollView></View>}{!!featuredError&&!query.trim()&&<View style={{gap:8}}><Text style={muted}>Featured ships are temporarily unavailable.</Text>{button('Try again',()=>setRetry(v=>v+1))}</View>}
 <Text accessibilityRole="header" style={[styles.title,text]}>All matching ships</Text>{error?<View style={{gap:12}}><Text accessibilityRole="alert" style={text}>{error}</Text>{button('Try again',()=>setRetry(v=>v+1))}</View>:rows.map(item=>renderShip(item))}{loading&&<Text style={muted}>Loading ships…</Text>}{!loading&&!error&&!rows.length&&<Text style={muted}>No verified ships match these filters. Try another cruise line or ship type.</Text>}{more&&!loading&&!error&&button('Load more ships',()=>setOffset(rows.length))}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({heading:{fontSize:34,fontWeight:'700'},title:{fontSize:24,fontWeight:'600'},small:{fontSize:12,lineHeight:19},button:{borderWidth:1,borderRadius:12,padding:12,minHeight:44,justifyContent:'center'},input:{borderWidth:1,borderRadius:12,padding:12,minHeight:46},card:{borderWidth:1,borderRadius:18,overflow:'hidden'},photo:{width:'100%',aspectRatio:16/9},compact:{width:240},placeholder:{width:'100%',height:130},compactPlaceholder:{height:88},companyToggle:{flexDirection:'row',alignItems:'center',gap:12},companyPanel:{borderWidth:1,borderRadius:12,padding:12,gap:10}});
