import CruisePhotoGallery from './CruisePhotoGallery';
import React,{useEffect,useState} from 'react';
import {View,Text,TouchableOpacity,ScrollView,SafeAreaView,Image,TextInput,Linking,Share,StyleSheet,ActivityIndicator} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {Ionicons} from '@expo/vector-icons';
import {useThemeContext} from '../../contexts/ThemeContext';
import {StoriesRow} from '../StoriesRow';
import {CruiseShipDetail,CRUISE_FACT_DEFINITIONS,displayCruiseFacts,formatCruiseFact,visibleCruiseVenues,visibleCruisePrograms,safeCruiseUrl} from '../../lib/cruises/catalog';
import {getCruiseShip,getCruiseDescription} from '../../lib/cruises/service';
import CruiseReviewPanel from './CruiseReviewPanel';
const tabs=[['overview','Overview'],['onboard','On board'],['cabins','Cabins'],['stories','Photos & stories'],['info','Ship information']] as const;
export default function CruiseUniverse({universeId}:{universeId:string}){
 const navigation=useNavigation<any>(),{theme}=useThemeContext();const[detail,setDetail]=useState<CruiseShipDetail|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[tab,setTab]=useState('overview'),[query,setQuery]=useState(''),[kind,setKind]=useState('all');
 useEffect(()=>{let active=true;setLoading(true);setError('');void getCruiseShip({universeId}).then(value=>{if(active)setDetail(value)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[universeId,retry]);
 const [description,setDescription]=useState<{universeId:string;value:string}|null>(null);
 useEffect(()=>{let active=true;setDescription(null);getCruiseDescription(universeId).then(value=>{if(active)setDescription(value?{universeId:universeId,value}:null)}).catch(()=>{if(active)setDescription(null)});return()=>{active=false};},[universeId,retry]);
 const text={color:theme.text},muted={color:theme.textSecondary},panel={backgroundColor:theme.surface,borderColor:theme.border};const openUrl=(url:string|null)=>{const safe=safeCruiseUrl(url);if(safe)void Linking.openURL(safe).catch(()=>setError('This link could not be opened.'));};
 const button=(label:string,onPress:()=>void)=><TouchableOpacity accessibilityRole="button" onPress={onPress} style={[styles.button,panel]}><Text style={text}>{label}</Text></TouchableOpacity>;
 if(loading||!detail)return <SafeAreaView style={{flex:1,backgroundColor:theme.background}}><View style={{padding:24,gap:18}}>{button('← Back',()=>navigation.goBack())}{loading?<ActivityIndicator color={theme.primary}/>:<><Text style={text}>{error||'Ship not found'}</Text>{button('Try again',()=>setRetry(v=>v+1))}</>}</View></SafeAreaView>;
 const{ship,sources}=detail,venues=visibleCruiseVenues(detail),facts=displayCruiseFacts(ship,sources),image=ship.photo?.permission_verified&&safeCruiseUrl(ship.photo.url)?ship.photo:null;
 const sourceLinks=(ids:string[])=><View style={{gap:6}}>{ids.map(id=>{const source=sources.find(s=>s.id===id);return source&&safeCruiseUrl(source.url)?<TouchableOpacity accessibilityRole="link" key={id} onPress={()=>openUrl(source.url)}><Text style={[styles.small,{color:theme.primary}]}>{source.publisher} · checked {source.checked_at} ↗</Text></TouchableOpacity>:null})}</View>;
 return <SafeAreaView style={{flex:1,backgroundColor:theme.background}}><ScrollView contentContainerStyle={{padding:18,paddingBottom:100,gap:20}}><View style={styles.row}>{button('← Back',()=>navigation.goBack())}{button('Share ship',()=>{void Share.share({message:`${ship.name}\nhttps://tavvy.com/app/cruises/${ship.slug}`,url:`https://tavvy.com/app/cruises/${ship.slug}`})})}</View>{image?<Image source={{uri:image.url}} accessibilityLabel={image.alt} style={styles.hero}/>:<View style={[styles.hero,panel,{justifyContent:'center',alignItems:'center'}]} accessibilityLabel="No verified ship photo"><Ionicons name="boat-outline" size={64} color={theme.textSecondary}/></View>}<View style={{gap:10}}><Text style={muted}>{ship.operator_name} · {ship.kind}</Text><Text style={[styles.title,text]}>{ship.name}</Text>{description?.universeId===ship.universe_id&&<Text style={muted}>{description.value}</Text>}<Text style={muted}>{ship.operating_status==='announced'?'Announced ship · not currently operating':'Operating overnight cruise ship'}</Text>{safeCruiseUrl(ship.official_url)&&button('Official ship website ↗',()=>openUrl(ship.official_url))}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{tabs.map(([id,label])=><TouchableOpacity key={id} accessibilityRole="tab" accessibilityState={{selected:tab===id}} onPress={()=>setTab(id)} style={[styles.button,panel,tab===id&&{borderColor:theme.primary}]}><Text style={[text,tab===id&&{color:theme.primary,fontWeight:'700'}]}>{label}</Text></TouchableOpacity>)}</ScrollView>{!!error&&<Text accessibilityRole="alert" style={text}>{error}</Text>}
 {tab==='overview'&&<><CruiseReviewPanel ship={ship}/><View style={styles.facts}>{facts.filter(f=>['year_built','guests_double_occupancy','guests_lower_berths','guests_maximum','decks_passenger'].includes(f.key)).slice(0,4).map(f=><View key={f.key} style={[styles.fact,panel]}><Text style={[styles.heading,text]}>{formatCruiseFact(f)}</Text><Text style={[styles.small,muted]}>{CRUISE_FACT_DEFINITIONS[f.key].label}</Text></View>)}</View>{button('Explore places on this ship →',()=>setTab('onboard'))}</>}
 {tab==='onboard'&&<><Text style={[styles.heading,text]}>On board</Text><Text style={muted}>{venues.length} verified venue listings. This may not be the ship’s complete venue list.</Text><TextInput accessibilityLabel="Find a venue on this ship" value={query} onChangeText={setQuery} placeholder="Find dining, shows, shops…" placeholderTextColor={theme.textSecondary} style={[styles.input,text,panel]}/><ScrollView horizontal contentContainerStyle={{gap:8}}>{['all',...new Set(venues.map(v=>v.kind))].map(k=><TouchableOpacity key={k} accessibilityRole="button" accessibilityState={{selected:kind===k}} onPress={()=>setKind(k)} style={[styles.button,panel,kind===k&&{borderColor:theme.primary}]}><Text style={text}>{k==='all'?'All venues':k.replace(/_/g,' ')}</Text></TouchableOpacity>)}</ScrollView>{venues.filter(v=>(kind==='all'||v.kind===kind)&&v.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(v=><View key={v.id} style={[styles.card,panel]}><Text style={[styles.small,muted]}>{v.kind.replace(/_/g,' ')}{v.deck_label?` · ${v.deck_label}`:''}</Text><Text style={[styles.heading,text]}>{v.name}</Text>{v.description&&<Text style={muted}>{v.description}</Text>}{v.included!==null&&<Text style={muted}>{v.included?'Included':'Additional charge'}</Text>}{v.availability_note&&<Text style={muted}>{v.availability_note}</Text>}{sourceLinks(v.source_ids)}{v.place_id&&button('Venue details & reviews →',()=>navigation.navigate('PlaceDetails',{placeId:v.place_id}))}</View>)}{!venues.length&&<Text style={muted}>Verified venue details are being added.</Text>}</>}
 {tab==='onboard'&&visibleCruisePrograms(detail).length>0&&<><Text style={[styles.heading,text]}>Shows & programs</Text><Text style={muted}>Programs may vary by sailing. Check the official source for current availability.</Text>{visibleCruisePrograms(detail).map(program=><View key={program.id} style={[styles.card,panel]}><Text style={[styles.small,muted]}>{program.kind} · as of {program.as_of}</Text><Text style={[styles.heading,text]}>{program.name}</Text>{program.description&&<Text style={muted}>{program.description}</Text>}{program.venue_id&&<Text style={muted}>{venues.find(v=>v.id===program.venue_id)?.name}</Text>}{program.availability_note&&<Text style={muted}>{program.availability_note}</Text>}{sourceLinks(program.source_ids)}</View>)}</>}
 {tab==='cabins'&&<><Text style={[styles.heading,text]}>Cabin categories</Text><Text style={muted}>Compare cabin categories without sharing your cabin number or current location.</Text>{ship.cabin_categories.map(c=><View key={c.id} style={[styles.card,panel]}><Text style={[styles.heading,text]}>{c.name}</Text>{c.description&&<Text style={muted}>{c.description}</Text>}{c.accessible!==null&&<Text style={muted}>{c.accessible?'Accessible option documented':'Not identified as an accessible category'}</Text>}{sourceLinks(c.source_ids)}</View>)}{!ship.cabin_categories.length&&<Text style={muted}>Verified cabin category details are being added.</Text>}</>}
 {tab==='stories'&&<><Text style={[styles.heading,text]}>Photos & stories</Text><CruisePhotoGallery key={ship.id} shipId={ship.id} cover={image}/><StoriesRow universeId={ship.universe_id}/><Text style={muted}>Stories belong to places on this ship. Venue offerings and shows may vary by sailing.</Text></>}
 {tab==='info'&&<><Text style={[styles.heading,text]}>Ship information</Text><Text style={muted}>Unknown specifications are omitted. Counts use the source’s stated definition.</Text>{facts.map(f=><View key={f.key} style={[styles.card,panel]}><Text style={muted}>{CRUISE_FACT_DEFINITIONS[f.key].label}</Text>{CRUISE_FACT_DEFINITIONS[f.key].type==='url'?button('Open official information ↗',()=>openUrl(String(f.value))):<Text style={[styles.heading,text]}>{formatCruiseFact(f)} {CRUISE_FACT_DEFINITIONS[f.key].unit}</Text>}<Text style={[styles.small,muted]}>As of {f.as_of}{f.note?` · ${f.note}`:''}</Text>{sourceLinks(f.source_ids)}</View>)}{!facts.length&&<Text style={muted}>Verified specifications are being added.</Text>}<Text style={[styles.heading,text]}>Identity & history</Text>{ship.imo&&<Text style={text}>IMO: {ship.imo}</Text>}{ship.eni&&<Text style={text}>ENI: {ship.eni}</Text>}{ship.name_history.map((h,index)=><View key={index} style={{gap:6}}><Text style={text}>{h.name}{h.operator_name?` · ${h.operator_name}`:''}{h.valid_from?` · from ${h.valid_from}`:''}{h.valid_until?` to ${h.valid_until}`:''}</Text>{sourceLinks(h.source_ids)}</View>)}<Text style={[styles.heading,text]}>Operating status sources</Text>{sourceLinks(ship.status_source_ids)}<Text style={[styles.small,muted]}>Gross tonnage describes enclosed volume, not ship weight. Double-occupancy, lower-berth and maximum capacities are different measures.</Text></>}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({row:{flexDirection:'row',justifyContent:'space-between',gap:12},button:{padding:12,minHeight:44,borderWidth:1,borderRadius:12,justifyContent:'center'},hero:{width:'100%',aspectRatio:16/9,borderRadius:20},title:{fontSize:34,fontWeight:'700'},heading:{fontSize:22,fontWeight:'600'},small:{fontSize:12,lineHeight:19},card:{borderWidth:1,borderRadius:16,padding:18,gap:12},input:{borderWidth:1,borderRadius:12,padding:12,minHeight:46},facts:{flexDirection:'row',flexWrap:'wrap',gap:10},fact:{width:'48%',flexGrow:1,borderWidth:1,borderRadius:14,padding:16,gap:8}});
